### ISSUE TITLE
Example code without `BuildWebHost` breaks Entity Framework 2.0

### ISSUE THREAD

**Issue by janpieterz** [serilog/serilog-aspnetcore#10]
Took me half a morning before I figured out what was exactly going on. 
My Identity Server project used the provided way here to create the host, but Entity Framework relies on the `BuildWebHost` method to analyse it for contexts.

Let me know if you'd like me to change the sample and docs here to below, I believe it contains all that's needed for a valid Serilog + AspNetCore flow.

Program.cs:
```c#
public class Program
    {
        public static IConfiguration Configuration { get; set; }
        public static int Main(string[] args)
        {
            Configuration = CreateConfiguration();

            Logging.Config(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development");

            try
            {
                Log.Information("Starting up application");

                var host = BuildWebHost(args);

                host.Run();

                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        private static IConfiguration CreateConfiguration()
        {
            return new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .Build();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseConfiguration(CreateConfiguration())
                .UseSerilog()
                .UseStartup<Startup>()
                .Build();
    }
```

**Comment by nblumhardt** [comment]
Hi Jan-Pieter, thanks for the report.

Do you mean that a method called `BuildWebHost` needs to exist? I think I might be misunderstanding what you mean here, as that seems slightly strange... :-) Is there any way of narrowing the change down to a single line of code?

Thanks again!

**Comment by janpieterz** [comment]
Hi Nick!

Yep, the BuildWebHost needs to exists, that's what it ended up as. The unbelievable bit was what made it cost so much time, I never thought this was the issue and compared a working sample and a not-working app, and brought them closer and closer until this was the only difference.

For reference:

https://github.com/aspnet/EntityFrameworkCore/issues/9415#issuecomment-327589912
and the linked article (bottom of the section)
https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#update-main-method-in-programcs

Single LOC change might be difficult as the Configuration also needs to be callable from that static bit as well as the normal flow. 
Currently I create it twice, which certainly isn't pretty, just to be able to (in other apps) have the configuration for Seq.

**Comment by nblumhardt** [comment]
Wow, thanks for the links, that's frankly one of the strangest design points I've seen in an ORM to date. Would love to know the backstory. I'll take a look at the sample again 👍

**Comment by nblumhardt** [comment]
@janpieterz I've updated the example in the main `README`. I'm keen to update the sample repository, but I'd love to come up with a way to do it that doesn't double up on loading the configuration... May be a bit hopeful on my part... Any ideas?

**Comment by janpieterz** [comment]
Nice. Yeah, I'd be curious what the MS team has to say about this.

We could look to set a private static variable that a `GetConfiguration` method returns?
Not the prettiest. 

```c#
private static IConfiguration _cachedConfig;

private static IConfiguration GetConfiguration()
{
    if (_cachedConfig == null)    
    {
        _cachedConfig = new ConfigurationBuilder()        
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .Build();
    }
    return _cachedConfig;
}

public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseConfiguration(GetConfiguration())
        .UseSerilog()
        .UseStartup<Startup>()
        .Build();
```

**Comment by nblumhardt** [comment]
Thanks for jumping in, @RehanSaeed 👍 .. The sample is now updated ( #17 ) so I'll close this - I think it'd be a great topic for a blog post, which might be a better candidate for top Google result for "serilog entity framework core" than we can achieve with the README. Cheers!
