### ISSUE TITLE
property CorrelationId is null always

### ISSUE THREAD

**Issue by martinmani** [serilog/serilog-aspnetcore#106]
The CorrelationId is always null for every log it writes. Even in the example given in [readme](https://github.com/serilog/serilog-aspnetcore), it showing as null. 

just wondering, what is the configuration/code to set value for it?

**Comment by nblumhardt** [comment]
This property is set by ASP.NET Core itself, so you might need to check out under which conditions the framework sets it.

**Comment by emrhesen** [comment]
Are you resolve this problem ? @martinmani 

My Serilog Properties example xml file below , correlationId always null
![Capture](https://user-images.githubusercontent.com/9653381/63194757-82d3b880-c079-11e9-9ef3-0118c0ff24d2.PNG)

Is there any example code for correlationId settings on asp.net core

**Comment by nblumhardt** [comment]
Hi all - there's a bunch of info on how this works, and more discussion, over in: https://github.com/aspnet/AspNetCore/issues/5914#issuecomment-380693192

In 2.x, your incoming requests need to carry a `Request-Id` header in order for the `CorrelationId` log event property to be set. In 3.0 it sounds like some more options are in the pipeline.

As it's an ASP.NET feature I'll close the ticket, here. Thanks!

**Comment by emrhesen** [comment]
Thank you for this explanation , @nblumhardt
