### ISSUE TITLE
When is release 3.0.0.* scheduled for?

### ISSUE THREAD

**Issue by VictorioBerra** [serilog/serilog-aspnetcore#108]
Also does the version line up with Core 3 on purpose? So it releases when 3 does? Or is that just a coincidence?

**Comment by nblumhardt** [comment]
The version numbers currently happen to line up, though we've been holding back on a release in case incompatible changes are introduced and we need to to deal with them via the major version increment. It seems unlikely there will be 2.2-3.0 breaking changes that impact this library, though, so it's possible we'll ship 3.0.0 with a dependency on 2.x+.

Are you using the new request logging features, or provider integration? Would be great to know what you are planning to consume from 3.0.0 and whether you have any feedback on how the APIs suit your usage. Cheers!

**Comment by VictorioBerra** [comment]
We are looking forward to the new request logging middleware, after testing out the pre-release we are really excited about how much cleaner and simpler the output is.

**Comment by nblumhardt** [comment]
Awesome, thanks for the feedback 👍
