### ISSUE TITLE
RequestLoggingMiddleware does not include RequestId

### ISSUE THREAD

**Issue by tomkerkhove** [serilog/serilog-aspnetcore#122]
`RequestLoggingMiddleware` does not include `RequestId`, is this on purpose or provided via a similar package?

If not, are there plans to surface the information as well?

**Comment by nblumhardt** [comment]
Hi! Thanks for the note. You need to add `Enrich.FromLogContext()` to your logger configuration in order to get all of the properties ASP.NET Core pushes onto the stack, including this one. Let me know if this doesn't help. Cheers!

**Comment by tomkerkhove** [comment]
Thanks for the tip but we've already included `Enrich.FromLogContext`. For sake of being sure, I've moved it up before our own enrichment but it seems like it doesn't help.

Here is what we use:
```csharp
var logConfiguration = new LoggerConfiguration()
                .MinimumLevel.Is(telemetrySettings.MinimumLogLevel)
                .Enrich.WithProperty("ComponentName", componentName)
                .Enrich.FromLogContext()
                .Enrich.With<OperationIdEnricher>() // Uses 'RequestId'
                .Enrich.WithMachineName()
                .Enrich.WithExceptionDetails(new DestructuringOptionsBuilder()
                    .WithDefaultDestructurers()
                    .WithDestructurers(new[] {new DbUpdateExceptionDestructurer()}));
```

**Comment by nblumhardt** [comment]
That's interesting - thanks Tom. I do see the value, which is strange... Are you using `UseSerilog()` to set up ASP.NET Core logging?

**Comment by tomkerkhove** [comment]
No we are using the following:
```csharp
var logConfiguration = BuildLogger(app, componentName, configuration);
Log.Logger = logConfiguration.CreateLogger();
```

This is based on the [configuration docs](https://github.com/serilog/serilog/wiki/Configuration-Basics#creating-a-logger).

**Comment by nblumhardt** [comment]
Ah, great - thanks for the follow-up, Tom.

The `RequestId` properties and others are pushed onto the log context by ASP.NET Core, so you need `UseSerilog()` somewhere in there to hook this up. The README in this repo should show an example.

We could definitely investigate adding these properties via the middleware ourselves, but there's probably a bit to consider around which properties we can grab.

Let me know if this helps,
Nick

**Comment by tomkerkhove** [comment]
Ah I figured you were asking if we pass the configuration to `UseSerilog()`.

We do indeed use `UseSerilog()`:
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) => WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging(loggingBuilder => loggingBuilder.ClearProviders())
            .ConfigureAppConfiguration((builder, config) =>
            {
                config.SetBasePath(Directory.GetCurrentDirectory());
                config.AddYamlFile(
                    "/config/runtime.yml", optional: false, reloadOnChange: true);
                config.AddEnvironmentVariables(prefix: "MNO_");
            })
            .UseStartup<Startup>()
            .UseSerilog();
```

But we only configure the logConfiguration after that given we need the configuration and some dependencies in order to build it. This might be the issue then?

**Comment by nblumhardt** [comment]
Interesting 🤔 ... I'm wondering whether perhaps the hosting model might make a difference? (IIS vs Kestrel, ...)

Also, just in case I've misunderstood, are you viewing the events as JSON or as plain text? (If the latter, the request id won't normally appear, unless the output template is overridden.)

**Comment by tomkerkhove** [comment]
I've verified and did not see `RequestId` in Application Insights nor via the custom enrichers that we are using.

Given we are using the default builder [it means that we run Kestrel](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#set-up-a-host). Did you use IIS in the past or Kestrel as well?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I'm using Kestrel, currently.

Are you able to send a redacted screenshot or paste of a typical request completion event with all of its properties? Based on which properties are included and which aren't, we might be able to spot a pattern.

**Comment by tomkerkhove** [comment]
Sure, but can you clarify what you mean with request completion event please?

Are you referring to an output trace or use the debugger to get more info?

**Comment by nblumhardt** [comment]
👍 the middleware writes out a single event on the completion of each web request, e.g. `HTTP GET / returned 404 in 200 ms` - it would be great to see one of these.

Showing the event in App Insights or via JSON-formatted console or file output would have all the info.

**Comment by tomkerkhove** [comment]
Sure, this is what we have in Application Insights:
![image](https://user-images.githubusercontent.com/4345663/64316721-ecc6ea00-cfb5-11e9-9e46-23a82cf6ee87.png)

And it includes the following custom properties:

![image](https://user-images.githubusercontent.com/4345663/64316682-d587fc80-cfb5-11e9-862c-d19482aa2b2b.png)

*The sections in red are added by our enrichers*

**Comment by nblumhardt** [comment]
Super strange! Have you tried moving the `UseSerilogRequestLogging()` middleware to different points in the middleware pipeline?

Keen to get to the bottom of this but not really sure where to start except by reading the ASP.NET Core source, which will have the answers but can take some time to digest :-) 

Would love to hear whether you spot any clues!

**Comment by tomkerkhove** [comment]
I might be mixing the RequestLoggingMiddleware with the plain AspNetCore features but it's not being added here: https://github.com/serilog/serilog-aspnetcore/blob/64924c4d1369a69ba5c831dce24fa58a6595578b/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L82

Is it because some other component is adding it, for example via an enricher?

**Comment by tomkerkhove** [comment]
I've checked and we add `UseSerilogRequestLogging` as part of `UseRuntimeLogging`

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
   if (env.IsDevelopment())
   {
      app.UseDeveloperExceptionPage();
   }
   else
   {
      // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
   }

   app.UseRuntimeLogging(componentName: ApiName, Configuration)
      .UseExceptionHandling()
      .UseMvc()
      .UseOpenApiUi(ApiName);
}
```

Which does the following:
```csharp
public static IApplicationBuilder UseRuntimeLogging(this IApplicationBuilder app, string componentName, IConfiguration configuration)
{
   Guard.NotNullOrWhitespace(componentName, nameof(componentName));

   // Define logger
   var logConfiguration = BuildLogger(app, componentName, configuration);
   Log.Logger = logConfiguration.CreateLogger();

   // Use request tracking
   app.UseSerilogRequestLogging();

   return app;
}
```

**Comment by nblumhardt** [comment]
Woohoo! I think I've repro'd this :-)

It looks like:

```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseSerilog()
                .UseStartup<Startup>();
```

writes the `RequestId`, while:

```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseSerilog();
```

does not. Note the switched order of `UseSerilog()` and `UseStartup()`.

Does switching those two statements fix it for you, @tomkerkhove ?

**Comment by nblumhardt** [comment]
I just looped back around to this and can no longer observe the behavior I thought I'd seen above - I may have just misread the JSON output :-(

But, in my fresh ASP.NET Core 2.2 app I'm no longer seeing `RequestId` on request completion events - looks like there's some difference between this and .NET Core 3.0, where I'm doing most day-to-day development at the moment. I think we should call this a bug 👍

**Comment by nblumhardt** [comment]
Nope, just realised my mistake, I'd left out the crucial `Enrich.FromLogContext()` in my test app 🤦‍♂️

Just ran through all hosting models and variations from ASP.NET Core 2.2 and 3.0, `RequestId` is included every time.

Tom, would it be possible for you to spin up a new blank app, configure `UseSerilogRequestLogging()`, and check out the results? If the `RequestId` is there, as it should be, then working step-by-step towards the configuration used by your main app should uncover whatever is breaking it.

**Comment by tomkerkhove** [comment]
Sorry for the late response but I just got back from holiday!

I'll try to have another look when I have some time but it looks like it might just be us then 🤔.

**Comment by nblumhardt** [comment]
Thanks - will be great to hear whether you find anything. My turn for a holiday now (off for three weeks :-)) but I'll keep an eye out for any updates.

**Comment by nblumhardt** [comment]
Closing, hopeful that you've tracked this down - we'll need some repros or more analysis if we're to go forward with this, in any case. Cheers!

**Comment by tomkerkhove** [comment]
I still haven't found the time to have a look at it - Sorry!

I'll reopen if I find some time or stumble upon it again!

Thanks for helping anyway!
