### ISSUE TITLE
RequestLoggingMiddleware does not add a SourceContext when logging

### ISSUE THREAD

**Issue by adamlith** [serilog/serilog-aspnetcore#123]
This makes it unusable for us as we filter logmessages based on source context and log level.

**Comment by nblumhardt** [comment]
Thanks for the note; I'd considered this originally but thought I'd lean towards smaller event payloads without it, but in hindsight it should probably be there 👍

**Comment by alexvaluyskiy** [comment]
@nblumhardt have you plan to release this bugfix soon? 
Without `Log.ForContext<RequestLoggingMiddleware>()` we can't override a log level by a namespace

**Comment by nblumhardt** [comment]
Hi @alexvaluyskiy - have you tried the current pre-release (`-dev-*`) package, and does it work as required for you? I'll open a release PR now, keen to have any feedback/validation of the prerelease that you can send.

**Comment by alexvaluyskiy** [comment]
@nblumhardt yes, the current `dev` version works great
