### ISSUE TITLE
RequestLoggingMiddleware uses DateTime.Now rather than UtcNow

### ISSUE THREAD

**Issue by tomkerkhove** [serilog/serilog-aspnetcore#128]
RequestLoggingMiddleware uses DateTime.Now rather than UtcNow, is that on purpose?

https://github.com/serilog/serilog-aspnetcore/blob/64924c4d1369a69ba5c831dce24fa58a6595578b/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L90

If not, happy to jump in and help change this.

**Comment by nblumhardt** [comment]
Thanks for spotting this; yes, it's intentional - Serilog uses `DateTimeOffset` and local time internally; once logs leave the local process they're either converted to UTC, or written in ISO 8601 with offsets included.

**Comment by tomkerkhove** [comment]
Perfect, thanks for explaining!
