### ISSUE TITLE
The sample web app does not allow extra configuration sections to be loaded from the Startup class

### ISSUE THREAD

**Issue by amoerie** [serilog/serilog-aspnetcore#13]
The sample web app at https://github.com/serilog/serilog-aspnetcore/tree/dev/samples/SimpleWebSample creates an IConfigurationRoot in Program.cs and then calls UseConfiguration(...) on the WebhostBuilder to register this, which is correct. Then, in the Startup.cs class an IConfiguration object is injected.

However, this object is not the configuration root, but a MemoryConfigurationProvider which just lists the configuration keys + values which have been registered. In some cases this might be okay, but if you try to load any extra configuration sections from within the Startup.cs class, **this will fail**.

As per [this SO question](https://stackoverflow.com/questions/41290566/net-core-pass-commandline-args-to-startup-cs-from-program-cs) you actually need to register IConfigurationRoot in the DI container, so you can inject an IConfigurationRoot object in Startup.cs.

So your Program.cs starts looking like this:

```csharp
new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .ConfigureServices(s => s.AddSingleton(configuration)) // <-- this allows IConfigurationRoot injection in Startup.cs
        .UseStartup<Startup>()
        .UseConfiguration(configuration)
        .UseSerilog()
        .Build();
```

And the Startup.cs has to be modified like this:

```csharp
  public class Startup {
    public IConfiguration Configuration { get; }

    public Startup(IConfigurationRoot configuration) {
      Configuration = configuration;
    }
    ...
  }
```

This then allows you to read extra config sections, etc.

```csharp
  public class Startup {
    public IConfiguration Configuration { get; }

    public Startup(IConfigurationRoot configuration) {
      Configuration = configuration;
    }

    public void ConfigureServices(IServiceCollection services) {
      var mySection = Configuration.GetSection("MySection");
      ...
    }
    ...
  }

```

**Comment by nblumhardt** [comment]
Thanks for the insights @amoerie ! We'll update the sample 👍 

(PR welcome if anyone is able to take a look.)

**Comment by alex-nicholas** [comment]
@nblumhardt  - Is this handled? If not - I'd like to have a quick chat with you about it on Saturday @ DDD Bne if you'll have a minute. I'd love to contribute

**Comment by nblumhardt** [comment]
Hi @alex-nicholas - thanks for jumping in 👍 ... there's now a new overload to `UsingSerilog()` that partially covers this, but I'd love to hear your thoughts, hope I catch you on Saturday, then!
