### ISSUE TITLE
Record MVC information to the request completion event

### ISSUE THREAD

**Issue by rossbuggins** [serilog/serilog-aspnetcore#131]
Utilise ActionFilters to support MVC - either in this, or an additional package Serilog.AspNetCore.Mvc?

Something like the below and then register it in the MvcCore options?
```
   public class MvcLoggerFilter : ActionFilterAttribute
    {
        IDiagnosticContext diag;
        public MvcLoggerFilter(
            IDiagnosticContext diag)
        {
            this.diag = diag;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (context.ModelState.IsValid)
            {
                var t = context.ActionDescriptor.DisplayName;
                diag.Set("ActionDescriptor.DisplayName", t);
            }
        }
    }
```

**Comment by sungam3r** [comment]
Only `"ActionDescriptor.DisplayName"` ?

**Comment by rossbuggins** [comment]
Probably more than that - will have a dig through and see what makes sense

________________________________

**Comment by rossbuggins** [comment]
I've created a PR #133 with my current mvc integration

**Comment by nblumhardt** [comment]
This is broad enough to require some more discussion/bake time than we can currently accommodate in this package's release cycle, so I've closed the current PR, but I'll leave this issue open to track where this goes 👍

**Comment by rossbuggins** [comment]
As per PR discussion, I've started a separate repo for now at https://github.com/rossbuggins/serilog-aspnetcore-mvc

**Comment by nblumhardt** [comment]
Too cool! 😎 .. I'll help get the word out 👍
