### ISSUE TITLE
Excess properties in every LogEvent.

### ISSUE THREAD

**Issue by iPilot** [serilog/serilog-aspnetcore#135]
Using Serilog.AspNetCore i have found that a lot of log events contains properties like 
_ActionId, ActionName, ConnectionId, CorrelationId, RequestId, RequestPath_
even when logs doesn't the http-request logs (actually it was temporary enabled TCP logs).

TCP message processor has a static readonly ILogger and right after app starts all works fine, but when first http request occured the excess properties appear.
Am i using ILogger right way?

**Comment by nikriaz** [comment]
What was a resolution? I have the same problem. If the logging level is "Debug", exactly these unwanted properties start to appear: ActionId, ActionName, ConnectionId, CorrelationId, RequestId, RequestPath. How to get rid of them?
