### ISSUE TITLE
"UseSerilog()" Latest version with .net core 2.2

### ISSUE THREAD

**Issue by Doidel** [serilog/serilog-aspnetcore#144]
Unfortunately, I can't upgrade my project to 3.0 yet, which is why I'm still on 2.2. I've just installed the latest version of serilog and now "UseSerilog" is invalid. I know that 3.0 changed some of the setup in Program.cs, e.g. changing IWebHostBuilder to IHostBuilder, so I'm wondering whether the latest version is only built for 3.0?
```
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Serilog;
using Serilog.Events;
using System;

namespace myapp
{
    public class Program
    {
        public static int Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .WriteTo.File("log.txt", rollingInterval: RollingInterval.Day)
            .CreateLogger();
           
            try
            {
                Log.Information("Starting web host");
                CreateWebHostBuilder(args).Build().Run();
                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
       
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseSetting("https_port", "443")
                .UseStartup<Startup>()
                .UseSerilog(); // this line has an error
    }
}
```

> 'IWebHostBuilder' does not contain a definition for 'UseSerilog' and no accessible extension method 'UseSerilog' accepting a first argument of type 'IWebHostBuilder' could be found (are you missing a using directive or an assembly reference?)

What am I missing? When googling old serilog tutorials they all use "UseSerilog()" for IWebHostBuilder.

Oh and the following packages are installed:

- Serilog
- Serilog.Sinks.Async
- Serilog.Sinks.Console
- Serilog.Sinks.File

Thanks for some help!

**Comment by nblumhardt** [comment]
Interesting - the `UseSerilog()` extension for `IWebHostBuilder`/.NET Core 2.2 is still supported, could there have been a package installation/upgrade issue? I notice that _Serilog.AspNetCore_ isn't in the list of packages in your post - just an oversight?

**Comment by Doidel** [comment]
That was it - sorry for the bother!

**Comment by jbfp** [comment]
Downgrading to Serilog.AspNetCore 2.1.1 worked for me.

**Comment by Doidel** [comment]
@jbfp If it's the same issue I had you just need to add the latest "Serilog.AspNetCore" nuget package. I'm running 2.2 and it works.

**Comment by mslot** [comment]
Istead of installing serilog.aspnetcore, you could just do

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureServices((hostContext, services) =>
            {
                ...
                services.AddSingleton<ILoggerFactory>(services => new SerilogLoggerFactory(Log.Logger, false));

            });
```

I do this when running console applications, where i don't need aspnetcore.

**Comment by Sike123** [comment]
> @jbfp If it's the same issue I had you just need to add the latest "Serilog.AspNetCore" nuget package. I'm running 2.2 and it works.

This worked for me. Thanks
