### ISSUE TITLE
Log requests in UTC timezone

### ISSUE THREAD

**Issue by tomkerkhove** [serilog/serilog-aspnetcore#145]
As of today, requests are logged in the local time. Would be good if this was changed into UTC or surfaced in the options.

https://github.com/serilog/serilog-aspnetcore/blob/dev/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L91

Happy to send a PR if you agree

**Comment by nblumhardt** [comment]
Hi Tom, thanks for the note. All Serilog events are logged using `DateTimeOffset.Now`, so this is for consistency. How the event is persisted depends on the sink, however, with many sinks choosing UTC as the stored representation (if you need a hand figuring out how to configure a particular sink, let us know). Cheers!

**Comment by tomkerkhove** [comment]
Makes sense, thanks for the fast response!
