### ISSUE TITLE
Wrapped enrichers, conditional/leveled enrichers, conditional

### ISSUE THREAD

**Issue by robertmujica** [serilog/serilog-aspnetcore#153]
Hey guys, is there any plan to bring following feature / PR https://github.com/serilog/serilog/pull/1316/ to aspnetcore ?, it would be really useful or is there an equivalent feature so we have a way to setup different subset of enrichers at different level, I cannot see it on latest stable version v3.2.0

**Comment by nblumhardt** [comment]
Hi Robert,

The linked PR is for a Serilog feature, if you `dotnet add package Serilog -v 2.9.0` to ensure you have the latest version, this feature will be present.

Hope this helps,
Nick

**Comment by nblumhardt** [comment]
Assuming the above will have you unblocked; let us know if not. Cheers!

**Comment by robertmujica** [comment]
@nblumhardt thanks for quick reply, yes I can see new extension method once i added Serilog NuGet to our project.
