### ISSUE TITLE
Logging does not work in Controller

### ISSUE THREAD

**Issue by TheNetStriker** [serilog/serilog-aspnetcore#154]
I'm trying to implement Serilog into my Asp.net Core 2.2 MVC webservice. I've managed to get the logging to work in the Startup class, but then it doesn't work in the Controller. Here is how I configure the logging:

Program.cs:
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
{
    var config = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json", optional: false)
        .Build();

    var webHost = WebHost.CreateDefaultBuilder(args)
        .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
            .ReadFrom.Configuration(hostingContext.Configuration)
            .Enrich.FromLogContext())
        .UseUrls(config.GetValue<string>("urls"))
        .UseKestrel()
        .UseStartup<Startup>();

    return webHost;
}
```

This is the appsettings.json configuration:
```
"Serilog": {
  "Using": [ "Serilog.Sinks.File", "Serilog.Sinks.Console" ],
  "MinimumLevel": "Error",
  "WriteTo": [
    {
      "Name": "File",
      "Args": { "path": "Log\\Application.log" }
    },
    { "Name": "Console" }
  ],
  "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
  "Properties": {
    "Application": "IDBrowserServiceCore"
  }
}
```

In the Startup class logging works:
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILogger<Startup> logger)
{
    logger.LogError("TEST1");
}

But in the controller the logging does nothing:
```
[Route("api/[controller]/[action]")]
public class ValuesController : Controller
{
        public ValuesController(ILogger<ValuesController> logger)
        {
            this.logger = logger;
            this.logger.LogError("TEST2");
        }
}
```

The logging command in the controller does not log to the file or the console. What am I doing wrong?

**Comment by sungam3r** [comment]
@TheNetStriker You use wrong config. This happens.
```c#
 .ReadFrom.Configuration(config)
```

**Comment by TheNetStriker** [comment]
Changing this line also doesn't help. I still only get the TEST1 log entry, but not the TEST2. Any other ideas?

**Comment by sungam3r** [comment]
Check `ILogger<ValuesController>` type - MS or Serilog ?

**Comment by TheNetStriker** [comment]
ILogger is Microsoft.Extensions.Logging.ILogger, but in the Startup class it is the same type and there it works. Also there seems to be no Serilog.ILogger with an argument type for the ValuesController class. Or am I maybe missing a NuGet package for this? I've installed the following ones:

Serilog.AspNetCore
Serilog.Settings.Configuration
Serilog.Sinks.Console
Serilog.Sinks.File

**Comment by TheNetStriker** [comment]
@sungam3r I found out what makes the difference in my app. I create additional services in the Configure method for different databases. Here is the complete code of the method:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILogger<Startup> logger)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseSerilogRequestLogging();

    try
    {
        IEnumerable<IConfigurationSection> sites = Configuration.GetSection("Sites").GetChildren();

        foreach (IConfigurationSection site in sites)
        {
            //https://www.strathweb.com/2017/04/running-multiple-independent-asp-net-core-pipelines-side-by-side-in-the-same-application/
            app.UseBranchWithServices("/" + site.Key,
            services =>
            {
                services
                    .AddMvc()
                    .AddXmlSerializerFormatters();
                        
                services
                    .AddSingleton<IConfiguration>(Configuration);

                services.Configure<ServiceSettings>(site.GetSection("ServiceSettings"));

                var strDbType = site["ConnectionStrings:DBType"];

                if (strDbType.Equals("MsSql"))
                {
                    var strConnection = site["ConnectionStrings:MsSql"];
                    services.AddDbContextPool<IDImagerDB>(options => options.UseSqlServer(strConnection));
                }
                else if (strDbType.Equals("Postgres"))
                {
                    var strConnection = site["ConnectionStrings:Postgres"];
                    services.AddDbContextPool<IDImagerDB>(options => options
                        .UseNpgsql(strConnection)
                        .ReplaceService<ISqlGenerationHelper, PostgresSqlGenerationHelper>());
                }
                else
                {
                    throw new Exception("DBType not supported, supported type are 'MsSql' and 'Postgres'.");
                }
            },
            appBuilder =>
            {
                appBuilder.UseMvc();
            });
        }

        app.Run(async c =>
        {
            await c.Response.WriteAsync("Service online!");
        });
    }
    catch (Exception ex)
    {
        logger.LogError(ex.ToString());
    }
}
```

Is there a way to use Serilog with this UseBranchWithServices method?

**Comment by sungam3r** [comment]
Do such things in `Configure` method is too late. `ServiceProvider` has already been created. You should configure your services in `ConfigureServices`.

**Comment by TheNetStriker** [comment]
@sungam3r The problem is that my method requires the IApplicationBuilder.UseBranchWithServices method to work. I found the instructions here: https://www.strathweb.com/2017/04/running-multiple-independent-asp-net-core-pipelines-side-by-side-in-the-same-application/

Is there also a way to do this in the ConfigureServices method? I found no examples so far.

**Comment by sungam3r** [comment]
`Configure` method is for plugging in middlewares into `*ApplicationBuilder`.

**Comment by TheNetStriker** [comment]
@sungam3r I guess so, but I need to run multiple instances of my controllers for different databases and this seems to be the only way I found how to do this. Please look at the link I sent you. Also there are some other examples I found that use the same method:

https://github.com/filipw/aspnetcore-parallel-pipelines/blob/master/WebApplication2/Startup.cs
https://github.com/WebApiContrib/WebAPIContrib.Core/blob/master/samples/WebApiContrib.Core.Samples/Startup.cs

Or is there another way to do this?

**Comment by sungam3r** [comment]
Well, then I think that you should call UseSerilog inside your Startup.Configure method and not in the "unused" one in Program.cs. In aforementioned link UseBranchWithServices creates WebHostBuilder.

**Comment by TheNetStriker** [comment]
@sungam3r The UseBranchWithServices method returns an IApplicationBuilder and not an IWebHostBuilder and there is no UseSerilog method for IApplicationBuilder.

As a workarround I'm now creating the logger in the controller this way:
Log.Logger.ForContext<ValuesController>();

**Comment by sungam3r** [comment]
I see. You are one step away from the required API: https://github.com/serilog/serilog-aspnetcore/blob/dev/src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs#L41 . In fact `builder` parameter  not used. `builder.ConfigureServices` stores delegate which will be called later to register your services in `IServiceCollection`, compare it with [this](
https://github.com/filipw/aspnetcore-parallel-pipelines/blob/22ff0894c5aff0825e1ce8e2f55f611dd60bfa32/WebApplication2/ApplicationBuilderExtensions.cs#L15). They do the same thing, they simply use an object internal to the `IWebHostBuilder`. `IWebHostBuilder` is a facade.

I can offer such a funny way to integrate them, the idea is very simple:

```c#
 internal class Adapter : IWebHostBuilder
    {
        private IServiceCollection _services;

        public Adapter(IServiceCollection services) => _services = services;

        public IWebHost Build()
        {
            throw new NotImplementedException();
        }

        public IWebHostBuilder ConfigureAppConfiguration(Action<WebHostBuilderContext, IConfigurationBuilder> configureDelegate)
        {
            throw new NotImplementedException();
        }

        public IWebHostBuilder ConfigureServices(Action<IServiceCollection> configureServices)
        {
            configureServices(_services);
            return this;
        }

        public IWebHostBuilder ConfigureServices(Action<WebHostBuilderContext, IServiceCollection> configureServices)
        {
            configureServices(null, _services); // <--------- WebHostBuilderContext is null 
            return this;
        }

        public string GetSetting(string key)
        {
            throw new NotImplementedException();
        }

        public IWebHostBuilder UseSetting(string key, string value)
        {
            throw new NotImplementedException();
        }
    }
```

```c#
 app.UseBranchWithServices("/" + site.Key,
            services =>
            {
                new Adapter(services).UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
            .ReadFrom.Configuration(Configuration/*hostingContext.Configuration*/) // <- hostingContext is null !
            .Enrich.FromLogContext());
                services
                    .AddMvc()
                    .AddXmlSerializerFormatters();
```

@nblumhardt Consider adding the new `UseSerilog` overload to invoke the callback method without having to have an instance of a `IWebHostBuilder`.  In our case, `IServicesCollection` will be quite enough.

**Comment by TheNetStriker** [comment]
@sungam3r Thanks, I've just tried this class but I'm still not getting any logs in the controller with this, but the ConfigureServices(Action<WebHostBuilderContext, IServiceCollection> configureServices) gets called twice. Any idea what could be missing?

**Comment by sungam3r** [comment]
It's hard for me to say having fragmentary pieces of code. Can you make a minimal example?

**Comment by TheNetStriker** [comment]
@sungam3r I just realized that I can simply change the "UseBranchWithServices" method an call UseSerilog there. I completely forgot that I simply implemented this method from the example I found. Now the logging works and I can also get a reference to the IDiagnosticContext.

Thanks again for your help!

**Comment by sungam3r** [comment]
> I can simply change the "UseBranchWithServices" method an call UseSerilog there. I completely forgot that I simply implemented this method from the example I found. 

Well, it simplifies a lot.
