### ISSUE TITLE
Have Serilog get automatically the configuration

### ISSUE THREAD

**Issue by simonech** [serilog/serilog-aspnetcore#155]
I just started using Serilog in a ASP.NET Core app, and I find it annoying that you cannot just use `.UseSerilog()` but one has to explicitly pass in the configuration 

```
    .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
        .ReadFrom.Configuration(hostingContext.Configuration)
        .Enrich.FromLogContext()
        .WriteTo.Console())
```

Is there some technical matter that prevents the `.UseSerilog` to just work? Why do I need to tell serilog to read the configuration? Cannot it be done automatically?

Also, I think that the "early initialization" example is going against the standard convention of ASP.NET Core. 
The `CreateDefaultBuilder` already creates the configuration object exactly as done in the sample. I don't see why you would need to do it "manually". I think as it is explained, it's misleading.

**Comment by sungam3r** [comment]
> Why do I need to tell serilog to read the configuration? Cannot it be done automatically?

Read from what? `IConfiguration` root? I think the main reason for this is that the serilog configuration can be built as you like. In this case, it is built from the `IConfiguration`, which is provided by a https://github.com/serilog/serilog-settings-configuration. Although this is the main method, but not the only one.

**Comment by simonech** [comment]
I mean, have an overload of the `.UseSerilog` that automatically calls the `.ReadFrom.Configuration(hostingContext.Configuration)` without having to specify it manually.

You can do the configuration any way you like, but the default behavior should be the one that all other logging providers (at least the ones bundled with ASP.NET Core) adopt.

And also, I'd swap the explanation in the README file by placing the "Inline initialization" first, since it's the easiest approach, and the one that requires less adding and removing lines of code from the ASP.NET templates. 
And then show the other more complex approach on how to create the logging in code vs via config file.

**Comment by sungam3r** [comment]
> I mean, have an overload of the .UseSerilog that automatically calls the .ReadFrom.Configuration(hostingContext.Configuration) without having to specify it manually.

I guessed and meant exactly that. This will require an external package dependency - https://www.nuget.org/packages/Serilog.Settings.Configuration. Why is one of the configuration providers placed above the others? This dependency is not useful, but only tightly binds the code.

**Comment by nblumhardt** [comment]
@simonech Howdy!

> Is there some technical matter that prevents the .UseSerilog to just work? Why do I need to tell serilog to read the configuration? Cannot it be done automatically?

No technical matter; it could be done. As @sungam3r points out, the current layering would need to be reconsidered, but there's no fundamental reason not to consider it.

Some complications will inevitably arise around how to customize configuration reading, ("how do I use a different section name?", "how do I turn it off?", perhaps) - and there's the question of bloating the package dependency graph for those who don't use `ReadFrom.Configuration()`, so it mostly needs thought and time/attention, but hasn't made it to the top of the list thus far.

> Also, I think that the "early initialization" example is going against the standard convention of ASP.NET Core.

Yes, this is deliberate - the default ASP.NET Core logging setup doesn't collect exceptions from host setup, which I think is a mistake, although opinions vary and we try to support both approaches equally well. The post at https://nblumhardt.com/2019/10/serilog-in-aspnetcore-3/ discusses some of this. Let's keep this particular ticket focused on your suggestion RE automatic reading of configuration so we don't end up off down that rabbit hole :-)

**Comment by phlashdev** [comment]
I can see the point here. I really like the ease of the .NET Core configuration system. It's very easy to have different settings for different environments with it, even more if you are not running your app in an container or still have very different environments. But like @nblumhardt adresses in his excellent blog post, the lack of logged exceptions at host startup is really not good in my opinion. 

I have to say I'm really struggling to get the logging setup easy and secure (and DRY, in regards to the early initialization with the self build config). Anything we can do here to improve things get's a thumbs up from me.

**Comment by nblumhardt** [comment]
I think we're unlikely to tackle this in the immediate future, so closing, but will come back and review it if there's a future opportunity to improve, here.
