### ISSUE TITLE
UseSerilog() with providing Serilog.Logger or without gives different results

### ISSUE THREAD

**Issue by ddrdoubled** [serilog/serilog-aspnetcore#156]
If i assign the Serilog.Logger and pass it over to UseSerilog Extension results in different logging behaviour than passing null, i would not expect that. Is this behaviour the desired one?

```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
               =>WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((builderContext, config) =>
                    {
                        Log.Logger = new LoggerConfiguration().ReadFrom.
                                                     Configuration(config.Build()).CreateLogger();
                    })
                .UseSerilog()
                .UseStartup<Startup>();
```
has a different behaviour then:
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
               =>WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((builderContext, config) =>
                    {
                        Log.Logger = new LoggerConfiguration().ReadFrom.
                                                     Configuration(config.Build()).CreateLogger();
                    })
                .UseSerilog(Log.Logger)
                .UseStartup<Startup>();
```

**Comment by skomis-mm** [comment]
Hi, @ddrdoubled . `Log.Logger` cannot be null and by default it is `SilentLogger`.
In the first snippet you pass null to `UseSerilog(..)`, in the second its `SilentLogger`, not the one you configured in `ConfigureAppConfiguration` because that delegate will be executed later.

**Comment by ddrdoubled** [comment]
Hi, thx understood, so that means if i pass null to `UseSerilog(..)` due to the lazy initialization of the `Log.Logger` the configuration provided in the delegate is used?

**Comment by skomis-mm** [comment]
@ddrdoubled right. `null` for `UseSerilog` means `use Log.Logger instance` when configuring LoggerFactory
