### ISSUE TITLE
How can I log the request and response body?

### ISSUE THREAD

**Issue by VictorioBerra** [serilog/serilog-aspnetcore#159]
Can this be done with `UseSerilogRequestLogging()`?

**Comment by nblumhardt** [comment]
Hi Victorio,

`UseSerilogRequestLogging()` doesn't do anything special to enable this; it's not a straightforward thing to do, and has some caveats (buffering and so on). Check out https://exceptionnotfound.net/using-middleware-to-log-requests-and-responses-in-asp-net-core/ for the kind of thing that's required (though I'd recommend avoiding this if at all possible).

Hope this helps,
Nick

**Comment by VictorioBerra** [comment]
Thanks for the quick reply.

When you say:
> (though I'd recommend avoiding this if at all possible)

Do you mean logging the request/response body entirely? What about for auditing purposes?

[Audit.NET.WebAPI](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.WebApi) seems to be able to do this, but unfortunately their sinks are very limited compared to Serilog. I would have to Sink them to a database table most likely.

**Comment by nblumhardt** [comment]
I think that's the essence of the _"if at all possible"_ :-) .. If you're stuck having to audit them, you might have to take the performance hit.

It's not that it's impossible, though - using something like the approach in the link should work, with a sprinkling of log statements in there.

I don't think we'd take on maintaining this kind of thing as part of Serilog - too many corner cases (e.g. giant request/response payloads, dropped connections, ...) to deal with.

**Comment by VictorioBerra** [comment]
Yeah, some of those edge cases crossed my mind. The client wants to be able to debug response issues by seeing the requests. I think maybe I could just log better manually and log out some of the more important requests.

**Comment by nblumhardt** [comment]
Sounds like a plan :-) - good luck with it!
