### ISSUE TITLE
Logging Broken in EF Core

### ISSUE THREAD

**Issue by danjohnso** [serilog/serilog-aspnetcore#160]
Something about UserSerilog() breaks EF Core 3 when used with Autofac Multitenant.  I had previously posted in 2.X about issues here which I got working in an odd way (https://github.com/serilog/serilog-aspnetcore/issues/45), but with 3.X not even that is working.  I know there are a lot of moving parts between EF, AspNetCore, Autofac and the multitenant setup, and I tried a 5-10 different options including manually setting the ILoggerFactory on the DbContextOptions, but nothing seemed to work.  Only way I got logs from EFCore back was by using this on the HostBuilder instead of UseSerilog:

 ```
Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.AddSerilog();
                })
                .UseServiceProviderFactory(new AutofacMultitenantServiceProviderFactory(MultitenantContainerSetup.ConfigureMultitenantContainer))
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                        .UseContentRoot(Directory.GetCurrentDirectory())
                        .UseIISIntegration()
                        .UseStartup<Startup>()
                        .UseConfiguration(Configuration);
                });
```

To be honest, I don't understand why that works.  I am not seeing any side effects right now, but I am wondering if there is a simple explanation for what is going on here.  Are there any subtle gotchas here I am going to hit by falling back to the 1.X method of using Serilog?

**Comment by mikes-gh** [comment]
I have the same issue
I have a service that uses `AddSerilog` on Generic host and that logs EFCore ok
I use `UseSerilog` on an aspnetcore 3 app and that doesn't log EF Core.

**Comment by sarensw** [comment]
@danjohnso I tried this but still don't see any sql texts logged out. Is there anything else that needs to be done? E.g. adjust the LoggerConfiguration, make some changes in the DbContext?

**Comment by tonymobster** [comment]
@sarensw you need to enable EF core logging with `.EnableSensitiveDataLogging(hosting.IsDevelopment())` or `.EnableSensitiveDataLogging()`.

**Comment by tonymobster** [comment]
I had the same issue, in my case with all `ILogger` logging not only EF core. The above workaround worked for me but in my case I also kept `.UseSerilog()` since I use `IDiagnosticContext`

**Comment by danieldieppa** [comment]
I did this and it is not working:
```C#
public static class Program
    {
        /// <summary>Gets the application configuration details.</summary>
        /// <value>The application configuration object.</value>
        public static IConfiguration Configuration { get; } = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production"}.json", optional: true)
            .AddEnvironmentVariables()
            .Build();

        /// <summary>Defines the entry point of the application.</summary>
        /// <param name="args">The arguments.</param>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        public static Task<int> Main(string[] args) => LogAndRunAsync(CreateHostBuilder(args).Build());


        /// <summary>
        /// Create logger and Run the applicataion.
        /// </summary>
        /// <param name="host">host.</param>
        /// <returns>A <see cref="Task{TResult}"/> representing the result of the asynchronous operation.</returns>
        /// /// <exception cref="ArgumentNullException">host null.</exception>
        public static async Task<int> LogAndRunAsync(IHost host)
        {
            if (host is null)
            {
                throw new ArgumentNullException(nameof(host));
            }

            Activity.DefaultIdFormat = ActivityIdFormat.W3C;
            Activity.ForceDefaultIdFormat = true;

            host.Services.GetRequiredService<IHostEnvironment>().ApplicationName = Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyProductAttribute>()?.Product;

            Log.Logger = CreateLogger(host);

            try
            {
                Log.Information("Starting web host");
                await host.RunAsync().ConfigureAwait(false);
                Log.Information("Stopped application");
                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        private static ILogger CreateLogger(IHost host)
        {
            var hostEnvironment = host.Services.GetRequiredService<IHostEnvironment>();
            return new LoggerConfiguration()
                 .Enrich.WithProperty("Application", hostEnvironment.ApplicationName)
                 .Enrich.WithProperty("Environment", hostEnvironment.EnvironmentName)
                 .Enrich.FromLogContext()
                 .WriteTo.Conditional(
                    x => !hostEnvironment.IsProduction(),
                    x => x.Console().WriteTo.Debug())
                 .WriteTo.Logger(x => x
                     .ReadFrom.Configuration(Configuration, "ErrorLog"))
                 .WriteTo.Logger(x => x
                     .ReadFrom.Configuration(Configuration, "DetailedLog"))
                 .WriteTo.Logger(x => x
                     .ReadFrom.Configuration(Configuration, "AppInsightsLogs"))
                 .CreateLogger();
        }

        /// <summary>Method to create the host builder.</summary>
        /// <param name="args">The arguments.</param>
        /// <returns>IHostBuilder object.</returns>
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```

**Comment by nblumhardt** [comment]
Closing as it's not clear what if anything we should do, here, but open to fixes if someone is able to pinpoint the issue.

**Comment by takato1314** [comment]
@nblumhardt after some deep debugging I found out that EntityFramework will check if the logger enabled for that logging level via the method below:
![image](https://user-images.githubusercontent.com/10910968/113511933-e5523300-9594-11eb-9137-525738085848.png)
![image](https://user-images.githubusercontent.com/10910968/113512009-45e17000-9595-11eb-8734-f49229e902bb.png)
![image](https://user-images.githubusercontent.com/10910968/113511914-cd7aaf00-9594-11eb-9123-49a823fd3a90.png)

I notice that the `levelSwitch` from the Serilog Logger is set to "Warning" here which causes the IsEnabled to be false, hence skipping the entire logging process.

Still what bothers me is that the private `logger` generated within the Serilog Logger constructor do respects the value of the Serilog Configuration, but the `_levelSwitch` will become `Warning` back after the Serilog constructor.
![image](https://user-images.githubusercontent.com/10910968/113512189-08c9ad80-9596-11eb-910c-0461f96a0295.png)
![image](https://user-images.githubusercontent.com/10910968/113512277-7b3a8d80-9596-11eb-93eb-228a6735b701.png)

I suspect that EntityFramework [internally uses](https://github.com/dotnet/efcore/blob/bbf39634cc5acbc7096c99e284c2efcd4afe0fa2/src/EFCore/DbContext.cs#L377) the `[ScopedLoggerFactory](https://github.com/dotnet/efcore/blob/809fe7a219c99fbe4f3576ef42bd084d4a6ce056/src/EFCore/Diagnostics/Internal/ScopedLoggerFactory.cs#L54)` which will [wrap around the actual `ILoggerFactory` used by the application](https://github.com/dotnet/efcore/blob/809fe7a219c99fbe4f3576ef42bd084d4a6ce056/src/EFCore/Diagnostics/Internal/ScopedLoggerFactory.cs#L32). It maybe that the `ScopedLoggerFactory` does some stuff that might've changed the `switchLevel`. 

Hope this helps.
