### ISSUE TITLE
.NET Core Workers injecting ILogger<T> need Serilog.AspNetCore

### ISSUE THREAD

**Issue by develorem** [serilog/serilog-aspnetcore#161]
.NET Core 3 now has support for applications called 'Workers' which are akin to windows services, Top Shelf, etc. It seems that Serilog has had a refactor to now work with the HostBuilder which is what Workers use, however it seems you still need to use the Serilog.AspNetCore package. Workers however are not ASP.Net. They are background processes. 

Mostly this is not a problem, except that Serilog.AspNetCore has a package dependency on Microsoft.AspNetCore.Hosting.Abstractions. This is also not a "problem" other dependency "cleanliness", deploying only what you need, etc. No doubt there is functionality in Serilog.AspNetCore that probably doesn't belong in Workers either. 

I know it must be hard to manage the whole ecosystem of Serilog packages and don't know enough to suggest a right solution, only that for a worker I shouldn't need to bring in anything related to AspNet. 

Also, my goal is to use the Microsoft abstractions as much as possible, which means always injecting ILogger<T> into my components.

Forgive me if I've missed the mark on how to do Serilog for Workers (ie if there is a way to do it without Serilog.AspnetCore and also lets you use ILogger<T>)

**Comment by sungam3r** [comment]
May be related to #127

**Comment by nblumhardt** [comment]
Hi! @develorem, I think you're looking for https://github.com/serilog/serilog-extensions-hosting - let us know if there are any drawbacks remaining, but as far as the current factoring goes I think that package has you covered. Cheers!
