### ISSUE TITLE
Serilog should honor asp.net core logging levels

### ISSUE THREAD

**Issue by bklooste** [serilog/serilog-aspnetcore#162]
Serilog is ignoring these and replacing it with their own , instead it should either use the Core logging convention or convert it to its own. 

Especially its import to have Microsoft logs set to warning and not debug .  ASP.NET Core web site logging is designed so different categories need different logging levels.

**Comment by nblumhardt** [comment]
Thanks for the suggestion; Serilog is already very well established, including outside of ASP.NET Core, so I think we will maintain consistency with existing Serilog usage, here.
