### ISSUE TITLE
Request Logging Should Log More by Default

### ISSUE THREAD

**Issue by RehanSaeed** [serilog/serilog-aspnetcore#163]
This issues is inspired by @andrewlock's [blog post](https://andrewlock.net/using-serilog-aspnetcore-in-asp-net-core-3-logging-the-selected-endpoint-name-with-serilog/). This is what is currently logged by the Serilog request logging middleware:

- RequestMethod (GET)
- RequestPath (/)
- StatusCode (200)
- Elapsed (224.5185)
- RequestId (0HLNPVG1HI42T:00000001)
- CorrelationId (1fbc88fa42db424fb32bc2d0994463f1)
- ConnectionId (0HLNPVG1HI42T)

These are properties that the default ASP.NET Core logger logs but are missing from the request logging middleware:

- Host (localhost:5001)
- Scheme (https)
- Protocol (HTTP/2)
- QueryString (test=true)
- EndpointName (/Index)
- HandlerName (OnGet/SerilogRequestLogging.Pages.IndexModel.OnGet)
- ActionId (1fbc88fa-42db-424f-b32b-c2d0994463f1)
- ActionName (/Index)
- RouteData ({page = "/Index"})
- ValidationState (True/False)
- ActionResult (PageResult)
- ContentType (text/html; charset=utf-8)

Some of these properties are more useful than others. I think it makes sense to add these properties at the very least:

- Host
- Protocol
- Scheme
- QueryString
- ContentType
- EndpointName

I have an open question about EndpointName. I'm not sure why ASP.NET Core doesn't log the RouteName instead. The EndpointName is actually the display name of the route which as far as I can see just adds a `/` at the beginning for reasons unknown to me.

```c#
var endpoint = httpContext.GetEndpoint();
 if (endpoint != null)
{
    diagnosticContext.Set("EndpointName", endpoint.DisplayName);

    var routeName = endpoint?.Metadata?.GetMetadata<IRouteNameMetadata>()?.RouteName;
    diagnosticContext.Set("RouteName", routeName);
}
```

**Comment by andrewlock** [comment]
> The EndpointName is actually the display name of the route which as far as I can see just adds a / at the beginning for reasons unknown to me.

That's only true for MVC actions AFAIK - for other endpoints, e.g. the HealthCheck endpoint or other custom endpoints it may have a display name that's different from the route name I think

**Comment by nblumhardt** [comment]
👍 - the initial set was chosen for being as close to "universal" as possible. Many apps serve only a single host, protocol, and scheme, so these are noise in those cases, though very useful in others. Query strings can sometimes, for some apps, be consistently large, so this was left out conservatively.

One pleasant way forwards might be to create  a `Flags`-style enum or similar representing the available properties, default it to what we have today, and expose it on the "options" object - any thoughts on that approach?

**Comment by RehanSaeed** [comment]
Seems sensible. An enum or builder pattern would do just fine.

**Comment by nblumhardt** [comment]
Shipped as [`EnrichDiagnosticContext`](https://github.com/serilog/serilog-aspnetcore/blob/dev/src/Serilog.AspNetCore/AspNetCore/RequestLoggingOptions.cs#L63)
