### ISSUE TITLE
Samples: SimpleWebSample didnt correspond to Readme.md

### ISSUE THREAD

**Issue by moskvitin** [serilog/serilog-aspnetcore#17]
Currently, the [sample application code](https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/SimpleWebSample/Program.cs) does not match the description in readme.md.
It's about using BuildWebHost.
Does it make sense to update the sample?

UPD:
Excuse me, but reason of it is copy of this [issue](https://github.com/serilog/serilog-aspnetcore/issues/10).

**Comment by nblumhardt** [comment]
Hi @moskvitin - thanks for getting in touch. I think that change would be fine if you're keen to PR an update. I'd like to try keeping the sample minimal, but the `BuildWebHost()` Entity Framework foot-gun is sure to snare some people 👍
