### ISSUE TITLE
Serilog.AspNetCore with UserSecrets entry in csproj cause Azure Functions to not load Startup extensions

### ISSUE THREAD

**Issue by saarivirtajCGI** [serilog/serilog-aspnetcore#181]
Came across this peculiar issue while upgrading my Functions and APIs to netcoreapp3.1 profile.

I'm truly puzzled as for what is happening here, but a single line in csproj causes the Startup code to not run. In fact, compilation should place a line in `bin/extensions.json` for the Function runtime to find it, but this does not happen, and therefore the code is never run. Simply having the Serilog.AspNetCore package present causes this, no code needs to be run. I suspect the Functions compilation does some discovery for Function extensions in referenced assemblies and in that process something goes haywire.

So this happens in netcoreapp3.1 / V3 Azure Functions.

The offending csproj:
```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <!-- Remove the line below to make Startup code to be run -->
    <UserSecretsId>8e82aff2-2dd0-4a3d-bd0e-9557f4cae65d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.5" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.3.0-dev-00152" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

The startup code is simple:

```
[assembly: FunctionsStartup(typeof(Startup))]

namespace FunctionApp3
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            // This won't be run.
        }
    }
}
```

Removing the UserSecretsId from the csproj suddenly makes it work. It's amazing.

I've attached the simplest possible example that reproduces this behavior. Just run the app in Visual Studio 2019 and hit a breakpoint to the startup code. I'm truly curious to find out what causes this.
[FunctionApp3.zip](https://github.com/serilog/serilog-aspnetcore/files/4323781/FunctionApp3.zip)

**Comment by nblumhardt** [comment]
Thanks for getting in touch. Unfortunately we can't dig in right now, but if you narrow down the issue to something Serilog is doing (rather than an esoteric tooling problem :-) ) please drop us a line, happy to fix anything that might cause this :+1:
