### ISSUE TITLE
How to configure outside of Main and CreateWebHostBuilder?

### ISSUE THREAD

**Issue by douglasg14b** [serilog/serilog-aspnetcore#186]
I need to configure serilog to add a sink during `Startup`, largely because I require injected dependencies from IServiceProvider to retrieve encrypted configurations.

How should this be configured to add a sink outside of `Program`?

Note that I still want to capture logs during webhost build, but after that I need to configure the logging in another fashion.

**Comment by skomis-mm** [comment]
Hi @douglasg14b ,

MEL supports adding providers dynamically via `ILoggerFactory` and `Serilog` support `ILoggerProvider`s, so check if it works for you
```csharp
public class Program
{
    static readonly LoggerProviderCollection Providers = new LoggerProviderCollection();

    public static int Main(string[] args)
    {
        Log.Logger = new LoggerConfiguration()
            .WriteTo.Console()
            .WriteTo.Providers(Providers)
            .CreateLogger();

        CreateHostBuilder(args).Build().Run();

        try
        {
            Log.Information("Starting web host");
            CreateHostBuilder(args).Build().Run();
            return 0;
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Host terminated unexpectedly");
            return 1;
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureLogging(lb => lb.ClearProviders())
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            })
            .UseSerilog(providers: Providers);
}
```
Startup.cs
```csharp
// inject any service here
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddSerilog(new LoggerConfiguration()
        .WriteTo.File("log.txt")
        .CreateLogger(),
        dispose: true);

     // ...
}
```

**Comment by bjorn-ali-goransson** [comment]
But with this pattern, won't the ConfigureWebHostDefaults create a Configuration again ie twice in the application? Isn't that confusing and/or bad?

**Comment by skomis-mm** [comment]
Hi @bjorn-ali-goransson ,

the configuration is not created twice. The `Configuration` first configured in the global `Host.CreateDefaultBuilder(..)`. You can, however, add `webBuilder.ConfigureAppConfiguration(...)` inside `ConfigureWebHostDefaults` but AFAIK it just will add another layer on top of the global config.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1#app-configuration

P.S. also recommend to check this out [serilog-reload](https://github.com/nblumhardt/serilog-reload) if you need a fully mutable logger.
