### ISSUE TITLE
Unit Testing with Serilog.AspNetCore.RequestLoggingMiddleware

### ISSUE THREAD

**Issue by naymore** [serilog/serilog-aspnetcore#189]
Can anyone please advice how this can be done (apart from disabling the middleware for a specific environment)?

**Description**
Unit test fails.

```
Message: 
    System.InvalidOperationException : Unable to resolve service for type 'Serilog.Extensions.Hosting.DiagnosticContext' while attempting to activate 'Serilog.AspNetCore.RequestLoggingMiddleware'.
  Stack Trace: 
    ConstructorMatcher.CreateInstance(IServiceProvider provider)
    ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
    <>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
    ApplicationBuilder.Build()
    WebHost.BuildApplication()
    WebHost.StartAsync(CancellationToken cancellationToken)
    TestServer.ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
    TestServer.ctor(IWebHostBuilder builder)
    FirmwareUpdateControllerTests.GetAsync_InvalidScope_ReturnsUnauthorizedResult() line 22
    --- End of stack trace from previous location where exception was thrown ---
```

```csharp
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Serilog;
using System.Net;
using System.Threading.Tasks;
using Tts.IoT.FirmwareUpdate;
using Xunit;

namespace myNamespace
{
    [Trait("IntegrationTests", "MySampleController")]
    public class MySampleControllerTests
    {
        private const string a= "10115143";
        private const string b= "3";

        [Fact]
        public async Task GetAsync_InvalidScope_ReturnsUnauthorizedResult()
        {
            // Arrange
            Log.Logger = new LoggerConfiguration().WriteTo.Console().CreateLogger();
            TestServer testServer = new TestServer(new WebHostBuilder().UseStartup<Startup>());
            System.Net.Http.HttpClient client = testServer.CreateClient();
            string url = $"route/to/controller/{a}/{b}";

            HttpStatusCode expectedHttpStatusCode = HttpStatusCode.Unauthorized;

            // Act
            System.Net.Http.HttpResponseMessage response = await client.GetAsync(url);

            // Assert
            Assert.Equal(expectedHttpStatusCode, response.StatusCode);

            // Clean up
            testServer.Dispose();
            client.Dispose();
            response.Dispose();
        }
    }
}
```

**Reproduction**
See above.

**Expected behavior**
Working unit tests.

**Relevant package, tooling and runtime versions**
v3.2.0

**Comment by naymore** [comment]
Nevermind. Forgot about `.UseSerilog()` for the TestServer :-/

**Comment by kinfinity** [comment]
Please can i know how you resolved this. i'm getting a similar error while trying to do some Integration tests

**Comment by kjones-lan** [comment]
> Please can i know how you resolved this. i'm getting a similar error while trying to do some Integration tests

Did you ever figure this out? I'm having the exact same problem with Integration Testing.

**Comment by tomer-cohen** [comment]
Getting the same exception while trying to run integration test, anyone has a solution?

**Comment by Adin-Sijamija** [comment]
I had this issue come up when doing integration testing. I had to set up serilog inside the program file the classic way (.UseSerilog()) add " app.UseSerilogRequestLogging();" on the start of the configure function and then finally add serilog once again to the Testserver instance for whatever reason, even thou my test server was using the already existing startup file. I think this is some dependency bug when it comes to transferring the serilog to a new namespace. 

Anyway code is bellow. Hope it helps you out @kjones-lan.
Systmes used: core 3.1, Owin(NancyFx), Xunit


```
        private readonly TestServer _server;
        private readonly HttpClient _client;

        public EventsModule_Int_Tester()
        {
            //Server setup
            _server = new TestServer(new WebHostBuilder()
          .UseStartup<Startup>().UseSerilog());
            _server.AllowSynchronousIO = true;//Needs to be overriden in net core 3.1
           _client= _server.CreateClient();
            
        }

```

**Comment by MoghiTech** [comment]
> Nevermind. Forgot about `.UseSerilog()` for the TestServer :-/

Hi Dude ✋🏻 
I Added it and Write This Code :

`builder.Host.UseSerilog(logger);`

After of This Single Line My Application is **Builded Not Runned** !
and Just Show me in Command Prompt of My VS Code : 
Building...

I Had This Problem For Serveral Times and Wrote Before One Post in Stack :
https://stackoverflow.com/questions/76333729/it-was-built-but-not-runned-because-of-serilog
