### ISSUE TITLE
EnrichDiagnosticContext logging to console

### ISSUE THREAD

**Issue by malnosna** [serilog/serilog-aspnetcore#196]
I tried to add the sample code to log EnrichDiagnosticContext to console:

`
app.UseSerilogRequestLogging(options =>
{
    // Customize the message template
    options.MessageTemplate = "Handled {RequestPath}";
    
    // Emit debug-level events instead of the defaults
    options.GetLevel = (httpContext, elapsed, ex) => LogEventLevel.Debug;
    
    // Attach additional properties to the request completion event
    options.EnrichDiagnosticContext = (diagnosticContext, httpContext) =>
    {
        diagnosticContext.Set("RequestHost", httpContext.Request.Host.Value);
        diagnosticContext.Set("RequestScheme", httpContext.Request.Scheme);
    };
});
`

But I didn't see anything logged to console. Is it only viewable to Seq?

**Comment by nblumhardt** [comment]
You'll need to include `{Properties}` in the console sink's `outputTemplate` in order for the full set of enriched properties to be shown (it can be a lot of data, so it doesn't do this by default).

**Comment by malnosna** [comment]
Thanks, that's all I needed!
