### ISSUE TITLE
getting Dynamic method when writing an ObjectResult where status code = 500

### ISSUE THREAD

**Issue by stevencovhlth** [serilog/serilog-aspnetcore#198]
**Description**
Our application captures all exceptions in some middleware and converts those exceptions into ObjectResults like
```
new ObjectResult(thrownException) {StatusCode = (int) HttpStatusCode.InternalServerError}
```
Instead of the actual `thrownException` I get 
```
System.InvalidOperationException: The requested operation is invalid for DynamicMethod.
   at System.Reflection.Emit.DynamicMethod.RTDynamicMethod.get_MethodHandle()
   at System.Text.Json.JsonPropertyInfoCommon`4.GetValueAsObject(Object obj)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Vortext.RCM.Api.CompositionRoot.QueryHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\dev\vortext-main-new\vortext-web\Vortext.RCM.Api\CompositionRoot\QueryHandlerMiddleware.cs:line 62
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)

```

If I change the result to only have the exception message, then only the 500 is logged, not the message passed.  For example
```
new ObjectResult(thrownException.Message) {StatusCode = (int) HttpStatusCode.InternalServerError}
```
Logs
```
[16:23:06 ERR] HTTP GET /queries/getsavedsearches responded 500 in 6010.8575 ms {"SourceContext":"Serilog.AspNetCore.RequestLoggingMiddleware" <= no message in the log
```

**Reproduction**
Here is my configuration
```
    public class Program
    {
        private const string OUTPUT_TEMPLATE = "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}";

        public static void Main(string[] args)
        {
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseSerilog((context, configuration) => ConfigureLogging(context, configuration, OUTPUT_TEMPLATE))
                .Build()
                .Run();
        }


        internal static void ConfigureLogging(HostBuilderContext context, LoggerConfiguration loggerConfiguration,
            string outputTemplate)
        {
            var mailSettings = new EmailSettings();
            context.Configuration.GetSection("EmailSettings").Bind(mailSettings);

            var appDataPath = Path.Combine(context.HostingEnvironment.ContentRootPath, "App_Data");
            AppDomain.CurrentDomain.SetData("DataDirectory", appDataPath);
            var environment =
                context.Configuration.GetSection("AppSettings")["serilog:enrich:with-property:Environment"];
            if (string.IsNullOrWhiteSpace(environment)) environment = "DEV";

            loggerConfiguration
                .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
                .Enrich.FromLogContext()
                .Enrich.WithProperty("Application", "MyApp")
                .Enrich.WithProperty("Environment", environment)
                .Enrich.WithThreadId()
                .WriteTo.RollingFile(appDataPath + "\\logs\\log-{Date}.txt", outputTemplate: outputTemplate,
                    restrictedToMinimumLevel: LogEventLevel.Information)
                .WriteTo.Email(new EmailConnectionInfo
                 {
                     MailServer = mailSettings.Host,
                     EnableSsl = false,
                     Port = mailSettings.Port,
                     FromEmail = mailSettings.From,
                     ToEmail = string.Join(",", mailSettings.To),
                     EmailSubject = $"Error in {Environment.MachineName} Vortext.RCM.Api",
                     IsBodyHtml = false,
                     ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true,
                     NetworkCredentials = new NetworkCredential(mailSettings.UserName, mailSettings.Password)
                 }, restrictedToMinimumLevel: LogEventLevel.Error);

        }
    }
```
**Expected behavior**
I expect the correct exception to be logged or if using Exception as the value in the ObjecttResult is a problem then using a simple object as the Value of the ObjectResult should be written when the result is a 500.

**Relevant package, tooling and runtime versions**
What Serilog version are you using, on what platform?
I'm using Serilog latest and .NET CORE 3.1.  Here are the version numbers and packages
Serilog Version="2.9.0" />
Serilog.AspNetCore Version="3.2.0" />
Serilog.Enrichers.Thread Version="3.1.0" />
Serilog.Sinks.Console Version="3.1.1" />
Serilog.Sinks.Email Version="2.3.0" />
Serilog.Sinks.File Version="4.1.0" />
Serilog.Sinks.RollingFile Version="3.3.0" />

**Comment by nblumhardt** [comment]
Hi Stephen, thanks for your message!

This doesn't seem like a Serilog issue - Serilog seems to be logging an exception that's been raised way down the stack in some other middleware. I would guess that using an exception in `ObjectResult` will lead to odd serialization issues (JSON-serializing `Exception` subclasses is fraught with dangers).

If you take Serilog out of the picture (no `UseSerilogRequestLogging()`) does everything behave as you expect?

**Comment by stevencovhlth** [comment]
@nblumhardt I commented out `app.UseSerilogRequestLogging();` and the same weird exception gets logged so I guess this is not a Serilog error after all.

I will close this but can you recommend an approach that will let me log the error and get only one notice?  In other words, I can call Log.Error conveniently in our middleware, but I still need to return 500.  However if I do I will get a secondary notice from the framework logging right?

Maybe I just remove `app.UseSerilogRequestLogging();` and just use Serilog for my application logging?

**Comment by stevencovhlth** [comment]
@nblumhardt I just verified that if I remove `app.UseSerilogRequestLogging();` and log by myself, I get the log entries I want.  I guess if I want to see what the framework is logging I can just configure the built in logging?

**Comment by nblumhardt** [comment]
Hi! Sorry about the long delay; I'm guessing you've figured out something suitable for now - if not, and it seems there's a Serilog bug (rather than just a trade-off to make between catching/logging the error, and letting the framework handle it), let me know, can dig deeper :+1:
