### ISSUE TITLE
EventId enrichment

### ISSUE THREAD

**Issue by Stepnicka** [serilog/serilog-aspnetcore#200]
Hi! 👋

I just wanted to know if we can enrich our logs with [EventId](https://docs.microsoft.com/en-gb/dotnet/api/microsoft.extensions.logging.eventid?view=dotnet-plat-ext-3.1) struct that is passed to [Iloger<>](https://docs.microsoft.com/cs-cz/dotnet/api/microsoft.extensions.logging.ilogger?view=dotnet-plat-ext-3.1) calls.

Like this: 
` logger.LogInformation(_events.TestEventId,"Logging test."); `

Is the struct accessible somehow through the Serilog.Events.LogEvent class?

**Comment by nblumhardt** [comment]
Hi! Yes, it should already be there in `Properties` as a property called `EventId` - is it missing in your app?

**Comment by nblumhardt** [comment]
Closing, but please follow up if there's a bug we've overlooked :+1:
