### ISSUE TITLE
Azure Functions Startup Failure on 3.4.0

### ISSUE THREAD

**Issue by tottes200** [serilog/serilog-aspnetcore#206]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other related package, please try to track down the correct repository for that package and create the report there: this tracker is for the  **Serilog.AspNetCore** package only.

**Description**
Upgrading to 3.4.0 causing the startup class in Azure Functions to not be hit.

**Reproduction**
`public Startup()
        {
            BulkOperationManager.ForceSelectOutput = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls13 | SecurityProtocolType.Tls12 |
                                                   SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
        }

        public override async void Configure(IFunctionsHostBuilder builder)
        {
            // use appsettings.json
            var currentDirectory = "/home/site/wwwroot";
            var isLocal = string.IsNullOrEmpty(Environment.GetEnvironmentVariable("WEBSITE_INSTANCE_ID"));
            if (isLocal) currentDirectory = Environment.CurrentDirectory;

            var config = new ConfigurationBuilder()
                .SetBasePath(currentDirectory)
                .AddJsonFile("appsettings.json")
                .Build();
            var keyVault = new KeyVaultCache(config);
            Log.Logger = SerilogSinkOptions.CreateMsSqlLogger().Result;

            // await KeyVaultCache.Initialize();

            ConfigureServices(builder.Services).BuildServiceProvider(true);
        }

        public IServiceCollection ConfigureServices(IServiceCollection services)
        {
            services.Configure<KestrelServerOptions>(options => { options.AllowSynchronousIO = true; });
            services.AddLogging(lb => lb.AddSerilog(dispose: true));
            return services;
        }`

**Expected behavior**
The startup class should always be hit.

**Relevant package, tooling and runtime versions**
Currently 3.2.0, upgrading to 3.4.0 causing this failure.

**Additional context**

**Comment by nblumhardt** [comment]
Thanks for the note; is there any diagnostic output for the function, or any other clue as to why this might fail?

**Comment by tottes200** [comment]
Not that I am aware of. I had simply updated all my packages and noticed that I started getting failures. After reverting and going through packages one at a time I found it failing only after updating to 3.4.0. There are no error messages or anything so I can't see a whole lot more than it missing the breakpoint.

**Comment by nblumhardt** [comment]
Hi @tottes200 - did you find any further clues? Without some kind of error message/diagnostic here, there's not a lot we can do, so I'll close this now, but would be happy to reopen if you obtain any additional data. Cheers!

**Comment by tottes200** [comment]
I haven't, but even to this day if I upgrade to that version it immediately stops the code from hitting startup. Again there are no errors codes, it just simply doesn't hit startup. I wish I could help more.
