### ISSUE TITLE
Asp and Entity Framework logs stop appearing after a while (3.1)

### ISSUE THREAD

**Issue by lesscodetxm** [serilog/serilog-aspnetcore#208]
We have a weird issue on a heavily trafficked API in production where at some point during the day Asp request logging and EF query logging just stops. We have other loggers (including a custom trace middleware) that continue to produce logs for all requests, so serilog in general seems fine.

Has anyone else seen this?
How would we begin to diagnose this?

**Comment by gaoshan0621** [comment]
I might meet the same problem:

I was using:
```
public static IHostBuilder UseSerilog(this IHostBuilder builder, Action<HostBuilderContext, LoggerConfiguration> configureLogger, bool preserveStaticLogger = false, bool writeToProviders = false);
```
to config serilog, like this:
```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
                .UseSerilog((hostBuilderContext, loggerConfiguration) => {
                    loggerConfiguration.ReadFrom.Configuration(hostBuilderContext.Configuration);
                });
```
any `Iogger<Type>` get from dependence injection doesn't work, even serilog request logging stop working.

I look the two useSerilog extension, look like this problem should relate to how `SerilogLoggerFactory` are created and how `Log.Logger` are assigned.

Then I found a workaround: I wrote my own useSerilog() extension like this:
```
        public static IHostBuilder UseSerilog(this IHostBuilder builder,
                Action<HostBuilderContext, LoggerConfiguration> configureLogger) {
            if (builder == null) {
                throw new ArgumentNullException(nameof(builder));
            }
            if (configureLogger == null) {
                throw new ArgumentNullException(nameof(configureLogger));
            }

            var ret = builder.UseSerilog();

            builder.ConfigureServices((context, collection) => {
                var loggerConfiguration = new LoggerConfiguration();
                configureLogger(context, loggerConfiguration);
                var logger = loggerConfiguration.CreateLogger();
                Log.Logger = logger;
            });

            return ret;
        }

```
Looks like `Log.Logger` should be assigned after `SerilogLoggerFactory` is created.

**Comment by gaoshan0621** [comment]
Hmm, are you sure you are using this package.

It looks like in asp.net core 3.1, Program.Main actually use IHostBuilder, so the right package to use is actually [Serilog-logging-host](https://github.com/serilog/serilog-extensions-hosting)

But I did get some problems recently, which give you some hints:

I was using:
```
public static IHostBuilder UseSerilog(this IHostBuilder builder, Action<HostBuilderContext, LoggerConfiguration> configureLogger, bool preserveStaticLogger = false, bool writeToProviders = false);
```
to config serilog, like this:
```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>())
                .UseSerilog((hostBuilderContext, loggerConfiguration) => {
                    loggerConfiguration.ReadFrom.Configuration(hostBuilderContext.Configuration);
                });
```
any `Iogger<Type>` get from dependence injection doesn't work, even serilog request logging stop working.

I look the two useSerilog extension, look like this problem should relate to how `SerilogLoggerFactory` are created and how `Log.Logger` are assigned.

Then I found a workaround: I wrote my own useSerilog() extension like this:
```
        public static IHostBuilder UseSerilog(this IHostBuilder builder,
                Action<HostBuilderContext, LoggerConfiguration> configureLogger) {
            if (builder == null) {
                throw new ArgumentNullException(nameof(builder));
            }
            if (configureLogger == null) {
                throw new ArgumentNullException(nameof(configureLogger));
            }

            var ret = builder.UseSerilog();

            builder.ConfigureServices((context, collection) => {
                var loggerConfiguration = new LoggerConfiguration();
                configureLogger(context, loggerConfiguration);
                var logger = loggerConfiguration.CreateLogger();
                Log.Logger = logger;
            });

            return ret;
        }

```
Looks like `Log.Logger` should be assigned after `SerilogLoggerFactory` is created.

**Comment by gaoshan0621** [comment]
One more comment: Actually asp.net 3.1 use `IHostBuilder` instead of `IWebHostBuilder`, so the really UseSerilog() extensions is actually defined in serilog-logging-hosting.

**Comment by lesscodetxm** [comment]
@gaoshan0621 In your case case you were _never_ seeing logging though, right?
In our case the app starts out logging fine, but then stops logging during the day, so I think our startup config is fine.

**Comment by nblumhardt** [comment]
@lesscodetxm have you tried enabling Serilog's `SelfLog`? May be a good place to start. I think this is unlikely to be Serilog itself - but if you find any clues to the contrary please let us know. I'll close this here as I don't think it's something we can act on directly without more data. Thanks again!
