### ISSUE TITLE
Access underlying Serilog logger

### ISSUE THREAD

**Issue by hardcodet** [serilog/serilog-aspnetcore#21]
Given that ASP.net's ILogger<T> has very limited functionality, it would be awesome if we could access the underlying Serilog logger at runtime. Globally configured enrichers are helpful, but they are useless if I want to add custom context information (e.g. a user ID I resolved) in every log message which I then could access in my log sink. Would that be feasible? Or should I just roll out my custom wrapper for Serilog's ILogger through dependency injection?

**Comment by nblumhardt** [comment]
Hi Philipp - there are a couple of options; if you're using Autofac for DI, you can configure _AutofacSerilogIntegration_ to get Serilog loggers injected; if not, you can always just assign `Log.Logger` when starting up and use `Log.ForContext<X>().Information(...)` wherever you need to. Does either approach work for you?

**Comment by hardcodet** [comment]
I'll go for the DI route then. Thanks Nicholas!
