### ISSUE TITLE
Can't seem to add any sinks with serilog.aspnetcore 

### ISSUE THREAD

**Issue by FooBartn** [serilog/serilog-aspnetcore#22]
Whenever I try to install any serilog sink/extension, NuGet wants to uninstall serilog.aspnetcore and extensions.logging. 

![image](https://user-images.githubusercontent.com/8498617/34580640-4d442c64-f153-11e7-9aad-f5b5ed2cb644.png)

Is there something I am missing?

This is an asp.net core 2.0 project

**Comment by FooBartn** [comment]
Strangely enough.. I unloaded VS2017 and restarted it. I noticed that when I was clicking install it was never showing the package as installed. Now it's working just fine. Starting to feel like I should be used to VS2017 quirks by now, hah. Apologies for any disturbance I may have caused. 

Take care!

**Comment by nblumhardt** [comment]
Thanks Joshua, glad you found the cause :-) 👍
