### ISSUE TITLE
Do we want to use this over the pre-release of Serilog.Extensions.Logging?

### ISSUE THREAD

**Issue by VictorioBerra** [serilog/serilog-aspnetcore#23]
We are building a core app and noticed some people online saying we should install the pre release of Serilog.Extensions.Logging. A quick google gave us serilog-aspnetcore. Which should we be using?

**Comment by nblumhardt** [comment]
Definitely _Serilog.AspNetCore_, if you're targeting .NET Core 2.

Best regards,
Nick
