### ISSUE TITLE
Serilog with dotnet watch breaks dotnet watch's autoreload feature

### ISSUE THREAD

**Issue by scottsauber** [serilog/serilog-aspnetcore#233]
**Description**
Running `dotnet watch run` on a Razor Pages/MVC app without Serilog allows the app to auto-open in the browser on first load.  Subsequent changes causes the app to rebuild and auto refresh the page.

**Reproduction**
This app has the repro: https://github.com/scottsauber/serilog-dotnet-watch-repo
There are two commits.  [Initial commit](https://github.com/scottsauber/serilog-dotnet-watch-repo/commit/7b04e50c6dc0a382e10efaaef78124f045105362) works when you do `dotnet watch run` but [add serilog](https://github.com/scottsauber/serilog-dotnet-watch-repo/commit/e5d9dcd77ad54f6bcb75b0f513197da21b39bdae) does not.  `dotnet watch run` does not launch a browser or autorefresh the page.

**Expected behavior**
When adding Serilog, `dotnet watch run` both launches the browser AND autorefreshes on changes

**Relevant package, tooling and runtime versions**
3.4.0 of Serilog.AspNetCore on both Windows and Mac

**Additional context**
I wonder if `dotnet watch` is looking for a very particular log message that it can't find with Serilog now.

**Comment by scottsauber** [comment]
Found the reason is because by default Serilog puts logs on one line and `Microsoft.Extensions.Logging` puts them on multiple lines and this regex the `^` expects a new line.  https://github.com/dotnet/sdk/blob/f91adc19fb8beab5bc2e09c4d589e1fec5e557d6/src/BuiltInTools/dotnet-watch/LaunchBrowserFilter.cs#L18

**Comment by nblumhardt** [comment]
Thanks, yes, unfortunately this is an issue with the regex; I think there's already an issue upstream in one of the dotnet repos tracking this.

**Comment by scottsauber** [comment]
Yep, I opened a [PR](https://github.com/dotnet/sdk/pull/15865) for it already.

In the meantime (if anyone comes across this), I worked around it by customizing the message template to put the message on a new line:
```csharp
Log.Logger = new LoggerConfiguration()
// other config
.WriteTo.Console(new MessageTemplateTextFormatter("{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {NewLine} {Message:lj}{NewLine}{Exception}"))
.CreateLogger()
```

**Comment by nblumhardt** [comment]
Awesome, thanks Scott!
