### ISSUE TITLE
[Docs] Improve section "Two-stage initialization"

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog-aspnetcore#237]
I read the [blog](https://nblumhardt.com/2020/10/bootstrap-logger/) and [docs](https://github.com/serilog/serilog-aspnetcore#two-stage-initialization) regarding "Two-stage initialization". My impression was that the bootstrap logger can be configured via `appsettings.json` or whatever.

The blog says:
> There’s a catch, though: in this case, important parts of the hosting infrastructure like appSettings.json configuration, and services provided by ASP.NET, won’t be available when logging is initialized.

I assumed this new approach tackles that, but that isn't shown in the [docs](https://github.com/serilog/serilog-aspnetcore#two-stage-initialization) and should be made explicit (it wasn't clear and led to confusion).

The docs look like this:
````cs
Log.Logger = new LoggerConfiguration()
  .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
  .Enrich.FromLogContext()
  .WriteTo.Console()
  .CreateBootstrapLogger();
````

They should look like this:
````cs
var config = GetConfig();                                          // <--- ADD THIS

Log.Logger = new LoggerConfiguration()
  .ReadFrom.Configuration(config, "Serilog")                       // <--- ADD THIS
  .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
  .Enrich.FromLogContext()
  .WriteTo.Console()
  .CreateBootstrapLogger();
````

**Comment by nblumhardt** [comment]
Hi! The example does show this, in the "two stage initialization" section, as:

```csharp
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog((context, services, configuration) => configuration
                    .ReadFrom.Configuration(context.Configuration) <-- here it is
                    .ReadFrom.Services(services)
                    .Enrich.FromLogContext()
                    .WriteTo.Console())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

Or am I misunderstanding? Thanks!

**Comment by lonix1** [comment]
Maybe I'm the one misunderstanding... :)

The code you show above is the part that loads the "normal" logger.

The first code block I show above (copied directly from the docs) is to create the "bootstrap" logger. That doesn't show that one needs to load the config.

**Comment by nblumhardt** [comment]
Thanks for the clarification. The bootstrap logger is intended to be created before config is available - it's possible to do something along the lines you suggest, but most of the time, loading from config is expected to be done in stage two. Hope this helps!

**Comment by lonix1** [comment]
Thanks for the confirmation.

Yes that's exactly what I do - I load the bootstrap logger with config, and later on, the normal logger with config.

I want those bootstrap logs to go to the same sinks as everything else, so I need to tell it to do that (by loading the same config as for the normal logger).

Hope this helps someone else.

**Comment by nblumhardt** [comment]
Thanks for the reply! 👍 

In that case, do you need two-stage initialization at all? You could just use `CreateLogger()` at start-up, and call it done?
