### ISSUE TITLE
Updating Serilog.AspNetCore package to 4.0, application cannot load Serilog.Sinks.Debug

### ISSUE THREAD

**Issue by mcattle** [serilog/serilog-aspnetcore#238]
**Description**
When updating the Serilog.AspNetCore Nuget package in a .Net 5.0 Windows Service from 3.4.0 to 4.0.0 and publishing the service in Release mode, the service fails to start because it cannot load Serilog.Sinks.Debug.  The service is published with PublishSingleFile=True.

- Explicitly adding the Serilog.Sinks.Debug 2.0.0 Nuget package to the project and publishing the application did not resolve this issue.
- Reverting the Serilog.AspNetCore package to 3.4.0 resolved the issue as a temporary workaround, but we like to keep our Nuget packages up to date.

**Relevant package, tooling and runtime versions**
- Serilog.AspNetCore 3.4.0, 4.0.0
- Serilog.Sinks.Debug 2.0.0
- Windows Server
- Visual Studio 2019 16.8.6, 16.9.1
- dotnet 5.0.103

**Comment by Numpsy** [comment]
Does Serilog.AspNetCore 3.4.0 together with Serilog.Sinks.Debug 2.0.0 (as opposed to version 1.0.1 of the debug sink that the aspnetcore package uses by default) work?

**Comment by nblumhardt** [comment]
Closing as stale, this doesn't seem to have appeared in the past few years.
