### ISSUE TITLE
Upgrade 4.0.0 -> 4.1.0 breaks on runtime:5.0.0-buster-slim docker image

### ISSUE THREAD

**Issue by Chrisw32** [serilog/serilog-aspnetcore#244]
**Description**
After upgrading to 4.1.0 of the Serilog.AspNetCore library the application (.netCore 5 Console App) fails to launch in the visual studio debugger with the following error:

> It was not possible to find any compatible framework version
> The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
>   - No frameworks were found.
> 
> You can resolve the problem by installing the specified framework and/or SDK.
> 
> The specified framework can be found at:
>   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=x64&rid=debian.10-x64
> The program 'dotnet' has exited with code 150 (0x96).

**Reproduction**
Open VS2019
Create a new .netCore 5 Console app project (if this is unavailable you will need to enable preview features, Tools > Options > Environment > Preview Features and tick the option, Show all .NET Core templates in the New project dialog (requires restart))
Right click the project, Add > Docker Support (Linux)
Tools > NuGet Package Manager > Manage NuGet Packages for Solution
Install "Serilog.AspNetCore" v4.1.0

Debugging the application with the "Docker" profile will now be broken.

Reverting the NuGet package to v 4.0.0 fixes it

**Expected behavior**
The application to launch without error on the runtime only .net core 5 docker images

**Relevant package, tooling and runtime versions**
Docker Image: mcr.microsoft.com/dotnet/runtime:5.0-buster-slim 
Target Framework: .NET 5.0
Framework Dependency: Microsoft.NETCore.App
NuGet Package: Serilog.AspNetCore 4.1.0

**Additional context**
The issue can be worked around by referencing full .net core docker images, both of the below images work with version 4.1.0
mcr.microsoft.com/dotnet/sdk:5.0-buster-slim 
mcr.microsoft.com/dotnet/aspnet:5.0

**Comment by rodrijp** [comment]
We have the same issue, withthe default image mcr.microsoft.com/dotnet/runtime:5.0

**Comment by Numpsy** [comment]
>Create a new .netCore 5 Console app project

Is this using Serilog.AspNetCore in a non-ASP.NetCore application?

**Comment by Chrisw32** [comment]
Ah you're correct, this particular project was a lightweight console app, which is referencing "mcr.microsoft.com/dotnet/runtime:5.0.5-buster-slim" instead of "mcr.microsoft.com/dotnet/aspnet:5.0.0-buster-slim", oddly this "worked" prior to Serilog 4.1,  4.1 added the specific framework dependency "<FrameworkReference Include="Microsoft.AspNetCore.App" />" which it seems now the dependencies are correctly enforced and as I'm using the wrong version for .net console apps has now produced an error.

I've confirmed this by trying to repo it in a standard AspNet WebApi project and Serilog 4.1 works fine with the default "mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim" image.

I'll update the version of serilog i use to "Serilog.Extensions.Hosting" as i believe this is the correct one when using IHostBuilder in console apps and close the issue as this is working as intended now with 4.1.

Thanks for pointing me in the right direction.
