### ISSUE TITLE
GetRequiredService throw "The logger is already frozen"

### ISSUE THREAD

**Issue by benlinx1018** [serilog/serilog-aspnetcore#251]
**Description**
in the project using `Swashbuckle.AspNetCore`, I try to use `CreateBootstrapLogger` to build a logger for Web API, but it cannot startup and throw the exception `The logger is already frozen`. 

**Reproduction**
![image](https://user-images.githubusercontent.com/5648078/120431299-e217cf80-c3aa-11eb-9259-08a5ca97eea4.png)

![image](https://user-images.githubusercontent.com/5648078/120431180-b98fd580-c3aa-11eb-9e09-4c933460f78d.png)

**Expected behavior**
Expected not throw exception

**Relevant package, tooling and runtime versions**
`netcoreapp3.1`
`Serilog.AspNetCore 4.1.0` 
`Swashbuckle.AspNetCore 6.1.4`

**Additional context**
no

**Comment by nblumhardt** [comment]
Interesting! Will need some debugging, not sure what might be the cause here, but if anyone's able to track it down and send a PR or clues, keen to enable this use case 👍

**Comment by skomis-mm** [comment]
Hi @benlinx1018 ,

Building `IServiceProvider` from the `IServiceCollection` is not a recommended pattern becuase it can results in multiple constructions. Use this one instead
```csharp
services.AddOptions<SwaggerGenOptions>()
    .Configure<IApiVersionDescriptionProvider>((options, provider) =>
    {
        foreach (var avd in provider.ApiVersionDescriptions)
        {
            options.SwaggerDoc(avd.GroupName, CreateMetaInfoApiVersion());
        }
    });

services.AddSwaggerGen();
```

**Comment by benlinx1018** [comment]
@skomis-mm thanks a lot, it looks great.

@nblumhardt thank you.

**Comment by dasiths** [comment]
I ran into the same problem because my integration test runner was setting up EFCore InMemory db context during the ConfigureServices methods. I presume one of those services I'm resolving has a dependency on `ILogger<SomeType>`.

```c#
public class Program {
    public static void Main(string[] args)
    {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Console()
                .CreateBootstrapLogger();

        try
        {
            var webApplicationBuilder = WebApplication.CreateBuilder(args);
            // SetupLogging
            // ConfigureServices
            var app = webApplicationBuilder.Build();
            // Configure(app);
            app.Run();
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "An unhandled exception occurred during bootstrapping.");
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }
}

public class MyApiApplication: WebApplicationFactory<Program>
{
    private readonly string _dbName;

    public ModernAwardsApiApplication(string dbName)
    {
        _dbName = dbName;
    }

    public static ModernAwardsApiApplication Create(string dbName, Action<MapiDbContext>? seedDatabaseAction = null)
    {
        var instance = new ModernAwardsApiApplication(dbName, configureServicesAction, configBuilderAction);
        instance.InitializeDatabase(seedDatabaseAction);
        return instance;
    }

    protected override IHost CreateHost(IHostBuilder builder)
    {
        builder.ConfigureServices(services =>
        {
            var descriptor = services.Single(d => d.ServiceType == typeof(DbContextOptions<MyDbContext>));
            services.Remove(descriptor);

            services.AddDbContext<MyDbContext>(options =>
            {
                options.UseInMemoryDatabase(_dbName);
            });
        });

        builder.ConfigureAppConfiguration((context, configurationBuilder) =>
        {
            // Add settings from appsettings.json in integration testing project
            var projectDir = Directory.GetCurrentDirectory();
            var configPath = Path.Combine(projectDir, "appsettings.json");
            configurationBuilder.AddJsonFile(configPath, optional: false);

            // Add user secrets in API project
            configurationBuilder.AddUserSecrets<Program>(optional: true);
        });

        return base.CreateHost(builder);
    }

    private void InitializeDatabase(Action<MyDbContext>? seedDatabaseAction = null)
    {
        using var scope = Services.CreateScope();
        var scopedServices = scope.ServiceProvider;
        var db = scopedServices.GetRequiredService<MapiDbContext>();

        db.Database.EnsureCreated();

        try
        {
            seedDatabaseAction?.Invoke(db);
        }
        catch (Exception ex)
        {
            var logger = scopedServices.GetRequiredService<ILogger<BootstrapTests>>();
            logger.LogError(ex, "An error occurred seeding the " +
                                "database with test messages. Error: {Message}", ex.Message);
        }
    }
}

```

Creating a new instance of `MyApiApplication` would randomly throw the "The logger is already fozen error" for different tests. I think it was a race condition because `Log.Logger` is a static.

As a workaround I had to introduce a static field in the Program.cs class and set that to true during integration test runs. Then not create the bootstrap logger if the field was set to true.

**Comment by dasiths** [comment]
> I ran into the same problem because my integration test runner was setting up EFCore InMemory db context during the ConfigureServices methods. I presume one of those services I'm resolving has a dependency on `ILogger<SomeType>`.
> 
> ```cs
> public class Program {
>     public static void Main(string[] args)
>     {
>             Log.Logger = new LoggerConfiguration()
>                 .WriteTo.Console()
>                 .CreateBootstrapLogger();
> 
>         try
>         {
>             var webApplicationBuilder = WebApplication.CreateBuilder(args);
>             // SetupLogging
>             // ConfigureServices
>             var app = webApplicationBuilder.Build();
>             // Configure(app);
>             app.Run();
>         }
>         catch (Exception ex)
>         {
>             Log.Fatal(ex, "An unhandled exception occurred during bootstrapping.");
>         }
>         finally
>         {
>             Log.CloseAndFlush();
>         }
>     }
> }
> 
> public class MyApiApplication: WebApplicationFactory<Program>
> {
>     private readonly string _dbName;
> 
>     public MyApiApplication(string dbName)
>     {
>         _dbName = dbName;
>     }
> 
>     public static MyApiApplication Create(string dbName, Action<MapiDbContext>? seedDatabaseAction = null)
>     {
>         var instance = new MyApiApplication(dbName, configureServicesAction, configBuilderAction);
>         instance.InitializeDatabase(seedDatabaseAction);
>         return instance;
>     }
> 
>     protected override IHost CreateHost(IHostBuilder builder)
>     {
>         builder.ConfigureServices(services =>
>         {
>             var descriptor = services.Single(d => d.ServiceType == typeof(DbContextOptions<MyDbContext>));
>             services.Remove(descriptor);
> 
>             services.AddDbContext<MyDbContext>(options =>
>             {
>                 options.UseInMemoryDatabase(_dbName);
>             });
>         });
> 
>         builder.ConfigureAppConfiguration((context, configurationBuilder) =>
>         {
>             // Add settings from appsettings.json in integration testing project
>             var projectDir = Directory.GetCurrentDirectory();
>             var configPath = Path.Combine(projectDir, "appsettings.json");
>             configurationBuilder.AddJsonFile(configPath, optional: false);
> 
>             // Add user secrets in API project
>             configurationBuilder.AddUserSecrets<Program>(optional: true);
>         });
> 
>         return base.CreateHost(builder);
>     }
> 
>     private void InitializeDatabase(Action<MyDbContext>? seedDatabaseAction = null)
>     {
>         using var scope = Services.CreateScope();
>         var scopedServices = scope.ServiceProvider;
>         var db = scopedServices.GetRequiredService<MapiDbContext>();
> 
>         db.Database.EnsureCreated();
> 
>         try
>         {
>             seedDatabaseAction?.Invoke(db);
>         }
>         catch (Exception ex)
>         {
>             var logger = scopedServices.GetRequiredService<ILogger<BootstrapTests>>();
>             logger.LogError(ex, "An error occurred seeding the " +
>                                 "database with test messages. Error: {Message}", ex.Message);
>         }
>     }
> }
> ```
> 
> Creating a new instance of `MyApiApplication` would randomly throw the "The logger is already fozen error" for different tests. @nblumhardt I think it was a race condition because `Log.Logger` is a static.
> 
> As a workaround I had to introduce a static field in the Program.cs class and set that to true during integration test runs. Then not create the bootstrap logger if the field was set to true.

This is stemming from the fact that WebApplicationFactory creates an instance of the test host per its lifetime. So Program.cs Main is called many times during the integration test suite. This causes race conditions where `Log.Logger` is used.

The solution here is to either have one instance of WebApplicationFactory in your integration test suite or have your integration tests run sequentially (i.e. XUnit https://stackoverflow.com/questions/1408175/execute-unit-tests-serially-rather-than-in-parallel).

**Comment by Jflaurendeau** [comment]
I had a similar problem. I use the `IApiVersionDescriptionProvider.ApiVersionDescriptions` à two places, so I created a method to fetch the data from `WebApplicationBuilder.Services`.
```c#
public static IReadOnlyList<ApiVersionDescription> GetApiVersionDescriptions(this IServiceCollection services)
{
    return services.BuildServiceProvider()
        .GetRequiredService<IApiVersionDescriptionProvider>().ApiVersionDescriptions;
}
``` 
The second call to the method was the one that cause my issue, because I called it after the application was built. To correct my issue, instead of getting the service from `WebApplicationBuilder.Services`, I fetch the service from the `IApplicationBuilder.ApplicationServices`.
```c#
var apiVersionDescriptions = app.ApplicationServices.GetRequiredService<IApiVersionDescriptionProvider>().ApiVersionDescriptions;
```

**Comment by sanderaernouts** [comment]
I know this is an older issue but passing `preserveStaticLogger: true` to `.UseSerilog(..)` solved the issue for me. I have not found a way to get rid of my `BuildServiceProvider()` call, so this seems to be a way around the `System.InvalidOperationException: The logger is already frozen`
```
Host.CreateDefaultBuilder(args)
  .UseSerilog(
      (context, services, configuration) => configuration
          .ReadFrom.Configuration(context.Configuration)
          .ReadFrom.Services(services)
          .Enrich.FromLogContext()
          .WriteTo.Console(),
      true
  )
```

**Comment by con-roki** [comment]
`preserveStaticLogger: true`  worked for me as well, but it's still unclear, after checking source code what implications it might cause ? Will it lower the performance of the app or what ?

**Comment by jacobjmarks** [comment]
See related https://github.com/serilog/serilog-aspnetcore/issues/105
