### ISSUE TITLE
Rolling option is not respected

### ISSUE THREAD

**Issue by ahdung** [serilog/serilog-aspnetcore#252]
**Description**
I setted `rollingInterval`  to `Day`, but `*_001.log` files appeared in the logs.
![微信截图_20210607090033](https://user-images.githubusercontent.com/12094247/120946882-8feef980-c770-11eb-86fd-353871c5ce6f.png)

**Reproduction**
1. create a asp.net core 5.0 project
2. in `appsettings.json` configure serilog like:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "Serilog": {
      "MinimumLevel": {
        "Override": {
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "WriteTo": [
        { "Name": "Console" },
        {
          "Name": "File",
          "Args": {
            "path": "Logs/.log",
            "outputTemplate": "{Timestamp:yyyy-MM-ddTHH:mm:ss.fffzzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
            "fileSizeLimitBytes": null,
            "rollingInterval": "Day"
          }
        }
      ]
    }
  },
  xxx
}
```
3. in `Program.cs/CreateHostBuilder`:
```c#
var host = Host.CreateDefaultBuilder(args)
               .UseSerilog((context, logger) => logger.ReadFrom.Configuration(context.Configuration, "Logging:Serilog"))
               .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.ConfigureKestrel(options => options.AddServerHeader = false);
                })
                xxx
```

**Expected behavior**
One day one log file.

**Relevant package, tooling and runtime versions**
Serilog.AspNetCore 4.1.0 from nuget.org
VS2019 16.10
Windows server 2008 R2 SP1

**Comment by nblumhardt** [comment]
By default, the file sink locks log files exclusively, and the `_001` etc. files will be created if an instance of the sink starts up while another has the file locked. Adding `"shared": "true"` to the file sink's args should sort this out for you. HTH!

**Comment by ahdung** [comment]
Thank you, I'll try it.

**Comment by wtjones** [comment]
Using `"shared": "true"` solves the issue for me. It might make sense to suggest this setting in the docs.
