### ISSUE TITLE
UseSerilog() doesn't do anything when using two-stage initialization

### ISSUE THREAD

**Issue by vvolodin** [serilog/serilog-aspnetcore#254]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other related package, please try to track down the correct repository for that package and create the report there: this tracker is for the  **Serilog.AspNetCore** package only.

**Description**
`UseSerilog()` doesn't execute supplied callback.

**Reproduction**
I've added serilog to my project and it worked fine with various sinks. But then I've decided to try two-stage initialization and it doesn't work. The callback supplied as parameter to `UseSerilog()` simply doesn't run. Here's some code from my `Program.cs`:

 ```
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, config) =>
                {
                    if (context.HostingEnvironment.IsProduction() || context.HostingEnvironment.IsStaging())
                    {
                        var builtConfig = config.Build();
                        var secretClient = new SecretClient(
                            new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
                            new DefaultAzureCredential());
                        config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());
                    }
                })
                .UseSerilog((context, configuration) => configuration
                    .WriteTo.Console()
                    .ReadFrom.Configuration(context.Configuration)
                    //.ReadFrom.Services(services)
                    .Enrich.FromLogContext()
                    .WriteTo.Debug()
                    .WriteTo.Console()
                )
                .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

**Expected behavior**
Logger has to be created and sinks set up.

**Relevant package, tooling and runtime versions**
4.1.0, tried both on Windows and Mac

**Comment by DemoBytom** [comment]
I have the same problem. It looks like moving `UseSerilog` to the `webBuilder` causes it to be setup, but I'm not sure if that's an intended fix:
```csharp
.ConfigureWebHostDefaults(webBuilder =>
{
    webBuilder
        .UseStartup<Startup>()
        .UseSerilog((ctx, cfg) => ConfigurationLambda);
});
```
That way the `ConfigurationLambda` is called.

Alternatively, I've discovered that adding `services.BuildServiceProvider` to `Startup` does invoke the UseSerilog lambda from the og `HostBuilder`:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    var logger = services
      .BuildServiceProvider()
      .GetRequiredService<ILogger<Startup>>();
    [...]
```

That is of course a terrible idea, as indicated by the warning you get when you do so:
```
ASP0000 Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created. Consider alternatives such as dependency injecting services as parameters to 'Configure'.
```

Injecting via Configure does not invoke the og UseSerilog lambda.

So at the moment I'm not sure what the intended way of adding Serilog to a service is.

**Comment by nblumhardt** [comment]
Thanks for the heads-up. Is it possible to also include your initialization code i.e. earlier in Program.cs where `CreateBootstrapLogger()` is being called? Thanks!

**Comment by slaneyrw** [comment]
Also, please note that the docs indicate the lambda has 3 arguments ( context, services and config ) but UseSerilog's callback only has 2

https://github.com/serilog/serilog-aspnetcore/blob/5b0205536a403efe96a9636a8705b50194bc4ada/src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L106

**Comment by nblumhardt** [comment]
@slaneyrw thanks for the note; the older web host builder configuration callback has two args, but the newer three-arg host builder one, which is what the docs refer to, is here: https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L135

**Comment by slaneyrw** [comment]
> @slaneyrw thanks for the note; the older web host builder configuration callback has two args, but the newer three-arg host builder one, which is what the docs refer to, is here: https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L135

So does that mean the extension used from inside the ConfigureWebHostDefaults is obsolete and it should be moved to the IHostBuilder level ?

**Comment by nblumhardt** [comment]
Yes, that's right 👍  ... There's already a `UseSerilog()` at the host builder level; we haven't marked the earlier one obsolete but it's probably time to make that change. A PR would be great, if anyone following along has a chance to dig into the details.

@vvolodin I'm guessing you've found the cause of your problem by now; if not, please feel free to comment here/reopen, but we'll need the JSON configuration, logger setup code (stage 1 initialization), and a description of what's not working before we can dig much further. Thanks!

**Comment by MJLHThomassen-Sorama** [comment]
I am walking into the same issue with Serilog.AspNetCore 6.1.0
The Callback passed to UseSerilog is never called.

@nblumhardt  @vvolodin  how did you solve this issue?
