### ISSUE TITLE
Documentation: typo in README.md

### ISSUE THREAD

**Issue by zetroot** [serilog/serilog-aspnetcore#256]
**Description**
> What's going wrong?

Found a typo in documentation in README.md. The text offers to use `CreateBoostrapLogger()` extension method, but there is no such.

**Reproduction**
> Please provide code samples showing how you're configuring and calling Serilog to produce the behavior.

No calls needed. Just open `REAMDE.md` [here](https://github.com/serilog/serilog-aspnetcore#two-stage-initialization)

**Expected behavior**
> A concise description of what you expected to happen.

I would like to have a correct name here - `CreateBootstrapLogger()`

**Relevant package, tooling and runtime versions**
> What Serilog version are you using, on what platform?

Found it on `dev` branch, at least in commit [094f15cb9b12790a3fd040d603dd3042e5f92c4d](https://github.com/serilog/serilog-aspnetcore/tree/094f15cb9b12790a3fd040d603dd3042e5f92c4d#two-stage-initialization)

**Additional context**
> Add any other context about the problem here.

Nothing to say :-)

**Comment by thinkOfaNumber** [comment]
fork, if it helps for a PR!
https://github.com/thinkOfaNumber/serilog-aspnetcore

**Comment by nblumhardt** [comment]
Thanks @zetroot 👍
