### ISSUE TITLE
ECCN question

### ISSUE THREAD

**Issue by saurabhsablaka** [serilog/serilog-aspnetcore#257]
Hello,

We use your component **serilog-aspnetcore** in our commercial product and therefore need to know the ECCN for it.

The ECCN is an international Export control and compliance number that is necessary for EVERY Export.
We need this information to classify our product embedding your component.
In case you have difficulties to provide us such ECCN number at least please answer the following questions, that will allow us to evaluate possible restriction on the exportability of the final product:

- Is the SW designed or modified to use cryptography performing any cryptographic function other than authentication or digital signature?
- If yes for what purpose is it used?
- Is your SW or part of it developed in US or by a US citizen?
- Is there US content in there? ( e.g. other open source libs)
- If yes what kind of SW?

Kind Regards,
Saurabh

**Comment by nblumhardt** [comment]
Hi! The complete source code and contribution history are available in this repository, which should be sufficient to answer your questions without any chance that my faulty memory will lead you astray. Hope this helps!
