### ISSUE TITLE
typo in Readme.md

### ISSUE THREAD

**Issue by thinkOfaNumber** [serilog/serilog-aspnetcore#259]
**Description**
Readme.md uses "boostrap..." instead of "bootstrap..."

Not a biggie, but I copied and pasted the wrong word to search for it so it threw out my search results :D

I created a fork [here ](https://github.com/thinkOfaNumber/serilog-aspnetcore) but didn't realise I couldn't create a PR, so it may be easier for someone with permission to edit directly...

Thanks!

**Comment by thinkOfaNumber** [comment]
dang, didn't see #256, sorry

**Comment by nblumhardt** [comment]
Thanks for the note. Anyone should be able to send a PR to this repo - could just be that you need to tweak the from/to repos and branches in the new PR screen? Will fix it now here, anyway, but thanks again!
