### ISSUE TITLE
Injecting ILoggerFactory and creating a logger does not log

### ISSUE THREAD

**Issue by generik0** [serilog/serilog-aspnetcore#26]
Hi

Great package. Thanks!!!
Is it just me or when i inject the ILoggerFactory into a controller, and use the create, it does not seam like the logging takes place.

I.e. the loggin is working for the WebHost. But not the individual Controller.

My WevbHost =

```c#
WebHost.CreateDefaultBuilder()
                .UseStartup<Startup>()
                .UseSerilog((hostingContext, loggerConfiguration) => 
                    loggerConfiguration.ReadFrom.Configuration(hostingContext.Configuration)
                        .Enrich.FromLogContext()
                        .WriteTo.Console()
                        .WriteTo.File(SerilogFileLocation, rollingInterval: RollingInterval.Day)
                )
                .Build();
```

My controller =

```c#
        private readonly ILoggerFactory _factory;
        public HomeController(ILoggerFactory factory)
        {
            _factory = factory;
        }
        public IActionResult Index()
        {
            var logger= _factory.CreateLogger("tester");
            logger.LogDebug("Foo Bar");
            return View();
        }
```

nothing pops up in the console nor file...

Any ideas.. IoC = Castle.Windsor.
Anyone have lock in inbuilt or Autofac?

**Comment by nblumhardt** [comment]
Hi! I'd guess this is because the `Debug` logging level is off by default in Serilog.

Try adding:

```csharp
    .MinimumLevel.Debug()
```

to your `LoggerConfiguration`. Cheers!

**Comment by generik0** [comment]
Jeps you where correct. onder why the config is not being read :-/

**Comment by generik0** [comment]
Hmmm, the configuration has appparently to be in the appsettings.josn.
I was hopeing to have a serilogsettings.json

Available setting in the host context:
![image](https://user-images.githubusercontent.com/2411563/35531787-58d5be8c-0538-11e8-8085-100e808c3919.png)

Available in Startup :-/
![image](https://user-images.githubusercontent.com/2411563/35531703-11de85d6-0538-11e8-806e-07463d9d3fec.png)

I wish the UseSerilog was in the startup, not on the Webhost builder...
