### ISSUE TITLE
Is UseSerilogReseponseLogging in the development plan?

### ISSUE THREAD

**Issue by nicholasyin** [serilog/serilog-aspnetcore#262]
UseSerilogRequestLogging looks really handy and powerful. But now that the request has been logged, isn't it intuitive to ask for a response logging?

**Comment by nblumhardt** [comment]
Hi @nicholasyin - `UseSerilogRequestLogging()` does include some response info; did you have something particular in mind?

**Comment by nicholasyin** [comment]
As far as I can find out, only StatusCode and the elapsed time are logged as response logging. Is it possible to further customize the response logging content?

**Comment by nblumhardt** [comment]
`options.EnrichDiagnosticContext` is a callback that should execute at the right time to add some more information from the response. It's not infinitely flexible but should cover a good range of cases.

**Comment by nicholasyin** [comment]
Good to know that. Thanks for the light.
