### ISSUE TITLE
Default Providers() sink method 

### ISSUE THREAD

**Issue by Kira-Lappo** [serilog/serilog-aspnetcore#269]
I was happy to find `writeToProviders` option in `UseSerilog()` extension method:

```csharp
    .UseSerilog(
        // note: services parameter has gone in the latest versions of the package
        (hostingContext, services, loggerConfiguration) => /* snip! */,
        writeToProviders: true)
```

but I wonder if it is possible or to use that feature in a sink format like without parameters with default behavior:

```csharp
    .UseSerilog(
        (hostingContext, loggerConfiguration) => 
        {
            // default one, to write to all registered ILoggerProvider instances in a web host
           // Currently, we don't have such a method.
            loggerConfiguration.WriteTo.Providers(); 

           // This one is actually implemented in the latest package
           ILoggerProviderCollection customCollection = null; /* creation does not matter for now */
           loggerConfiguration.WriteTo.Providers(customLoggerCollection); 
        }
    )
```

Potentially, I could use `services` parameter to get providers collection like that: `service.GetServices<ILoggerProvider>()`,
but `services` was removed in the latest package.

The question is, do we currently have some workaround or it just can't be done for the moment?

**Comment by nblumhardt** [comment]
Hi! The `services` parameter is still there - any additional info on the package versions you're targeting?

https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L135

**Comment by Kira-Lappo** [comment]
oh, 

> Hi! The `services` parameter is still there - any additional info on the package versions you're targeting?
> 
> https://github.com/serilog/serilog-extensions-hosting/blob/dev/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L135

oh, you are right.
some @!#!er used WebHost instead of Host to create a host builder. And extension for WebHostBuilder doesn't have that extension.

Then, yes, I could easilly use services collection in that case. Thanks a lot.
