### ISSUE TITLE
logger not logging object

### ISSUE THREAD

**Issue by adnan-kamili** [serilog/serilog-aspnetcore#27]
Hi,

I was trying to log the object but it doesn't display:

`this._logger.LogInformation("activation request...", viewModel);
`
but it only logs "activation request..." in the papertrail console.

**Comment by nblumhardt** [comment]
Hi! You need to include a placeholder in the message for it:

```csharp
this._logger.LogInformation("activation request... {@ViewModel}", viewModel);
```

See: https://messagetemplates.org for information on the logging syntax.

Cheers!

**Comment by adnan-kamili** [comment]
Thanks 👍
