### ISSUE TITLE
Provide exception in IDiagnosticContext

### ISSUE THREAD

**Issue by angularsen** [serilog/serilog-aspnetcore#270]
**Is your feature request related to a problem? Please describe.**
We use [Hellang.Middleware.ProblemDetails](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails/) to transform unhandled exceptions to ProblemDetails responses.

This means Serilog's `RequestLoggingMiddleware` does not observe any unhandled exceptions.

In order to log unhandled exceptions in our APIs, we currently use a separate error logging middleware.
This means we get two log events:
- One from a custom ErrorLogMiddleware.
- One from Serilog's request log middleware.

We would like to merge the exception data into Serilog's request log event by passing on the exception details via `IDiagnosticContext`.

**Describe the solution you'd like**
- Add `IDiagnosticContext.SetException(Exception e)`.
- Add `DiagnosticContextCollector.TryComplete(out IEnumerable<LogEventProperty>, out Exception)`
- Enrich log event with exception from `IDiagnosticContext`, unless an unhandled exception takes precedence.

**Pull requests**
https://github.com/serilog/serilog-extensions-hosting/pull/56
https://github.com/serilog/serilog-aspnetcore/pull/271

**Describe alternatives you've considered**
Separate error logging middleware, but then we get two log events instead of one.

**Additional context**
Current state:
![image](https://user-images.githubusercontent.com/787816/140333572-8f0a3555-1eb5-4d0b-8e07-6bb134510a45.png)

Desired state with exception merged into Serilog's request log event:
![image](https://user-images.githubusercontent.com/787816/140333867-2466ae42-9918-4e29-9ab2-07ab72fa9483.png)

**Comment by nblumhardt** [comment]
Thanks for the PR and write-up 👍 

Sounds like a reasonable solution; will need to give this some thought but will loop back to it ASAP.
