### ISSUE TITLE
Use Serilog in Asp.Net 6.0 new Program.cs?

### ISSUE THREAD

**Issue by kevingates** [serilog/serilog-aspnetcore#272]
**Is your feature request related to a problem? Please describe.**
The new Program.cs doesn't allow you to implement Seriolog as we normally would.

**Describe the solution you'd like**
A least a new How-To guide if not changes to the code necessary.

**Describe alternatives you've considered**
You could deviate from the standard template and use the Asp.net 5.0 template, but that's a lot of unnecessary work.

**Additional context**
See the changes here from 5.0 to 6.0
https://gist.github.com/davidfowl/0e0372c3c1d895c3ce195ba983b1e03d

**Comment by kevingates** [comment]
On stackoverflow, someone gave this solution: https://stackoverflow.com/questions/69274369/serilog-setup-with-two-stage-in-net-6-rc1-using-minimal-api

`builder.WebHost.UseSerilog();` but that doesn't work as it's not a proper extension method.

**Comment by houstondapaz** [comment]
Hi @kevingates I tried this stackoverflow solution, but running at contatiner (Docker) this error is throw
```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=3.0.0.0
```

**Comment by elylv** [comment]
I can use builder.WebHost.UseSerilog() but I get an error:
System.NotSupportedException: Call WebApplicationBuilder.Build() instead.
   at Microsoft.AspNetCore.Builder.ConfigureWebHostBuilder.Microsoft.AspNetCore.Hosting.IWebHostBuilder.Build()

**Comment by houstondapaz** [comment]
> Hi @kevingates I tried this stackoverflow solution, but running at contatiner (Docker) this error is throw
> 
> ```
> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=3.0.0.0
> ```


Forget, my problem was causing by [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration)

**Comment by elylv** [comment]
@houstondapaz did you manage to get it working?  How?

**Comment by houstondapaz** [comment]
> @houstondapaz did you manage to get it working? How?

@elylv I stopped the process of updating my project, for while

**Comment by skomis-mm** [comment]
@houstondapaz , @elylv you probably hit [Single File App](https://github.com/serilog/serilog-settings-configuration#net-50-single-file-applications) issue. Try the workaround (`Using` section instead of auto-discovery) and the latest version of `Serilog.Settings.Configuration`

**Comment by Tieantono** [comment]
Invoking `UseSerilog()` both on `builder.Host` and `builder.WebHost` works, I'm using `Serilog.AspNetCore` version `4.1.0`, below are my `appsettings.json` or user secrets configs:
```json
"Serilog": {
    "MinimumLevel": {
      "Default": "Information",
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
        }
      }
    ]
  }
```
And this is my `Program.cs` codes:
```csharp
using Serilog;

// Configure builder.
var builder = WebApplication.CreateBuilder(args);

var configuration = new ConfigurationBuilder()
    // For some reasons this is required so when running the dotnet run command, it will read your secrets too.
    .AddUserSecrets<Program>(optional: true)
    .AddEnvironmentVariables()
    .Build();

Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration)
    .CreateLogger();

builder.Host.UseSerilog();

// Register services.
builder.AddServices();

var app = builder.Build();

try
{
    Log.Information("Starting web host");

    // Configure the middleware.
    app.ConfigureMiddleware();
    app.Run();

    return 0;
}
catch (Exception e)
{
    Log.Fatal(e, "Host terminated unexpectedly");

    return 1;
}
finally
{
    Log.CloseAndFlush();
}

```

**Comment by nblumhardt** [comment]
Hey folks! I've put together a complete example with all of the working parts: https://github.com/datalust/dotnet6-serilog-example (it's the how-to guide you were looking for, @kevingates).

Closing, here, as I think this thread will accumulate unrelated issues that are only coincidentally observed on .NET 6. If you do spot any .NET 6-specific incompatibility, please open a new ticket. Thanks all!
