### ISSUE TITLE
About 500 status code in RequestLoggingMiddleware 

### ISSUE THREAD

**Issue by suadev** [serilog/serilog-aspnetcore#273]
https://github.com/serilog/serilog-aspnetcore/blob/706c196b599bfb497ca15bbde7009f25d61ad21f/src/Serilog.AspNetCore/AspNetCore/RequestLoggingMiddleware.cs#L70

Can someone explain why the middleware overrides the original status code with  500?

We are facing an issue. The web API returns HTTP 404 but we see HTTP 500 in logs.  

Thanks in advance.

**Comment by nblumhardt** [comment]
Hi! Might be a middleware ordering problem; where in the pipeline are you using Serilog request logging? It should be outermost, as much as possible.

**Comment by suadev** [comment]
@nblumhardt, an unhandled exception that threw by the next middleware caused the situation, thank you. 

After fixing this issue, I realized that HTTP 404 logs have an Information log level.   I resolved it like [this](https://github.com/serilog/serilog-aspnetcore/issues/152#issuecomment-972590232), but not sure about it
