### ISSUE TITLE
Two-stage initialization - callback never called

### ISSUE THREAD

**Issue by benmccallum** [serilog/serilog-aspnetcore#275]
**Description**
After a colleague gave up about 6 months ago to get this working in some other apps, I'm now trying to set it up in a new app and the `Action` provided to `UseSerilog` is just never called. I'm following the documentation in the readme to the tee.

**Reproduction**
Please provide code samples showing how you're configuring and calling Serilog to produce the behavior.

```
using System;
using Autofac.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Serilog;
using Serilog.Events;

namespace MyCompany.Api
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .CreateBootstrapLogger();

            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .AddMachineNameAppConfiguration()
                .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .UseSerilog((ctx, sp, lc) => ConfigureSerilog(ctx, sp, lc))
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                        .UseSerilog((ctx, cfg) => { /* this fires ok */ });
                        .UseStartup<Startup>();
                });

        private static LoggerConfiguration ConfigureSerilog(HostBuilderContext context, IServiceProvider serviceProvider, LoggerConfiguration configuration)
        {
            throw new Exception("This is never called!");
            return configuration
                    .ReadFrom.Configuration(context.Configuration)
                    .ReadFrom.Services(serviceProvider)
                    .Enrich.FromLogContext()
                    .WriteTo.Console();
        }
    }
}

```

**Expected behavior**
Action I provided to UseSerilog is called so that I can configure a replacement for the bootstrapped logger.

**Relevant package, tooling and runtime versions**
Latest packages and net6, but still using `IHostBuilder` setup (not new setup style).
```
    <PackageReference Include="Serilog.AspNetCore" Version="4.1.0" />
    <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="5.6.1" />
```

**Additional context**
We're using Autofac, but the other project that my team mate had issues with wasn't; so I'm not sure that'd be causing any issues.

**Comment by benmccallum** [comment]
Looking into the code in the UseSerilog extension method in this repo, it appears to be extending `IWebHostBuilder`, which made me realise the method I'm calling in my sample (as per the documentation) is off `IHostBuilder`. So this may be an issue since the generic host was introduced. Still playing around.

**Comment by benmccallum** [comment]
Can confirm that when doing `.UseSerilog((ctx, c) => { ... })` off the `webBuilder` which is `IWebHostBuilder`, that action is called.

**Comment by benmccallum** [comment]
Upgrading to Serilog.Extensions.Hosting 4.2.0 didn't help...

**Comment by benmccallum** [comment]
Seems I can't reproduce this problem in a separate fresh project... even after I add Autofac into the mix. 

Somehow it's behaving differently in my real app... maybe it's this compile-time flag...
https://github.com/serilog/serilog-extensions-hosting/blob/c729baec7d33d18dae69c603cfb3459c55699a0f/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L133

**Comment by benmccallum** [comment]
I copied the ext method into my projects. 

When I call it, I can see that in the fresh project my Action is eventually called during startup [here](https://github.com/serilog/serilog-extensions-hosting/blob/c729baec7d33d18dae69c603cfb3459c55699a0f/src/Serilog.Extensions.Hosting/SerilogHostBuilderExtensions.cs#L169).

But in my actual project the AddSingleton delegate is never called. Strange.

**Comment by benmccallum** [comment]
It turns out even the workaround with UseSerilog of the web host builder still doesn't result in standard ILogger<T> log entries being written. Even if I roll back to just a plain old Log.Logger setup hardcoded to my db and then `UseSerilog()` with no params; nothing from asp.net core gets into the db, even with lowest log level. Fresh project though; no problems...

I'm going insane here.

**Comment by benmccallum** [comment]
Alright so after getting rid of modules adding services via `builder.Populate(someLocalServiceCollection)`, which was really just to make it easy to hook up services using standard library extensions, and instead just adding those from Startup.ConfigureServices, it now doesn't take over and the UseSerilog setup callback is being called.

What a mission. Closing.

**Comment by henrikottesorensen** [comment]
>     * Once that service collection contains an ILogger/ILoggerFactory (e.g. after calling something like AddHttpClient), serilog can't do its thing

Thank you so much for posting that follow up @benmccallum. I was dealing with the exact same issue, in a ASP.NET WebAPI project using Autofac/Serilog, that we're migrating to .NET 8. And was going crazy, had created a example project to reproduce the issue, without luck.

 As soon as I disabled the RegisterInstance for loggerfactory and RegisterGeneric for ILogger, the callback 
started getting called.
