### ISSUE TITLE
Allow Use of IConfigureOptions to Configure RequestLoggingOptions

### ISSUE THREAD

**Issue by RehanSaeed** [serilog/serilog-aspnetcore#277]
**Is your feature request related to a problem? Please describe.**
[`IConfigureOptions<T>`](https://andrewlock.net/simplifying-dependency-injection-for-iconfigureoptions-with-the-configureoptions-helper/) allows you to move your configuration code to a separate class. I'd like to use this to move my lengthy configuration to a separate class in a standard way.

**Describe the solution you'd like**

Add the following API where omitting the `configureOptions` parameter causes the configuration to be retrieved from IoC.
```cs
IApplicationBuilder UseSerilogRequestLogging(this IApplicationBuilder app);
```

**Comment by skomis-mm** [comment]
Hi @RehanSaeed ,
separate `RequetLoggingOptions` configuration supported since [3.4.0](https://github.com/serilog/serilog-aspnetcore/releases/tag/v3.4.0)

**Comment by RehanSaeed** [comment]
Thats awesome. Thank you!
