### ISSUE TITLE
Unable to publish .NET 6 console application due to package downgrade

### ISSUE THREAD

**Issue by PhilBroderickFS** [serilog/serilog-aspnetcore#279]
**Description**
When trying to publish a .NET 6 console application as a self-contained app, using the latest dev version of Serilog.AspNetCore, I receive errors due to package downgrades

![image](https://user-images.githubusercontent.com/76115748/148376187-abece71a-3238-478f-831c-89e92555cde5.png)

**Reproduction**
Add Serilog.AspNetCore package and try to publish a .NET 6 Console application, using `dotnet publish -c Release -r win-x64`

**Expected behavior**
Expected the application to be published with no errors.

**Relevant package, tooling and runtime versions**
Using Serilog.AspNetCore v4.1.1-dev-00241. 

**Additional context**
If I explicitly added Serilog.Settings.Configuration v3.3.0, I was able to successfully publish my console application. From the screenshot above, the package downgrade stems from an older version of Serilog.Settings.Configuration, so does this package need updated for the 'main' Serilog.AspNetCore package?

**Comment by seriouz** [comment]
Yeah i can confirm this problem.

**Comment by nblumhardt** [comment]
Fixed in the -dev package now.
