### ISSUE TITLE
Regression of  .MinimumLevel.Override for http requests

### ISSUE THREAD

**Issue by whitemtnelf** [serilog/serilog-aspnetcore#281]
I am writing a .Net core5 web app using 

- Serilog.AspnetCore v4.1.0
- Serilog.Enrichers.Environment v2.2.0
- Serilog.Sinks.Console v4.0.1
- Serilog.Sinks.MSSqlServer v5.6.1

My Serilog setup is:
```
LoggerConfiguration loggerConfiguration = new LoggerConfiguration()
                .Enrich.WithMachineName()
                .Enrich.WithProperty("Application", "app xyz")
               .WriteTo.Console()
                .WriteTo.MSSqlServer(
                connectionString: connectionString,
                sinkOptions: new MSSqlServerSinkOptions { AutoCreateSqlTable = true, TableName = "Serilog" },
                columnOptions: columnOptions)
                .MinimumLevel.Information()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Error)
                .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Error);

            Log.Logger = loggerConfiguration.CreateLogger();

            services.AddLogging(builder => builder.AddSerilog(dispose: true));
```
I am still getting log messages for the http messages (start/sending/received/end).

I saw a bug report that said this was fixed in v4.0 but seems to be re-introduced with v4.1.0

**Comment by nblumhardt** [comment]
Hi! Can you please provide a JSON dump or similar, showing one of the events that's unexpectedly getting through?

Also, `UseSerilog()` on `IHostBuilder` is generally a better bet than `AddSerilog()` on the logging builder, unless you specifically need to use the second variant.

**Comment by whitemtnelf** [comment]
Thanks, I'll look into your suggestion. Here's the http result, I've x'd out sensitive info:

{
	"Version": "1.1",
	"Content": {
		"Headers": [
			{
				"Key": "Content-Type",
				"Value": [
					"application/json; charset=utf-8"
				]
			}
		]
	},
	"StatusCode": 200,
	"ReasonPhrase": "OK",
	"Headers": [
		{
			"Key": "Transfer-Encoding",
			"Value": [
				"chunked"
			]
		},
		{
			"Key": "Server",
			"Value": [
				"Microsoft-IIS/10.0"
			]
		},
		{
			"Key": "X-Powered-By",
			"Value": [
				"ASP.NET"
			]
		},
		{
			"Key": "Date",
			"Value": [
				"Tue, 18 Jan 2022 15:49:01 GMT"
			]
		}
	],
	"TrailingHeaders": [],
	"RequestMessage": {
		"Version": "1.1",
		"VersionPolicy": 0,
		"Content": {
			"ObjectType": "OktaUserMigrator.DTOs.OktaMigrateUserRequest, OktaUserMigrator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
			"Value": {
				"Profile": {
					"FirstName": "xxx",
					"LastName": "xxx",
					"Email": "xxx",
					"Login": "xxx",
					"MobilePhone": null
				},
				"Credentials": {
					"Password": {
						"Hash": {
							"Algorithm": "BCRYPT",
							"WorkFactor": 10,
							"Salt": "xxx",
							"Value": "xxx"
						}
					},
					"Provider": null
				}
			},
			"Headers": [
				{
					"Key": "Content-Type",
					"Value": [
						"application/json; charset=utf-8"
					]
				}
			]
		},
		"Method": {
			"Method": "POST"
		},
		"RequestUri": "http://localhost:15478/api/v1/migrate",
		"Headers": [
			{
				"Key": "Accept",
				"Value": [
					"application/json"
				]
			},
			{
				"Key": "Authorization",
				"Value": [
					"xxxx"
				]
			},
			{
				"Key": "Transfer-Encoding",
				"Value": [
					"chunked"
				]
			}
		],
		"Properties": {
			"PolicyExecutionContext": null
		},
		"Options": {
			"PolicyExecutionContext": null
		}
	},
	"IsSuccessStatusCode": true
}

[10:48:50 INF] Starting Okta User Migrator
[10:48:54 INF] migrating user xxx
[10:48:59 INF] Start processing HTTP request POST http://localhost:15478/api/v1/migrate
[10:48:59 INF] Sending HTTP request POST http://localhost:15478/api/v1/migrate
[10:49:01 INF] Received HTTP response headers after 2015.7077ms - 200
[10:49:01 INF] End processing HTTP request after 2039.2575ms - 200

**Comment by nblumhardt** [comment]
Thanks! I don't think the JSON you've posted is a single Serilog event. You can get these with `WriteTo.Console(new CompactJsonFormatter())`. HTH!

**Comment by whitemtnelf** [comment]
I posted the serialized http response object that resulted in Serilog generating the log message. Is there something else that you need? If so please provide instructions on how to capture it. Thanks

**Comment by skomis-mm** [comment]
Hi @whitemtnelf ,
try include `SourceContext` to the output template of the `Console` sink. 
It looks like `HttpClient` logging from `System.Net`  source, not the `Microsoft` one

**Comment by whitemtnelf** [comment]
Sorry for the delay, for some reason I'm not receiving notification emails. @skomis-mm  is correct, I added an override for System.Net and am no longer receiving unwanted log messages. Thanks for your help.
