### ISSUE TITLE
Migrations generating an error when serilog enabled.

### ISSUE THREAD

**Issue by rcoady70** [serilog/serilog-aspnetcore#288]
I get the following error when try to add a migration to a new core application. 
Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException: Exception of type 'Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException' was thrown.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   
   When I remove serilog configuration it works correctly.  I had a few "WriteTo"  enabled  (File, Seq) once I remove these from the APPSETTINGS.JSON it works again. 
   
So it seems to be directly related if there are any WriteTo elements it fails. Remove the writeto element and it works.
     "Serilog": {
    "Using": [ "Serilog.Sinks.Console"],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "RC": "Information",
        "Microsoft": "Information",
        "System": "Information"
      }
    },
    // https://github.com/serilog/serilog/wiki/Provided-Sinks.
    "WriteTo": [
      {
        "Name": "Console"
      }
    ]
  }

**Comment by skomis-mm** [comment]
Hi @rcoady70 ,
check workarounds [here](https://github.com/serilog/serilog-aspnetcore/issues/276).

**Comment by rcoady70** [comment]
Thanks for the response. 

I had tried this already but did not work...  Setup is simple so I do not think any other factors at play . 
New .net core 6 application with Identity added, the migration to update the identity tables just fails.

**Comment by skomis-mm** [comment]
@rcoady70 can you provide minimal example?
I've just created .net 6 web app + individual accounts from template, with Serilog added.  But could not reproduce the problem

**Comment by rcoady70** [comment]
Thanks Sergey,

I created a git repo :
https://github.com/rcoady70/Serilog.Mig.Issue.git

gh repo clone rcoady70/Serilog.Mig.Issue

Basically if you comment out the write to line in the appsettings file it
will work.

[image: image.png]

**Comment by skomis-mm** [comment]
@rcoady70 , I cloned project and executed
```csharp
dotnet ef migrations add Initial
dotnet ef database update
```

Migrations were generated and applied successfully.  The message you see `Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException` doesn't affect the behavior. It comes from implementation details of how EF tools handle top-level statements.

You can suppress this message by adding additional catch block:
```csharp
catch (Exception ex) when (ex.GetType().Name == "StopTheHostException")
{
}
```

**Comment by rcoady70** [comment]
Thanks for taking the time to review.

I assume that that catch block is added to the migration code.

**Comment by nblumhardt** [comment]
(Just a quick note, I think it'd be in your program/main entrypoint.)

**Comment by ataccounts** [comment]
Nice work guys.  Thank you for the details here.  Immediately helped with the catch.
