### ISSUE TITLE
Overriding minimum logging level for ASP.NET changes level for all

### ISSUE THREAD

**Issue by PaulDotNet** [serilog/serilog-aspnetcore#29]
I have logging in my app with configuration like this:
````csharp
            var config = new LoggerConfiguration()
                .MinimumLevel.Is(LogEventLevel.Information)
                .MinimumLevel.Override("Microsoft", LogEventLevel.Error);
````
Before any calls to ASP.NET logging from my app works at information level ,i.e. information and higher messages are logged.  Then app builds the host like this:
````csharp
            var host = WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseSerilog()
                .UseUrls("some nice url here")
                .Build();
````
and logging level for everything becomes LogEventLevel.Error. 
If this a bug in serilog-aspnetcore or am I using this nugget wrong?

**Comment by nblumhardt** [comment]
Hi @PaulDotNet - any chance you could post a bit more code, showing the events you're logging that you expect should be output (i.e. at the information level) but aren't?

Definitely not expected behaviour - a repro would be great if you still think this might be a bug. Thanks!

**Comment by nblumhardt** [comment]
Did you figure it out? If so, it'd be great to have some info here in case others hit the same issue. Thanks!

**Comment by PaulDotNet** [comment]
It was a temporary mystery that disappeared after a few days. I could not find the reason. I would put this in user error category.
