### ISSUE TITLE
Does UseSerilog replace the default loggers

### ISSUE THREAD

**Issue by gallwood** [serilog/serilog-aspnetcore#3]
Hi,

Using the standard templates in VS 2017, a new webapi project uses WebHost.CreateDefaultBuilder. This in turn adds a Console logger and a Debug logger.

The advice I've seen for Serilog is to add UseSerilog() in the WebHost creation.

If I use both CreateDefaultBuilder and UseSerilog, will Serilog replace all other loggers previously added?

Graham

**Comment by nblumhardt** [comment]
Hi Graham, thanks for getting in touch.

Yes, the default loggers are replaced - if you want console and debug logging, you can add the _Serilog.Sinks.Console_ and _Serilog.Sinks.Debug_ packages, then call `WriteTo.Console()` and `WriteTo.Debug()` on the `LoggerConfiguration`.

HTH!
Nick

**Comment by tradewithjazz** [comment]
Hi @nblumhardt,

Is this still correct for .Net core? I am using Seri for logging in file. It's working. But the original debug and console logs are still there. So it's not replacing the previous logger. Can you please help?
