### ISSUE TITLE
First console entries are not logged by Serilog.

### ISSUE THREAD

**Issue by nojaf** [serilog/serilog-aspnetcore#30]
I tried the sample and I noticed that 

```
Hosting environment: Production
Content root path: C:\temp\serilog-aspnetcore\samples\SimpleWebSample
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

isn't logged by Serilog. Is there anyway to change this?

**Comment by nblumhardt** [comment]
I think these are just regular console `WriteLine()`s, not log events - so not part of the logging infrastructure. I could be mistaken - might be one to dig into the ASP.NET Core source code to check. HTH!

**Comment by MaikuMori** [comment]
They're from `Console.WriteLine`, what you can do is instead of using `host.Run()` do:
```c#
host.Start();
host.WaitForShutdown();
```

That should bypass the console writes.

**Comment by PureKrome** [comment]
More info: https://github.com/aspnet/Hosting/issues/1340

**Comment by glennc** [comment]
Do you actually want that content in logs? It wasn't obvious to me that an option to do so was valuable.

**Comment by PureKrome** [comment]
I personally like seeing some of this data in logs so having the option/ability (to me) is helpful. Some example scenario's are localhost development or a dev server. Possible LIVE logs as a sanity/confirmation check.

**Comment by nblumhardt** [comment]
When I do this, I try to wrap everything up into a single "startup" log event, since it can be annoying to have to correlate several events carrying information about the same logical occurrence.

I'd be surprised to see anything about "pressing Ctrl+C" in a log, FWIW :-)
