### ISSUE TITLE
Git Action to create new package on referenced package release

### ISSUE THREAD

**Issue by christopher-watanabe-snkeos** [serilog/serilog-aspnetcore#300]
**Is your feature request related to a problem? Please describe.**
I use Serilog.AspNetCore in my .Net Core projects, but would like the most recent release of the [Serilog](https://www.nuget.org/packages/Serilog/2.11.0) package, without adding an extra reference to my projects. The latest version of Serilog.AspNetCore references Serilog v2.10.0, which was released September 2020. A more recent release, v2.11.0, was released April 2022.

**Describe the solution you'd like**
It might be nice if there was a Git action in this repo that gets triggered when any of the referencing packages are updated, so that all referenced packages stay up-to-date without manual effort to release new versions. 

**Describe alternatives you've considered**
1. A semi-automated approach could be implemented. Perhaps notifications to admins when new referenced packages are available to indicate readiness for manual release of a new Serilog.AspNetCore package. 

2. Anyone like me that wants the most recent versions of the referenced packages can replace the reference to Serilog.AspNetCore with individual package references (Serilog, Serilog.Extensions.\*, Serilog.Sink.\*, etc.). This is unfortunately against the recommendation that .Net Core projects reference Serilog.AspNetCore, in the READMEs of the Serilog.Extensions.Hosting & Serilog.Extensions.Configuration projects, for example.

**Comment by nblumhardt** [comment]
I agree that the lack of a 'dependency version - highest' package reference is inconvenient, but it's not a problem I think we're out to solve via this project right now. Thanks for the suggestion all the same!
