### ISSUE TITLE
Missing brace!

### ISSUE THREAD

**Issue by vicenteyu** [serilog/serilog-aspnetcore#304]
ID: Serilog.AspNetCore
Version: 6.0.1

Sample:
```
void Main()
{
	Log.Logger = new LoggerConfiguration().WriteTo.Console().CreateLogger();

	Log.Information("{\"event\":{\"list\":[{\"id\":\"test\"}]}}");
}
```

Output:
`{"event":{"list":[{"id":"test"}]}`

Last brace was lost.

**Comment by nblumhardt** [comment]
Thanks for the note!

The first argument to `Log.Information()` is a _message template_, which has [its own syntax](https://messagetemplates.org) including `{{` and `}}` escaped-single-braces. The JSON value you're passing through there isn't a valid message template, so you're seeing Serilog's best effort to interpret it.

A better way to do what you want is:

```csharp
Log.Information("{Json}", someJson);
```

where the string value `someJson` will get substituted in for the `{Json}` placeholder.

Hope this helps
Nick

**Comment by vicenteyu** [comment]
> 

I see. Thank you!
