### ISSUE TITLE
Serilog truncates debug levels by default

### ISSUE THREAD

**Issue by BearOakheart** [serilog/serilog-aspnetcore#308]
The Serilog maintainers want you to have a great experience using Serilog, and will happily track down and resolve bugs. We all have limited time, though, so please think through all of the factors that might be involved and include as much useful information as possible 😊.

ℹ If the problem is caused by a sink or other related package, please try to track down the correct repository for that package and create the report there: this tracker is for the  **Serilog.AspNetCore** package only.

**Description**
What's going wrong?

Serilog configuration has unexpected side effects. 

**Reproduction**
Please provide code samples showing how you're configuring and calling Serilog to produce the behavior.

Create project with packages:

    <PackageReference Include="Serilog.AspNetCore" Version="6.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.4.0" />

Configure logger:

```
builder.Host.UseSerilog(new LoggerConfiguration()
    .ReadFrom.Configuration(builder.Configuration)
    .CreateLogger());
```
    
Provide app settings:
   
```
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Debug",
        "System:" "Debug"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
        }
      }
    ]
  }
}

```
**Expected behavior**
When logging with serilog I would expect to receive all log messages where logging level is DEBUG or above.

**Relevant package, tooling and runtime versions**
What Serilog version are you using, on what platform?

```
net6.0 with 
    <PackageReference Include="Serilog.AspNetCore" Version="6.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.4.0" />
```

**Additional context**
Actual observed behavior is that DEBUG logs get truncated when they are clearly expected to exist on the logs. After hours of debugging and querying for simillar behavior, found out that there is an additional configuration to the sink level which is NOT documented anywhere. If that configuration is not configured it defaults to Information which truncates logs of lower levers even if you specify Minimum levels as debug. 

[10:40:58 INF] foo <ss:WhateverContext>
[10:40:58 WRN] foo <s:s:WhateverContext>
[10:40:58 ERR] foo <s:s:WhateverContext>
[10:40:58 FTL] foo <s:s:WhateverContext>

To resolve this issue, need to explicitly configure restrictedToMinimumLevel on sink level.

```
 {
        "Name": "Console",
        "Args": {
          "restrictedToMinimumLevel" : "Debug", <-- to see debug results this need to be configured explicitly
          "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <s:{SourceContext}>{NewLine}{Exception}"
        }
}
```

[10:40:58 DBG] foo <ss:WhateverContext>
[10:40:58 INF] foo <ss:WhateverContext>
[10:40:58 WRN] foo <s:s:WhateverContext>
[10:40:58 ERR] foo <s:s:WhateverContext>
[10:40:58 FTL] foo <s:s:WhateverContext>

Could we improve documentation somewhere if there is a reason for this. Or can we have this annoying side effect removed, by altering behavior to expected?

**Comment by augustoproiete** [comment]
@BearOakheart This is a core Serilog behavior and it's documented in [Configuration Basics](https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level).

<img width="927" alt="image" src="https://user-images.githubusercontent.com/177608/195579795-9705bcd3-3577-45c7-8d63-e3076b87455c.png">

Any ideas on how to improve the docs or make this more discoverable (without updating the readme of hundreds of sink repos)?

**Comment by BearOakheart** [comment]
I'd add a documentation block saying that this is also true vice versa. 

_**Logger vs. sink minimums** - it is important to realize that the logging level can only be raised for sinks, not lowered. So, if the logger's MinimumLevel is set to Information then a sink with Debug as its specified level will still only see Information level events. This is because the logger-level configuration controls which logging statements will result in the creation of events, while the sink-level configuration only filters these. To create a single logger with a more verbose level, use a separate LoggerConfiguration._

Given no configuration is provided for the sink general minimum level has no effect on sink when general level is lower than defined on the sink. 

As a user it's impossible to know that defining minimum level on top level has no effect on sinks, if that sink level is not lowered as well explicitly.

Thanks for the response and confirmation though! 👍

**Comment by nblumhardt** [comment]
Howdy! Something's not quite right, here - the default `restrictedToMinimumLevel` for the console sink (and others) is `LevelAlias.Minimum`, i.e. `Verbose`, so in the case reported here I'd also very much expect debug level logs to make it to the console. I'll have a shot at reproducing it 👀

**Comment by nblumhardt** [comment]
I can't repro this @BearOakheart - is it possible you have conflicting settings in your `appsettings.Development.json` file, environment vars, or somewhere else?

Note the debug message reaching the console sink - I've just copied your setup verbatim (aside from fixing the broken JSON):

![image](https://user-images.githubusercontent.com/342712/195761212-deee3e23-8415-45ad-babc-ace7ff86d2ad.png)

**Comment by BearOakheart** [comment]
![image](https://user-images.githubusercontent.com/9497646/195788227-172187ce-e47b-4c0b-84f1-35d40cb06715.png)
![image](https://user-images.githubusercontent.com/9497646/195787676-218b9fcf-9cc9-4b79-93f5-88633863096b.png)
![image](https://user-images.githubusercontent.com/9497646/195787791-32126ec3-267e-4b66-8df4-c15fdd616cf1.png)
![image](https://user-images.githubusercontent.com/9497646/195787957-f639ee66-05bd-4479-983d-82c910684473.png)

Here created a sanitized test project with complete configuration, with these settings debug messages are lost even though they should exist.

**Comment by nblumhardt** [comment]
appsettings.json overrides of array properties are by index, so what's happening here is your App Insights and Console `WriteTo` entries are getting merged into a single node by Microsoft.Extensions.Configuration, and the `restrictedToMinimumLevel: Information` entry from the App Insights block is being applied to Console.

Unfortunately there are a few footguns in how the system merges appsettings.json files; my recommendation is that if you need to customize a complex section like Serilog on a per-environment basis, you're better off putting the configurations in the environment-specific files only (.Development and .Production IIRC), and avoid duplicating it in the default config file.

HTH!

**Comment by BearOakheart** [comment]
Ah, geez yea ofc. Thanks a lot! I was blind sorry for the trouble :)
