### ISSUE TITLE
Serilog JsonFormatter in an ASP.Net Core 2 not being applied from appsettings file

### ISSUE THREAD

**Issue by imorital** [serilog/serilog-aspnetcore#31]
Hi all,

The "formatter" configuration does not appear to be picked up when defined in an appsettings.json file. The remainder of the configuration works correctly, but specifying the formatter does nothing with either the standard Serilog.Formatting.Json.JsonFormatter or the compact Serilog.Formatting.Compact.CompactJsonFormatter.

The SeriLog section of the appsettings file reads:

    "Serilog": {
      "Using": ["Serilog.Sinks.RollingFile"],
      "MinimumLevel": {
        "Default": "Verbose",
        "Override": {
          "Microsoft": "Warning",
          "System": "Warning"
        }
      },
      "WriteTo": [
        {
          "Name": "RollingFile",
          "Args": {
            "pathFormat": "C:\\Logs\\MLSBPortal-{Date}.txt",
            "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
            "restrictedToMinimumLevel": "Debug",
            "retainedFileCountLimit": "10",
            "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] [{ThreadId}] [{SourceContext}] [{SessionId}] [{UserName}]: {Message}{NewLine}{Exception}"
          }
        }
      ],

The same is seen (i.e. no change to output) when using:

    "formatter": "Serilog.Formatting.Json.JsonFormatter, Serilog",

Packages in use are:

- Serilog.AspNetCore - 2.1.0
- Serilog.Enrichers.Environment - 2.1.2
- Serilog.Enrichers.Thread - 3.0.0
- Serilog.Formatting.Compact - 1.0.0
- Serilog.Settings.Configuration - 2.4.0
- Serilog.Sinks.RollingFile - 3.3.0

Happy to can supply other information if required.

Thanks,

Stuart.

**Edit:** Is the issue to do with the fact that specifying the "formatter" and "outputTemplate" together is not supported? I see no way of doing this via a code (rather than config) approach.

**Comment by nblumhardt** [comment]
> Is the issue to do with the fact that specifying the "formatter" and "outputTemplate" together is not supported?

Looks like you've spotted it 👍 - yes, only one parameter or the other can be supplied.

**Comment by imorital** [comment]
Thanks for the clarification Nicholas (and also thanks to you and others for your work on this project).

Is this something that's planned to change?

Also, whilst investigating this issue, I noticed adding the JSON formatter seemed to ramp up the quantity of messages being reported in an Asp.Net Core 2.0 web app, overriding the log level set. That didn't seem right to me (although I must point out I didn't spend any time investigating)

**Comment by nblumhardt** [comment]
No ideas what might have caused the level change, sorry - might need more investigation.

Output templates and custom formatters will probably stay mutually exclusive, output templates are an implementation of a specific formatter.

**Comment by imorital** [comment]
Thanks for your info on this. Looks like I'll have to try and create my own custom formatter to provide the functionality I need.

**Comment by alastairs** [comment]
We just hit this issue - thank you @imorital for reporting it. I'm not sure who the maintainers of this repo are (@nblumhardt?), but it would be _really_ useful to have a SelfLog message written out if the configuration is known to be invalid.

**Comment by nblumhardt** [comment]
@alastairs thanks for the note; this would be one for https://github.com/serilog/serilog-settings-configuration.
