### ISSUE TITLE
Use one version of Microsoft.Extensions.Logging package across all build configurations 

### ISSUE THREAD

**Issue by AlthalusDGr8** [serilog/serilog-aspnetcore#316]
**Is your feature request related to a problem? Please describe.**
I am working on a solution with mixed projects of Dot Net Standard, Dot Net 6 and Dot Net 3.1.  With the way the reference for Microsoft.Extensions.Logging is set up, each framework comes with its own different version of the logging library

This causes problems when you are trying to migrate as it will cause a nuget restore to fail as it will claim that other libs are using an out of date version

**Describe the solution you'd like**
Set the minimum Microsoft.Extensions.Logging lib that works across all current build versions of serilog-aspnetcore)

**Describe alternatives you've considered**
I have downaloded the sroucecode myself and when setting them up to version 2.2.0 across no issues where reported and all tests executed fine

**Comment by AlthalusDGr8** [comment]
PR can be found here: https://github.com/serilog/serilog-aspnetcore/pull/317

**Comment by nblumhardt** [comment]
Discussion in #317, closing this one.
