### ISSUE TITLE
UseSsl from appsettings.json not working. 

### ISSUE THREAD

**Issue by angroPowel** [serilog/serilog-aspnetcore#318]
**Description**
Not 100 % sure if thie belongs here or in the graylog sink, but this is my issue: 

Sett the "useSsl" property in appsettings.json don't work. My appsettings.json: 

![image](https://user-images.githubusercontent.com/69149792/215995338-6e6e1f80-a13c-47d6-89e5-c3a8963af479.png)

This is my program.cs, using .Net 6: 

![image](https://user-images.githubusercontent.com/69149792/215997194-d02e5b39-8b51-4663-ae4b-a729d6b39ef6.png)

I have a local project that sends logs to a localhost graylog project, and it works fine. 

It also works to my online project if I do it like this: 

![image](https://user-images.githubusercontent.com/69149792/215998081-4a00ebaa-71a9-4fd1-8d91-8f3af47f8637.png)
 
But I would prefer to do it from appsettings.json. 

**Expected behavior**
Write logs to my online graylog project "exampleSite.com", configuring from secure connections from appsettings.json. 

**Relevant package, tooling and runtime versions**
.Net 6 running on my PC
Serilog.AspNetCore 6.1.0
Serilog.Sinks.Graylog 2.3.0

**Comment by augustoproiete** [comment]
This is specific to the Graylog sink - https://github.com/whir1/serilog-sinks-graylog/issues/88
