### ISSUE TITLE
Configure BootstrapLogger from appsettings.json file

### ISSUE THREAD

**Issue by elendil-software** [serilog/serilog-aspnetcore#319]
**Is your feature request related to a problem? Please describe.**

The [Two-stage initialization](https://github.com/serilog/serilog-aspnetcore#two-stage-initialization) chapter suggest to create a Bootstrap Logger to have a logger available immediately when the application starts.

It is also written 

> The downside of initializing Serilog first is that services from the ASP.NET Core host, including the appsettings.json configuration and dependency injection, aren't available yet.

and the example suggest to configure the logger in the code

```cs
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateBootstrapLogger();
```

This is a bit annoying to have to configure the logger in two places and/or in code.

**Describe the solution you'd like**
It would be usefull to be able to load the Bootstrap Logger configuration from appsettings.json file

**Describe alternatives you've considered**
Would it be wrong to do something like :

```cs
IConfigurationRoot configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

Log.Logger = new LoggerConfiguration()
    .ReadFrom.Configuration(configuration)
    .CreateBootstrapLogger();
```
?

**Comment by nblumhardt** [comment]
That's fine to do - you'll lose logging through Serilog for configuration file loading problems, so that's the trade-off you need to make.

**Comment by elendil-software** [comment]
Would it be desirable to have some extension method in the serilog-aspnetcore package ?
If yes, I can do a PR. Otherwise, I think we can close this issue.

Another possibility would be to give an additional example in the documentation.

**Comment by nblumhardt** [comment]
Hi @elendil-software - I think I misunderstood your question. It's not necessary to create a bootstrap logger at all, if you don't need two different logging configurations for startup and runtime.

Doing as you're suggesting, loading from appsettings.json when the app starts, is the way to go. You don't need to `CreateBootstrapLogger()` though - you can just `CreateLogger()` and then later `UseSerilog()` without doing any additional logger configuration.

Hope this makes sense; if not please chime back in, but as this ticket's a couple of months old I'll close it now.

**Comment by elendil-software** [comment]
Hi @nblumhardt 
This totally make sense. Indeed, I don't need a different configuration for startup
