### ISSUE TITLE
Unable to use Serilog after calling UseSerilog?

### ISSUE THREAD

**Issue by MV10** [serilog/serilog-aspnetcore#32]
After `UseSerilog` is called during the initial setup, is the expectation that the website (meaning code I write) will use Microsoft logging methods and not Serilog methods?

I have a fairly complex netcore2 system that uses Serilog across many library packages, console utility apps, Azure Functions apps, and ASP.NET Core 2.0 websites. All those scenarios apart from the websites are up and running and cranking out log entries just fine. Using Microsoft's DI extensions, I inject `ILogger` throughout all of these by treating `Log.Logger` as if it were a factory by registering it as a singleton (I also hook `ProcessExit` to call `Log.FlushAndClose`).

I'd been locally developing some basic functionality for the sites without this package, injecting Serilog `ILogger` references into controller and handler ctors throughout the site. It worked great, just as it had in other parts of the system. My plan was to wire up ASP.NET Core's logging before I deployed the basics to Azure App Services. I moved everything out of startup and into program-main ... and from that point, only ASP.NET Core's log entries work.

Config code below, but I'm using a combination of code-based configuration and appsettings. The code portion sets up SQL Server, for example, but appsettings.json controls things like log level. That much works, I can change log level and the events reach the database.

I suspected maybe my DI approach was a problem, so I added a test using the static `Log` and that also didn't output anything. When I looked more closely, both DI and the static are using the "silent" logger, clearly not the same instance ASP.NET Core is using.

Really hoping I don't have to use MEL over Serilog for websites...

Edit: If I put the config into a separate method and call it from Program.cs, then call it again from Startup.cs and register for DI there, then everything works -- but I don't understand why it has to be set up twice.

```csharp
return WebHost.CreateDefaultBuilder(args)
    .UseKestrel(options) // details omitted for brevity
    .UseIISIntegration()
    .UseStartup<Startup>()
    .ConfigureServices(svc =>
    {
        var opts = new ColumnOptions(); // details omitted for brevity
        Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Verbose()
                .WriteTo.Console()
                .WriteTo.MSSqlServer(sqlconnectionstring, "Logs", columnOptions: opts)
                .ReadFrom.Configuration(config)
                .Enrich.WithProperty("MachineName", Environment.MachineName)
                .CreateLogger();

        svc.AddSingleton(Log.Logger);
    })
    .UseSerilog()
    .Build();
```

**Comment by MV10** [comment]
Bah. Async shenanigans. Non-issue.

**Comment by JorgIanFloren** [comment]
can you elaborate a bit, because I'm trying to push my events to db and it won't work for some reason. I write both the console as to sqlserver as you do, but my ILogger<T>.LogInformation entries come trough in Console, but not on the db side of things.

**Comment by MV10** [comment]
@JorgIanFloren Sure, though I doubt it will help you. I simplified the code I posted above for the sake of brevity. The connection string was actually being retrieved from Azure Key Vault, and I forgot to `await` the call.

```
.WriteTo.MsSqlServer(await getSecret.SqlConnection(), "Logs", columnOptions: opts)
```

**Comment by JorgIanFloren** [comment]
It's indeed not what my problem was, I have since figured it out. 

The reason why my logging to db wasn't working, was because of a known bug that you can't send null values to custom db columns. The sink swallows all exceptions and routes them to SelfLog.

After activating SelfLog to Console I finally found out what was happening.

I just hate that my customer isn't willing to get me R# on their laptop. That way I would have found the issue 4 hours sooner :(
