### ISSUE TITLE
Using CreateBootstrapLogger starts the Host when using PMC commands for migration

### ISSUE THREAD

**Issue by philippedurocher** [serilog/serilog-aspnetcore#320]
I followed the documentation for 2 stages initialization using `CreateBootstrapLogger()` but when I use `drop-database` in the PMC, the host is trying to starts.

![image](https://user-images.githubusercontent.com/1459389/223168974-31d4ccb0-73b1-4d0e-b486-d5e92c3d4fd4.png)

When I use `drop-database`

![image](https://user-images.githubusercontent.com/1459389/223169407-49093c86-23d0-4380-b7e6-6abb28e0d820.png)

When I comment the line at the top of Program.cs
![image](https://user-images.githubusercontent.com/1459389/223169789-60308684-cf18-4396-87fe-7a0213561d42.png)

The Host is not starting when I try to `drop-database`
![image](https://user-images.githubusercontent.com/1459389/223170034-add4d93c-3135-4a50-87f6-c24b4c37cbff.png)

Would it be possible to detect when it's a migration command and not start the host?

I'm using theses Serilog packages with AspNetCore 7.0.3
```
    <PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="6.2.0" />
```

**Comment by philippedurocher** [comment]
I've found a workaround

In Program.cs add this at the end of the file
```
public partial class Program
{
	public static bool IsStartedFromMigration => Assembly.GetEntryAssembly() != Assembly.GetExecutingAssembly();

	// This constructor is mandatory to avoid making the class static.
	public Program() { }
}
```

At the top of the file, wrap the `CreateBootstrapLogger()` like this
```
if (!IsStartedFromMigration)
{
	Log.Logger = new LoggerConfiguration()
		.MinimumLevel.Debug()
		.MinimumLevel.Override("Microsoft", LogEventLevel.Information)
		.Enrich.FromLogContext()
		.WriteTo.Console()
		.CreateBootstrapLogger();
}
```

I still think CreateBootstrapLogger() should avoid starting the host when starting from migration commands.

**Comment by augustoproiete** [comment]
> _I still think CreateBootstrapLogger() should avoid starting the host when starting from migration commands_

@philippedurocher Serilog is a logging library for .NET apps... It has no knowledge of "migrations" - or whatever tool you use for that... And it should not have any knowledge about it either.

**Comment by nblumhardt** [comment]
Nice workaround, though! Thanks for posting your solution, hopefully others can find this if they're facing a similar problem.
