### ISSUE TITLE
loggerConfiguration.ReadFrom.Configuration Does not exist

### ISSUE THREAD

**Issue by rcollette** [serilog/serilog-aspnetcore#33]
The readme includes example code 
```
 .UseSerilog((hostingContext, loggerConfiguration) => loggerConfiguration
	.ReadFrom.Configuration(hostingContext.Configuration)
	.Enrich.FromLogContext()
	.WriteTo.Console())
```

But I am not seeing Configuration as a method of ReadFrom.   
![screen shot 2018-02-15 at 10 46 23 am](https://user-images.githubusercontent.com/136476/36265822-0bfead72-123e-11e8-8581-3e10b75fb69d.png)

If using a namespace is required it would be helpful to include it in the documentation since the IDE is not picking it up.  Otherwise the code sample needs to be updated.

**Comment by nblumhardt** [comment]
👍 you'll need the _Serilog.Settings.Configuration_ package for this.

**Comment by nblumhardt** [comment]
README fixed, thanks!
