### ISSUE TITLE
Serilog flush interval not working as expected

### ISSUE THREAD

**Issue by Raffaele-Doti** [serilog/serilog-aspnetcore#334]
Hi,
I hope this message finds you well. I wanted to bring to your attention an issue I encountered while using Serilog with the Serilog.AspNetCore version 7.0.0 and Serilog.Sinks.File version 5.0.0 packages.

Description:
The problem lies in the flush interval configuration of the Serilog file sink. Despite setting the `flushToDiskInterval` to TimeSpan.FromSeconds(120), the logs are not being flushed at the specified interval, causing potential performance issues.

Reproduction Steps:
1. Install the Serilog.AspNetCore version 7.0.0 and Serilog.Sinks.File version 5.0.0 packages.
2. Configure the logger with the following code snippet:

```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Information()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
    .MinimumLevel.Override("Microsoft.Hosting.Lifetime", LogEventLevel.Warning)
    .WriteTo.Logger(lc => lc
        .Filter.ByIncludingOnly(Matching.FromSource("Microsoft"))
        .WriteTo.Console(formatter: new MessageTemplateTextFormatter("{Message}", null)))
    .WriteTo.Logger(lc => lc
        .Filter.ByIncludingOnly(Matching.FromSource("Microsoft.Hosting.Lifetime"))
        .WriteTo.Console(formatter: new MessageTemplateTextFormatter("{Message}", null)))
    .WriteTo.File(@"/app/log/log.txt", flushToDiskInterval: TimeSpan.FromSeconds(120))
    .CreateLogger();

services.AddLogging(loggingBuilder =>
{
    loggingBuilder.ClearProviders();
    loggingBuilder.AddSerilog(); // Add this option to use Serilog as the default logger.
});
```

Expected Behavior:
The logs should be written to the file at the specified flush interval of 120 seconds, ensuring optimal performance.

Actual Behavior:
Despite setting the flush interval, the logs are not being flushed at real time, potentially causing performance degradation over time.

Environment Details:
- Serilog.AspNetCore version: 7.0.0
- Serilog.Sinks.File version: 5.0.0

I have confirmed this behavior by thoroughly testing it and ruling out any other potential causes.

Please let me know if you require any additional information or if there are any workarounds available for this issue. Thank you for your attention to this matter, and I look forward to your response.

Best regards,
Raffaele.

**Comment by nblumhardt** [comment]
Hi @Raffaele-Doti - I think:

a) You need to also specify `buffered: true` for `flushToDiskInterval` to have any effect, and
b) Specifying `flushToDiskInterval` won't stop .NET from flushing to the file whenever internal buffers fill up; the setting only provides a _maximum_ interval at which logs will be durably persisted.

Hope this helps,
Nick

**Comment by Raffaele-Doti** [comment]
Thank you @nblumhardt for your reply.
