### ISSUE TITLE
Excess http properties in every LogEvent

### ISSUE THREAD

**Issue by nikriaz** [serilog/serilog-aspnetcore#337]
I use Serilog.AspNetCore 6.1.0 in Net Core 7 with minimal API and Serilog configured in appsettings.json

I have explicitly configured template for WriteToFile sink like this:
`"outputTemplate": "{Timestamp:HH:mm:ss} [{Level:u3}] {SourceContext} {Message:l}{NewLine}{Exception} {Properties}"`

and it works as expected until I enable "Debug" level for my code like this:
```
  "Serilog": {
    "MinimumLevel": {
      "Default": "Warning",
      "Override": {
        "respApi": "Debug"
      }
```
After that I'm starting to get unwanted http-related details. This is an example:
` { ActionId: "c8ddc045-3861-43d6-8266-8a3f48f57e58", ActionName: "respApi.Controllers.NextController.PostConfirmCode (respApi)", RequestId: "0HMRO2797THHI:00000001", RequestPath: "/api", ConnectionId: "0HMRO2797THHI" } 21:56:55 [DBG] respApi.Engine.Commander Progress: 0, Code: 0`
 
Template seems to be still respected, just unwanted details added in front of. How to get rid of them and why they are there?

The issue was already reported in 2019 #135 but it was closed without any comments.

**Comment by sungam3r** [comment]
> added in front of

This is a tail of prev log. Try to append {NewLine} at the end of your template.

**Comment by nikriaz** [comment]
You're absolutely right, thank you!
