### ISSUE TITLE
Serilog.AspNetCore v8.0.0 but assembly version 0.0.0.0

### ISSUE THREAD

**Issue by thohng** [serilog/serilog-aspnetcore#356]
Serilog.AspNetCore v8.0.0 but assembly version 0.0.0.0

**Description**
Got warning during build:
```
C:\Program Files\dotnet\sdk\8.0.101\Microsoft.Common.CurrentVersion.targets(2382,5): warning MSB3277: Found conflicts between different versions of "Serilog.AspNetCore" that could not be resolved. [C:\....\samples\SampleWorkerService\SampleWorkerService.csproj::TargetFramework=net6.0]
C:\Program Files\dotnet\sdk\8.0.101\Microsoft.Common.CurrentVersion.targets(2382,5): warning MSB3277: There was a conflict between "Serilog.AspNetCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10" and "Serilog.AspNetCore, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10". [C:\W
```

**Reproduction**
dotnet build

**Expected behavior**
Assembly version should corresponding to package version

**Relevant package, tooling and runtime versions**
dotnet SDK 8.0.101

**Additional context**
Inspecting the assembly version

![image](https://github.com/serilog/serilog-aspnetcore/assets/9668549/c959514a-c1ce-4575-816e-1af21f094116)

**Comment by bartelink** [comment]
Triaging:
- https://nuget.info/packages/Serilog.AspNetCore/8.0.0 does show the AssemblyVersion is 0 and AssemblyFleVersion is 8
- same thing for V7 shows 7 in both cases
- snk and general settings seem consistent

Ultimately the AssemblyVersion is pretty academic for .NET Core - is this causing a specific issue?

**Comment by nblumhardt** [comment]
Life still gets confusing when assembly versions are off; I'll have a dig and see what I can figure out 🧐

**Comment by thohng** [comment]
Confirm version Serilog.AspNetCore@v8.0.1 fixes the issue

Previously, .NET 6.0 or .NET 7.0 may got issue with Serilog.AspNetCore@v8.0.0 on runtime
.NET 6.0 and Serilog.AspNetCore@v8.0.0
![image](https://github.com/serilog/serilog-aspnetcore/assets/9668549/ea497dbd-e4b1-4a3d-af3b-eb2ce1a2ce9e)

.NET 7.0 and Serilog.AspNetCore@v8.0.0
![image](https://github.com/serilog/serilog-aspnetcore/assets/9668549/c31eb11b-24ff-49c9-8a81-7ad3ce69028f)
