### ISSUE TITLE
.NET 6 version of Serilog.AspnetCore uses .NET 8 dependencies.

### ISSUE THREAD

**Issue by bleepzter** [serilog/serilog-aspnetcore#360]
The official NuGet packages show the following:

Serilog.AspnetCore and Hosting extensions v7.0.0 are compatible with .Net 6, however they uses the .NET 7 versions of 
Microsoft.Extesions.DependencyInjection v7.0.0 and 
Microsoft.Extensions.Logging v7.0.0
which will force you to upgrade to .NET 7 assemblies. WHY?!?

Serilog.AspnetCore and Hosting extensions v8.0.0 are compatible with .Net 6, however they uses the .NET 8 versions of 
Microsoft.Extesions.DependencyInjection v8.0.0 and 
Microsoft.Extensions.Logging v8.0.0

If you target .NET 6 it should use the .NET 6 versions of those dependencies.
If you target .NET 8 it should use the .NET 8 versions of those dependencies.

Your code targets a mix of both causing developers to either stay on old versions that are compatible with their framework choice or just use another library. This library causes a package hell in the following ways:

When your logger is included in a base lib - any app that targets .NET 6 (LTS -1) assemblies that includes that base lib  all of the sudden gets an assembly version mismatches and downgrade issues. 

**Moral of the story is Just because you can bring the latest package to your project - it doesn't mean you should. You should always bring the package that is in-line with your target framework.**

![image](https://github.com/serilog/serilog-aspnetcore/assets/3333921/38d15d36-130e-451b-911c-59314d987889)
![image](https://github.com/serilog/serilog-aspnetcore/assets/3333921/216223e7-ff13-4dad-808b-76b405f9ef68)
![image](https://github.com/serilog/serilog-aspnetcore/assets/3333921/d04fb9b0-802f-45ee-92ba-474c1725370f)

**Comment by nblumhardt** [comment]
Versioning of this package works  the same way as Microsoft.Extensions.* https://github.com/serilog/serilog-aspnetcore?tab=readme-ov-file#versioning

Going the other way leads to a different set of problems, unfortunately.

**Comment by bleepzter** [comment]
Actually no - Serilog doesn't follow the aspnet or .net core version monikers. For the longest time you spewed garbage over NuGet in the form of dev-XXXX builds (for both Serilog and Serilog.AspNetCore) and one day ya'll decided that now you will follow .NET's monikers? Are you kidding me? 

You just closed this bug because you don't want to deal with the real issue. Either remove the .NET 6 compatibility of the latest packages or if you are doing a targeted .NET 6 builds - use the correct dependencies.

You can't target .NET 6 and use .NET 8 packages! If you target some framework - use the correct framework packages. 

I went to war with my tech architect to use Serilog company wide and I see i was grossly mistaken. This unprofessional behavior is ridiculous. Do you know how many companies work with the guidance (.NET LTS or at most LTS-1)? It means that they can only use the whatever packages they are currently using as an LTS.

So when you sneak in incompatible packages through a logger none-the-less - it raises eyebrows.

**Comment by trinzya** [comment]
@nblumhardt  So, What would be the work around for this, Our app is on .NET 6 with 
Microsoft.EntityFrameworkCore on Version 6.0.28, With as dependency as shown in Image , while Serilog.Extensions.logging needs it be 8 or greater (Refer below image)
![image](https://github.com/user-attachments/assets/0dc38724-a6ea-421a-bb89-ce3632e50649)

![image](https://github.com/user-attachments/assets/83234bbe-d40d-4d6d-8de3-78159f9d676f)
This Version mismatch breaks the Azure function app, and throws error 


Microsoft.Azure.WebJobs.Host: Error indexing method 'TrainingFunction.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

**Comment by nblumhardt** [comment]
@trinzya you need to install v6.1.0 of Serilog.AspNetCore if you want to target v6 platform dependencies. HTH!

**Comment by nblumhardt** [comment]
(Or for Serilog.Extensions.Logging, it's v3.1.0, since the v6 versions of the package pre-date the new versioning scheme.)
