### ISSUE TITLE
Serilog doesn't create log file from my appsettings.json 

### ISSUE THREAD

**Issue by Snake0803** [serilog/serilog-aspnetcore#37]
appsettings.json

`{
  "Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "RollingFile",
        "Args": {
          "pathFormat": "%TMP%\\Log\\log-{Date}.txt",
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] [{SourceContext}] [{EventId}] {Message}{NewLine}{Exception}"
        }
      }
    ]
  }
}`
I have in my Startup.cs constructor this : 
Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .CreateLogger();
            Log.CloseAndFlush();

I use UseSerilog() in my BuildWebHost method in Program.cs and it doesn't create my log file into my TMP file

**Comment by nblumhardt** [comment]
Hi @Snake0803 - do you see any output in `SelfLog`? Also, does the configuration work if you specify a full/rooted path (without the environment variable substitution)? Thanks!

**Comment by Snake0803** [comment]
Hi @nblumhardt - In my Selflog, i have this "Ignoring added logger provider Microsoft.ApplicationInsights.AspNetCore.Logging.ApplicationInsightsLoggerProvider"
I try with the full path in my appsettings.json but there isn't file in my Temp file

**Comment by nblumhardt** [comment]
Hmm, it sounds like somehow the sink isn't being configured - is there any file output if you configure `WriteTo.RollingFile()` directly in the code? (You'll need to use a full path here as env vars aren't supported).

**Comment by Snake0803** [comment]
It works when i use `WriteTo.RollingFile(fullpath)` in my code. But i want to use %TMP% for my path because another user will use this log and the path will be different for each user 
. That's the problem

**Comment by Snake0803** [comment]
I resolve my problem. I use `string pathformat = System.Environment.ExpandEnvironmentVariables(path);'`
and it works. Thanks for your help @nblumhardt

**Comment by mkgn** [comment]
Seems this is the only thread found related to serilog configuration of settings file in aspnetcore version of serilog. So i am trying to avoid configuring Serilog in code. So i have moved everything to a dedicated serilog.json and loads the file. The part having the problem is below.

        "WriteTo": [
      {
        "Name": "Console"
      },
      {
        "Name": "File",
        "Args": {
          "path": "log.txt",
          "outputTemplate": "{Timestamp} {Message}{NewLine:1}{Exception:1}"
        }
      }
    ]

Both works fine in above configuration, but I want to append the date to the log file name and also make it a rolling file. So for that if i replace above File section with below

          {
        "Name": "RollingFile",
        "Args": {
          "pathFormat": "log-{Date}.txt",
          "outputTemplate": "{Timestamp} {Message}{NewLine:1}{Exception:1}"
        }
      }

It doesn't create the text file. I can live without it for the moment. But I would like to know how to configure it properly.
