### ISSUE TITLE
Adding IP logging

### ISSUE THREAD

**Issue by MV10** [serilog/serilog-aspnetcore#38]
I'm trying to figure out if it's possible to add automatic IP logging. The problem is that an enricher would need to use DI to grab a reference to the current (transient) `IHttpContextAccessor` and since Serilog is based upon a static instance, DI doesn't have a chance to resolve against a constructor except the first time when the logger is built from configuration.

For use within our own code, I register `Log.Logger` as a singleton, and then I register this little hack as a transient service, which allows us to inject something that logs IP (and yes, I'm mixing concerns by also logging Type, but I'd be more than willing to change that to get full-stack IP logging). 

```csharp
public interface ILoggerWithIP<T> : ILogEventEnricher
{
    ILogger Logger { get; }
}

public class LoggerWithIP<T> : ILoggerWithIP<T>
{
    private readonly ILogger logger;
    private readonly IHttpContextAccessor contextAccessor;
    public LoggerWithIP(ILogger logger, IHttpContextAccessor contextAccessor)
    {
        this.logger = logger.ForContext(typeof(T)).ForContext(this as ILogEventEnricher);
        this.contextAccessor = contextAccessor;
    }

    public ILogger Logger => logger;

    public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
    {
        string ip = $"({contextAccessor.HttpContext?.Connection.RemoteIpAddress.ToString() ?? "unknown"})";
        logEvent.AddPropertyIfAbsent(new LogEventProperty("IP", new ScalarValue(ip)));
    }
}
```

Usage is simple enough (I dislike the extra step of having to remember to reference the `Logger` property, but I see no way around it, `ILogger` has far too many methods to implement reasonably to derive from that for a cleaner approach).

```csharp
public class SomeController : Controller
{
    private readonly ILogger log;
    public SomeController(ILoggerWithIP<SomeController> iplogger)
    {
        log = iplogger.Logger;
    }
}
```

It works, but of course, log entries from ASP.NET Core know nothing of this. 

Am I overlooking some way to make this happen?

Bonus question (since I'm also logging Type): I'm a bit confused about how Serilog is compatible with Core logging. I've noticed in the .NET Core source (I've only used Serilog, I'm not really familiar with Core logging other than reading MS source code) that Microsoft is using `ILogger<T>` everywhere. Serilog's `ILogger` doesn't have this variant, so how does that work? Or is `<T>` a post-2.0 feature in Core?

**Comment by nblumhardt** [comment]
Hi @MV10 - I think in ASP.NET Core, middleware turns out to be a more natural fit for this - have you seen something like:

https://blog.getseq.net/smart-logging-middleware-for-asp-net-core/

? It should be pretty easily modified to add IP address in there with a `using LogContext.PushProperty(..)` around the `await next()` call.

Let me know how this lines up!

Nick

**Comment by MV10** [comment]
Unless I've misunderstood, that looks as if it would log all traffic, right? I was just hoping to add the IP to the JSON data for existing log-writes.

**Comment by nblumhardt** [comment]
Perhaps this is enough for your needs?

```csharp
app.Use(async (ctx, next) => {
    using (LogContext.PushProperty("IPAddress", ctx.Connection.RemoteIpAddress))
    {
        await next(ctx);
    }
});
```

**Comment by MV10** [comment]
Interesting... that looks almost too good to be true! I'll give it a shot, thanks.

**Comment by arisliang** [comment]
why next doesn't take context parameter?

**Comment by arthurchiakh** [comment]
Hi, All.
I experienced some issues during implementing this IpAddress logging. 
Here's some notes for the developers.
*** I implemented this for .Net Core 3.1 Web API.

1.) The middleware part must be placed before app.UseSerilogRequestLogging()
*** For problem: Unresolved {IPAddress} in outputTemplate.

2.) Try to put both middleware part and app.UseSerilogRequestLogging() before any IApplicationBuilder implementation. 
*** For problem: The following requests will not be logged. 

![image](https://user-images.githubusercontent.com/20477807/81149242-6b927d80-8fb0-11ea-8ae3-775b28bd8a27.png)

Hope, this able to save the developers some time.
Happy coding.

**Comment by svonidze** [comment]
The approach with `app.Use(...(LogContext.PushProperty` does not work for me in .NET 5 since MessageTemplate was not changed. I found this approach (mentioned on the main page) working
```
app.UseSerilogRequestLogging(
    options =>
        {
            options.MessageTemplate =
                "{RemoteIpAddress} {RequestScheme} {RequestHost} {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms";
            options.EnrichDiagnosticContext = (
                diagnosticContext,
                httpContext) =>
                {
                    diagnosticContext.Set("RequestHost", httpContext.Request.Host.Value);
                    diagnosticContext.Set("RequestScheme", httpContext.Request.Scheme);
                    diagnosticContext.Set("RemoteIpAddress", httpContext.Connection.RemoteIpAddress);
                };
        });
```
