### ISSUE TITLE
Log SourceContext without namespace

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog-aspnetcore#387]
**Is your feature request related to a problem? Please describe.**
When using `{SourceContext}` in a log message, it populates the source type's full name (i.e. namespace and class name). Those can be very long and noisy.

I'm sure many people like that, because it allows one to filter based on namespace and class.

But in my case I just need a quick indication of the source of the problem, and the class name is sufficient.

**Describe the solution you'd like**
A way to log just the class name. Maybe `{SourceContext:name}`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nblumhardt** [comment]
Hi! Serilog.Expressions has all you need for this; recipe is in:

https://nblumhardt.com/2021/06/customize-serilog-text-output/#-formatting-sourcecontext-as-a-simple-class-name

HTH!
