### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by karb0f0s** [serilog/serilog-aspnetcore#41]
New version has tag v2.2.1 but package has v2.1.1 [releases v2.2.1](https://github.com/serilog/serilog-aspnetcore/releases/tag/v2.2.1)

**Comment by merbla** [comment]
Nice pickup @karb0f0s!

Updated to v2.1.1 as per `master` [branch](https://github.com/serilog/serilog-aspnetcore/blob/master/src/Serilog.AspNetCore/Serilog.AspNetCore.csproj#L5)
