### ISSUE TITLE
UseSerilog() disables logging to Azure Diagnostics LogStream

### ISSUE THREAD

**Issue by pcreyght** [serilog/serilog-aspnetcore#42]
I am hosting a small logging application in an Azure web App, using the 'microsoft.aspnetcore.all' and 'serilog.aspnetcore' nuget packages

whenever I enable the UseSerilog extension method the application stops writing logs to the azure app logstream.
``` c#
public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .WriteTo.RollingFile(@"D:\home\LogFiles\Application\diagnostics-{Date}.txt")
                .CreateLogger();

                BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseSerilog() // <-- Whenever this is enabled the logstream stops outputting logfiles
                .Build();
    }
```

Is it possible to use Serilog along with the logstream functionality in azure?

**Comment by nblumhardt** [comment]
I think you need to add `shared: true` to:

```csharp
.WriteTo.RollingFile(@"D:\home\LogFiles\Application\diagnostics-{Date}.txt", shared: true)
```

**Comment by pcreyght** [comment]
I tried to write manually to the azure logfile folder using the rollingfile sink. This 'should' enable the stream since that folder is watched by azure, but unfortunately does not work, setting `shared: true` doesnt solve this for me.
According to the docs, the ASP.NET Core 2.0 automatically adds `AddAzureWebAppDiagnostics()` to the loggerfactory, my guess is that the `UseSerilog()` extension removes this feature?

**Comment by skomis-mm** [comment]
@pcreyght yes, this package replaces logger factory and you can see this if you enable `SelfLog`. If you want to preserve existing providers you need to install `serilog.extensions.logging` separately and add serilog via `ILoggingBuilder.AddSerilog()`
https://github.com/serilog/serilog-extensions-logging

**Comment by pcreyght** [comment]
@skomis-mm 
> add Serilog via ILoggingBuilder.AddSerilog()
That would mean going back in time! ;-) . plus I believe ASP.NET Core 2.0 is not working correctly with the 'ILoggingBuilder.AddSerilog()' method, not reporting debug and trace logmessages.
Anyway I seem to be able to work around the issue using the FlushToDisk interval setting of the RollingFileSink like this: 
```
.WriteTo.RollingFile(@"D:\home\LogFiles\Application\diagnostics-{Date}.txt", shared: true, flushToDiskInterval: TimeSpan.FromSeconds(5) )
```
This way the stream is working again!

Since the obvious end solution seems to be creating a seperate sink for this specific purpose, and as I understand correctly the issue ( UseSerilog() disables logging to Azure Diagnostics LogStream), is by design, I will close this issue.
Thank you all for pointing me in the right direction.

**Comment by nblumhardt** [comment]
Thanks for the investigation and fix, Paul! I'll list this in the README :+1:
