### ISSUE TITLE
Update Serilog.AspNetCore to support IHostBuilder

### ISSUE THREAD

**Issue by andrewlock** [serilog/serilog-aspnetcore#49]
I've been using this library successfully with ASP.NET Core for some time. ASP.NET Core 2.1 introduces  `IHostedService`  and `IHostBuilder` for background services, and it would be nice to be able to use this library too. Basically it's a normal ASP.NET Core app without the Http.

Unfortunately, in their infinite wisdom, the .NET team have decided to create whole new abstractions around `IHostBuilder` in different namespaces. Pretty much everything has an equivalent (e.g. there's a duplicate `IHostingEnvironment` in `Microsoft.Extensions.Hosting.Abstractions` as well as `Microsoft.AspNetCore.Hosting.Abstractions`, even though the latter lib references the former), but it means libraries written for the ASP.NET Core abstractions can't just be automatically used with `IHostBuilder`.

Despite this, I think supporting it should be very easy. The main question is where should the code live? There's a couple of options I see: 

1. We add support to the `Serilog.AspNetCore` library. That's easy enough, but would mean targeting the  ASP.NET Core packages at the .NET Core 2.1 versions. Also would mean the library needs to reference the ASP.NET Core packages.
1. We create a separate package in this repo that mirrors the existing library. The new package can target the .NET Core 2.1 packages, and has the minimal number of dependencies. But then you're versioning two libraries in the same repo which can sometimes get messy.
1. We create a separate package in a separate repo. All the benefits of the 2 with none of the versioning issues. You then have a separate code duplication issue though.

Personally I'd lean towards 3, but up to you. I'm happy to do the leg work with the rc1 packages if you like 🙂

**Comment by nblumhardt** [comment]
Hey Andrew, thanks for raising this! I think 3 does sound like less hair-pulling over the long run. Two sets of types makes me think there's every chance they'll diverge, or the newer types will supplant the older ones.

What to call it? _Serilog.Hosting_? _Serilog.Extensions.Hosting_? And do we follow suit and take a dependency on it from this library, so that this package remains an easy single-package install to cover the whole range of ASP.NET Core use cases?

Cheers!

**Comment by elevate-andrewlock** [comment]
Yeah, no idea what will happen in the future in terms tbh 🙂  They might end up diverging further (they already have slightly different APIs).

Either of those suggestions for names sounds good. Given you already have _Serilog.AspNetCore_, I'd probably go for _Serilog.Hosting_? 

Referencing the _Hosting_ library from this one is definitely a possibility. You could always move the `SerilogLoggerFactory` to the _Hosting_ library and reference it from there. One less file to maintain 😉

**Comment by andrewlock** [comment]
Yeah, no idea what will happen in the future in terms tbh 🙂  They might end up diverging further (they already have slightly different APIs).

Either of those suggestions for names sounds good. Given you already have _Serilog.AspNetCore_, I'd probably go for _Serilog.Hosting_? 

Referencing the _Hosting_ library from this one is definitely a possibility. You could always move the `SerilogLoggerFactory` to the _Hosting_ library and reference it from there. One less file to maintain 😉

**Comment by nblumhardt** [comment]
Thanks Andrew, will dig into it ASAP :+1:

**Comment by nblumhardt** [comment]
Having a hard time clawing out some proper time for this - @serilog/reviewers-core is anyone working in this area and keen to help/shepherd this through?

**Comment by SonicGD** [comment]
Hello. Any news on this issue?

**Comment by skomis-mm** [comment]
I've checked this, looks great. The name probably could also be `Serilog.Extensions.Hosting`

**Comment by nblumhardt** [comment]
Looking again, yes, since it's a _Microsoft.Extensions.*_ package, we should keep the naming consistent with our other extension packages.

@andrewlock let's do this thing! Are you able to shepherd it through an initial release? The steps would be something like:

 1. Transfer the repo to the Serilog org (it might need to go via one of us, personally - feel free to send it to me)
 1. We'll create a new "reviewers" team to manage the repo, which you'd join
 1. We'll add the project to the Serilog CI server and NuGet organization
 1. Adventure!

What do you think?

**Comment by andrewlock** [comment]
Sounds good @nblumhardt 🙂  I've just transferred the repo to you (couldn't transfer to Seriog directly). I've also renamed the package to _Serilog.Extensions.Hosting_ as suggested, and updated to the full 2.1.0 packages

**Comment by nblumhardt** [comment]
Ah, sorry @andrewlock - got distracted by the weekend and didn't manage to accept the transfer before it expired :-/ ... mind sending it again? :-) Thanks!

**Comment by andrewlock** [comment]
Yep, no worries @nblumhardt , just sent it again 🙂

**Comment by nblumhardt** [comment]
Awesome, thanks :-)

The repo is now at: https://github.com/serilog/serilog-extensions-hosting

You should have an admin team invitation @andrewlock.

May be good to close this ticket now and follow up on final details over there.
