### ISSUE TITLE
Using appsettings to configure

### ISSUE THREAD

**Issue by nrandell** [serilog/serilog-aspnetcore#5]
Not really an issue, but I've just experimented with using appsettings to configure the logger. I don't know if this is something worth adding in or not, so I'll just include a few code snippets. 

Happy to create a PR if it's valuable.

First off, in the extensions
```
public static IWebHostBuilder UseSerilogLogger(this IWebHostBuilder builder)
{
    if (builder == null) throw new ArgumentNullException(nameof(builder));
    builder.ConfigureServices((context, collection) =>
        collection.AddSingleton<ILoggerFactory>(new LoggerFactory(context.Configuration))
    );
    return builder;
}
```

Then in the factory
```
public LoggerFactory(IConfiguration configuration)
{
    Log.Logger = new LoggerConfiguration()
        .ReadFrom.Configuration(configuration)
        .CreateLogger();
    _provider = new SerilogLoggerProvider();
}
```

And finally my settings
```
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "Console"
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
  }
```

**Comment by cyrusjamula** [comment]
This would be great

**Comment by nrandell** [comment]
Ok - working on it

**Comment by nblumhardt** [comment]
Thanks for the suggestion and discussion 👍 

I am a bit hesitant to start wrapping Serilog via this package; the Serilog API already provides for this case, e.g. check out this sample: https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/SimpleWebSample/Program.cs#L13

There are some rough edges, discussed in #1, but in general I think we're aiming to wrap as little of Serilog as possible, just to get the logging provider replaced.

**Comment by nrandell** [comment]
I'd seen that one - the thing that made me do the initial work was to keep the `WebHost.CreateDefaultBuilder(args)` without having to manually create the configuration. Maybe what's needed is an extension method that takes a configuration object and returns the logger as one of the parameters. 

eg. `public static IWebHostBuilder UseSerilog(this IWebHostBuilder builder, Func<IConfiguration, Serilog.ILogger> logBuilder, bool setCoreLogger = true, bool dispose = false)`

That way there are no more dependencies added, but it keeps everything simple. Does that make sense?

**Comment by nrandell** [comment]
I've just updated the PR to remove the dependency and use a builder function as mentioned above. I think this should address the concerns.

**Comment by nrandell** [comment]
Just closed the PR based on comment

**Comment by nblumhardt** [comment]
Thanks, Nick 👍
