### ISSUE TITLE
RollingFileLogging Shared not working

### ISSUE THREAD

**Issue by geisi93** [serilog/serilog-aspnetcore#50]
I configure the Serilog Logger as follows:

`Log.Logger = new LoggerConfiguration()
	.MinimumLevel.Debug()
	.MinimumLevel.Override("Microsoft", LogEventLevel.Debug)
	.Enrich.FromLogContext()
	.Enrich.WithExceptionDetails()
	.WriteTo.RollingFile("logs/log-{Date}.txt", shared: true)
	.CreateLogger();`

However, when I try to read from the file in my application I get the following error:
`System.IO.IOException: 'The process cannot access the file 'C:\xyz\logs\log-20180614.txt' because it is being used by another process.'`

The file is opened in FileMode.Open with FileAccess.Read.

Is there anything wrong with my configuration? 

Thanks in advance

**Comment by nblumhardt** [comment]
Hi! When you say:

> The file is opened in FileMode.Open with FileAccess.Read.

do you mean that another process does have the file open? In that case, it will need to explicitly specify `FileShare.ReadWrite`.

**Comment by geisi93** [comment]
At this time, only the application (and therefore serilog) could have the file open. I get this error when I try to read from the file with FileMode.Open and FileAccess.Read

**Comment by nblumhardt** [comment]
Your application then, if you try to open the file, will also have to specify `FileShare.ReadWrite`.
