### ISSUE TITLE
Please add support for HostBuilder.

### ISSUE THREAD

**Issue by VictorioBerra** [serilog/serilog-aspnetcore#51]
[Generic Hosts in 2.1.](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)

```csharp
var host = new HostBuilder()
    .UseSerilog()
    .Build();
```

**Comment by andymac4182** [comment]
I believe you are looking for this package https://github.com/serilog/serilog-extensions-hosting
