### ISSUE TITLE
Requests logged as Trace, not Request

### ISSUE THREAD

**Issue by cmeeren** [serilog/serilog-aspnetcore#52]
As far as I can see, requests (and their responses) show up as Trace events in AI instead of Request events. Is this intentional? Can it be configured?

**Comment by adamchester** [comment]
Hey @cmeeren, perhaps you’re looking to ask this question over in the application insights sink? https://github.com/serilog/serilog-sinks-applicationinsights

**Comment by cmeeren** [comment]
I might be wrong, but I don't think so. The initial request and final response log messages are going through Serilog when I'm using this package. Before that, it did not go through Serilog. Since this package caused that change, AFAIK this belongs here.

Let me know if I should explain it in more detail or show an example of which log messages I'm thinking about.

**Comment by andymac4182** [comment]
@cmeeren I believe you need to actually set up Application Insights as well. What are are sending is the logs but not the first class request and dependancy items.

**Comment by adamchester** [comment]
Hey @cmeeren, I think you might be right, adding this package did cause your issue.

I think, if you do wish to get somebody with experience in Application Insights issues (e.g. "trace" vs "request" events), I would still suggest posting a question over in that repo: https://github.com/serilog/serilog-sinks-applicationinsights.

Hope this helps!

**Comment by cmeeren** [comment]
@andymac4182 Are you talking about using `UseApplicationInsights()`? The readme in this repo explicitly says to remove it. (For the record, I am using Serilog.Sinks.ApplicationInsights.)

@adamchester Sorry, I don't get it - The way I see it (I may very well be wrong), the issue is not a general usage issue I have, but an issue with Serilog.AspNetCore, and I fail to see how my asking the folks over at Serilog.Sinks.ApplicationInsights will help solve this issue.

**Comment by adamchester** [comment]
@cmeeren please feel free to keep trying to get your answer here, but so far it sounds like an Application Insights related issue. It’s very possible I’m just lacking an understanding of the problem you are facing, so please do continue here if you think it’s the best place. 👍 

Perhaps you could now continue describing the issue in more detail here and hopefully somebody here can help.

**Comment by seniorquico** [comment]
@adamchester I think there is some confusion about how these Serilog packages (Serilog.AspNetCore and Serilog.Sinks.ApplicationInsights) are intended to work together with or without `Microsoft.ApplicationInsights.AspNetCore`. Reading the installation instructions for Serilog.AspNetCore, I came up with the same question as @cmeeren.

A [similar issue](https://github.com/serilog/serilog-sinks-applicationinsights/issues/48) was raised on the Serilog.Sinks.ApplicationInsights project. (Of note, [nblumhardt's latest comment](https://github.com/serilog/serilog-sinks-applicationinsights/issues/48#issuecomment-372832888) is recommending that the discussion happen _in this project_). The README for Serilog.Sinks.ApplicationInsights appears to indicate they only send Event, Trace, and Exception telemetry events for what they refer to as _application logs_.

The `UseApplicationInsights()` extension method configures so much more, though (it calls [this AddApplicationInsightsTelemetry method](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/v2.5.0/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L126)). To explicitly name a few items, it:

- initializes a `DiagnosticsListener` that sends Request/Exception telemetry events for HTTP requests
- initializes a `DiagnosticsListener` that sends Dependency telemetry events for HTTP client calls (which includes calls to Azure Storage)
- includes common environment info for the application map

It would be nice to get the reasoning behind the recommendation in the installation instructions to remove the `UseApplicationInsights()` call. Is there a conflict? Does it result in double logging? I'm wondering (as @andymac4182 and others in the above referenced thread have proposed), if we should be considering Serilog.Sinks.ApplicationInsights and Microsoft.ApplicationInsights.AspNetCore together (i.e. retain the `UseApplicationInsights()` call).

I can understand that the Serilog/App Insights configuration really depends on the use case--and maybe some are interested in sending only the Event/Trace telemetry events. If that's the use case in mind, I think the installation instructions could make this a bit clearer.

**Comment by seniorquico** [comment]
The README for Serilog.Sinks.ApplicationInsights includes the following example:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<RequestTelemetryEnricherOptions>(Configuration);
    services.AddApplicationInsightsTelemetry();

    var log = new LoggerConfiguration()
        .WriteTo
	    .ApplicationInsightsTraces() // or .ApplicationInsightsEvents()
        .CreateLogger();

    // . . .
}
```

This calls `AddApplicationInsightsTelemetry` directly to enable all of the default ASP.NET Core + App Insights configuration and telemetry events mentioned in my previous comment. What's unfortunate, though, is that out of several examples in their instructions, only this _one_ includes the `AddApplicationInsightsTelemetry` call.

Between both project's READMEs, it looks pretty easy for newcomers to remove the `UseApplicationInsights` call and to _not_ add the `AddApplicationInsightsTelemetry` call. Not really sure what can be done to the README in Serilog.AspNetCore to help with this trap, but I think the README in the Serilog.Sinks.ApplicationInsights project could be improved.

**Comment by nblumhardt** [comment]
Thanks for the analysis, @seniorquico ! :+1: 

Is anyone out there keen to PR some improvements to the App Insights sink README?

**Comment by seniorquico** [comment]
@cmeeren `AddApplicationInsightsTelemetry` is definitely the method responsible for setting up the "normal experience" for ASP.NET Core + App Insights (check out [the source code here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/v2.5.0/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L126)... although, that's quite the rabbit hole). Calling this method in your Startup class should get you the Request and Dependency telemetry tracking.

However, I do not know the consequences of using both the App Insights sink + `AddApplicationInsightsTelemetry` (e.g. double logging). I'm working on adding this to my application today. I will try to post an update with additional findings in several hours. 🤞

**Comment by seniorquico** [comment]
Just a quick update-- I feel pretty close to a good configuration. I have been able to successfully configure our application with both of the App Insights logging approaches. It's currently sending `M.E.L.ILogger`, `M.E.L.ILogger<T>`, and `Serilog.Log` calls as Trace telemetry events using Serilog + the sink for App Insights. I also added a call to `AddApplicationInsightsTelemetry` to get all of the "normal" Request and Dependency telemetry events.

There is a small amount of duplication between the Request and Trace telemetry events. The detail provided by the Request telemetry events and the Azure portal's UI makes me think a handful of the Trace events could simply be filtered out by changing some minimum logging levels for ASP.NET Core on the Serilog side.

Unfortunately, the configuration is rather complex. I ran into some interesting issues as I dissected the default configs in the `Microsoft.ApplicationInsights.AspNetCore` package. I'll try to get this cleaned up and post some configuration code for review. (Let me know if the discussion should continue elsewhere.)

**Comment by seniorquico** [comment]
Here's a relatively simple configuration that works in a basic ASP.NET Core 2.1 application. I tested the configuration in a project using .NET Core 2.1 & ASP.NET Core 2.1 (I did not test it with the .NET Framework). I tested the project on a Windows host & a Linux host. I imagine that this configuration will work for many projects.

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    new WebHostBuilder()
        ...
        .ConfigureServices((hostingContext, services) =>
        {
            services.AddApplicationInsightsTelemetry(hostingContext.Configuration);
        })
        .UseSerilog((hostingContext, config) =>
        {
            config
                .ReadFrom.Configuration(hostingContext.Configuration)
                .WriteTo.ApplicationInsightsTraces(hostingContext.Configuration["ApplicationInsights:InstrumentationKey"]);
        })
        ...
```

There are a couple of interesting things to note about the above configuration.

First, the `AddApplicationInsightsTelemetry` call is pushing settings into `TelemetryConfiguration.Active` (I couldn't find this documented anywhere, just observed it). The `WriteTo.ApplicationInsightsTraces` call is then pulling settings from `TelemetryConfiguration.Active`. While this works, I'm concerned about the long-term reliability of this approach.

I found several ongoing discussions in the App Insights GitHub projects related to decoupling the configuration used by the ASP.NET Core App Insights package from `TelemetryConfiguration.Active` to better support multiple configurations in a single project. Additionally, the changelog includes this notice for v2.3.0 (current version):

> ... every WebHost has its own `TelemetryConfiguration` instance. Changes done for `TelemetryConfiguration.Active` do not affect telemetry reported by the SDK; use `TelemetryConfiguration` instance obtained through the dependency injection.

Second, I'm explicitly using the `AddApplicationInsightsTelemetry(IConfiguration)` overload to ensure any custom configuration sources are honored. Without this, the ASP.NET Core App Insights package only looks at the "default" list of configuration files (appsettings.json and appsettings.{EnvironmentName}.json) and envrionment variables (see [DefaultApplicationInsightsServiceConfigureOptions](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/v2.3.0/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs#L30-L35)).

The above configuration still needed some tweaks to meet our project's requirements. Here's the configuration block I've added to my project:

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    new WebHostBuilder()
        ...
        .ConfigureServices((hostingContext, services) =>
        {
            var config = hostingContext.Configuration;
            var environment = hostingContext.HostingEnvironment;

            // Ensure instrumentation and API keys are configured in production and staging
            // environments.
            var instrumentationKey = config["ApplicationInsights:InstrumentationKey"];
            var apiKey = config["ApplicationInsights:ApiKey"];
            if (environment.IsProduction() || environment.IsStaging())
            {
                if (string.IsNullOrEmpty(instrumentationKey))
                {
                    throw new KeyNotFoundException($"Failed to find configuration key ApplicationInsights:InstrumentationKey");
                }

                if (string.IsNullOrEmpty(apiKey))
                {
                    throw new KeyNotFoundException($"Failed to find configuration key ApplicationInsights:ApiKey");
                }
            }

            // Ensure storage folder is configured.
            var storageFolder = config["ApplicationInsights:TelemetryChannel:StorageFolder"];
            if (string.IsNullOrEmpty(storageFolder))
            {
                throw new KeyNotFoundException($"Failed to find configuration key ApplicationInsights:TelemetryChannel:StorageFolder");
            }

            // Create telemetry channel. The server telemetry channel persists events to
            // disk and retries when errors occur. The StorageFolder must be configured to
            // work in Docker.
            services.AddSingleton<ITelemetryChannel>(container =>
                new ServerTelemetryChannel
                {
                    StorageFolder = storageFolder
                });

            // Create telemetry configuration.
            services.AddApplicationInsightsTelemetry(config);
            if (!string.IsNullOrEmpty(apiKey))
            {
                services.ConfigureTelemetryModule<QuickPulseTelemetryModule>(module => module.AuthenticationApiKey = apiKey);
            }

            // Create logger factory.
            services.AddSingleton<ILoggerFactory>(container =>
            {
                var telemetryConfiguration = container.GetService<TelemetryConfiguration>();
                var logger = new LoggerConfiguration()
                    .ReadFrom.Configuration(config)
                    .WriteTo.ApplicationInsightsTraces(telemetryConfiguration, logEventToTelemetryConverter: ConvertLogEventToTelemetry)
                    .CreateLogger();
                return new SerilogLoggerFactory(logger, true);
            });
        })
        ...
```

This alternative configuration:

- uses the `TelemetryConfiguration` from the DI container created by the ASP.NET Core App Insights package (instead of passively using `TelemetryConfiguration.Active`)
- secures the Live Metrics Stream control channel using an API key
- configures the ServerTelemetryChannel's StorageFolder
- ensures required configuration keys/values are defined

**Comment by ifle** [comment]
@seniorquico Thanks for your example. What is ConvertLogEventToTelemetry?

**Comment by ifle** [comment]
I have not web application that use .Net Framework 4.6.2 and have similar issue when warnings and errors logged as trace. What I need to do for fixing that?

**Comment by seniorquico** [comment]
@ifle Sorry for not removing the `ConvertLogEventToTelemetry` method reference from the example... We simply use that to customize the telemetry objects. The method signature is as follows:

```csharp
private static ITelemetry ConvertLogEventToTelemetry(LogEvent logEvent, IFormatProvider formatProvider)
{
    // Convert LogEvent to ITelemetry and customize...
}
```

If you do not need that level of customization, simply remove that argument from the `.WriteTo.ApplicationInsightsTraces` call. Check out the [`Serilog.Sinks.ApplicationInsights` README](https://github.com/serilog/serilog-sinks-applicationinsights) for details and an example.

**Comment by ifle** [comment]
Thanks

**Comment by DinoSourcesRex** [comment]
@seniorquico Would it be possible for you to upload an example repository?

**Comment by seniorquico** [comment]
@DinoSourcesRex The project in which these configs are running is not open source, so I can't share it directly. All of the relevant configuration code is posted above. I added a task to my backlog to upload an example repo, but it will take considerable time due to work and personal constraints.
