### ISSUE TITLE
Move SerilogLoggerFactory to Serilog.Extensions.Logging

### ISSUE THREAD

**Issue by ChrisSimmons** [serilog/serilog-aspnetcore#53]
From a distance, it seems that while `SerilogWebHostBuilderExtensions` deals with bona fide ASP.NET concerns (e.g `IWebHostBuilder`), `SerilogLoggerFactory` would be better placed in a more generic .NET Core library.  Perhaps `Serilog.Extensions.Logging`.

There's also the possibility that I'm completely insane. :)

Of course if not, I realize this would be a breaking change but maybe something to consider in the next major version of this library.

**Comment by khellang** [comment]
It could be moved and type-forwarded, since this package already depends on Serilog.Extensions.Logging 😊

**Comment by ChrisSimmons** [comment]
I'll happily take this task (unless of course someone else comes along and does the hard work)

**Comment by jasper-d** [comment]
@ChrisSimmons What's the status of this?

**Comment by nblumhardt** [comment]
This is part of https://github.com/serilog/serilog-extensions-logging/pull/132

**Comment by nblumhardt** [comment]
@khellang RE the type forwarding, #87 doesn't do it as I took liberties breaking the `SerilogLoggerFactory` constructor's signature... Does seem like it would be nice and neat to type-forward here, though :-)
