### ISSUE TITLE
Question: How to deal with environment (development, staging, production)?

### ISSUE THREAD

**Issue by lonix1** [serilog/serilog-aspnetcore#54]
ASP.NET Core apps typically setup logging that takes into account the environment. In the `Startup.cs` we have for e.g.

````csharp
if (environment.IsDevelopment()) {
  loggerFactory
    .AddConsole(configuration.GetSection("Logging:Console"))
    .AddDebug(LogLevel.Warning);
}
else {
  // something else
}
````
But Serilog recommends to setup logging before the webhost (in `Program.cs`), like this:

````csharp
new LoggerConfiguration()
  .ReadFrom.Configuration(configuration)
  .CreateLogger();
````
So what is the recommended way to configure logging per environment?
- For example, I want console and debug logging when in development, and not when in production.
- Also, I'm not sure how to determine the environment, because `environment.IsDevelopment()` isn't available before the webhost is started.

**Comment by lonix1** [comment]
@milosloub Thanks for that.

I've since put different sinks in `appsettings.json` and `appsettings.Development.json`, `appsettings.Production.json` and so on.

**Comment by kinetiq** [comment]
FYI, as of .NET Core 3, EnvironmentName is marked obsolete. 

The new guidance should be:

```
var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
if (environment == Microsoft.Extensions.Hosting.Environments.Development.Production)
{
    // your config
}
```
