### ISSUE TITLE
Serilog and WebApplicationFactory

### ISSUE THREAD

**Issue by kimbell** [serilog/serilog-aspnetcore#57]
I have a .NET Core 2.1 project. I'm running tests using the new WebApplicationFactory. 
This uses information in the program.cs to bootstrap things. 

When running tests, I wan't to mock the ILogger infrastructure, not use the Serilog implementation. From what I can tell, it's not trivial to remove the Serilog implementation from DI. 

Serilog is set up in program.cs like this:
```cs
  public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseSerilog((context, configureLogger) =>
                {
                       // configuration omitted. 
                });
```
This is a cut down version of my Testing contex
```cs
 public class TestingContext : WebApplicationFactory<Startup>
    {
        /// <summary>
        /// Mocked ILogger
        /// </summary>
        public Mock<ILogger> Logger { get; } = new Mock<ILogger>();

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            var loggerProvider = new Mock<ILoggerProvider>();
            loggerProvider.Setup(x => x.CreateLogger(It.IsAny<string>())).Returns(Logger.Object);

            builder
                .UseDefaultServiceProvider(p => p.ValidateScopes = true)
                .ConfigureLogging(l =>
                {
                    // this is the only way I have found to remove Serilog
                    var serilog = (from s in l.Services
                        where s.ImplementationFactory != null &&
                              s.ImplementationFactory.Target.GetType().Assembly.FullName.Contains("Serilog.AspNetCore")
                        select s).FirstOrDefault();

                    if (serilog != null)
                    {
                        l.Services.Remove(serilog);
                    }

                    // this does not clear Serilog, it removes all ILoggerProvider
                    // Serilog is registered as an ILoggerFactory
                    l.ClearProviders(); 
                    l.AddProvider(loggerProvider.Object);
                });
        }
    }
```

**Comment by adamchester** [comment]
Hi @kimbell, I’ve been calling `UseSerilog` outside of `CreateWebHostBuilder` In Main.

This way, I can configure it differently in my tests. Does that help?

**Comment by kimbell** [comment]
This seems to be a less messy workaround. I still think ```.ClearProviders()``` should remove the Serilog implementation. This side-effect of Serilog, is unexpected and can be tricky for people to track down.

**Comment by nblumhardt** [comment]
@kimbell `ClearProviders()` removes providers from the default logger factory; since Serilog replaces the default logger factory, there's no way `ClearProviders()` can have this effect. Thanks for the feedback, though - good to have this here for others who need the same info 👍

**Comment by kimbell** [comment]
Out of curiosity, why is it replacing the default logger factory? Why isn't Serilog implemented as a provider?

**Comment by skomis-mm** [comment]
@kimbell you can plug in `Serilog` as provider with [Serilog.Extensions.Logging](https://github.com/serilog/serilog-extensions-logging). This package replaces the factory if you don't want any other providers that can be plugged in and for convenient usage.

**Comment by kimbell** [comment]
One of the first statements from that repos read me file is: 

> ASP.NET Core 2.0+ Instructions
ASP.NET Core 2.0 applications should prefer Serilog.AspNetCore and UseSerilog() instead.

The AspNetCore package replaces the default LoggerFactory registered by Microsoft. 
Looking at the SerilogLoggerFactory, it's using a SerilogLoggerProvider that is of type `ILoggerProvider`.

Since one has gone through the effort of creating a new LoggerFactory, I'm assuming there is a reason for this. I'm curious as to why? What does it bring to the table that isn't possible by just adding Serilog as another provider?

**Comment by nblumhardt** [comment]
@kimbell yes, in v2, the default "logger factory" became more of a logging framework in its own right, with level control, filtering, and configuration that all duplicate (and interact poorly) with their Serilog equivalents. More info at: https://nblumhardt.com/2017/08/use-serilog - cheers!

**Comment by kakins** [comment]
> Hi @kimbell, I’ve been calling `UseSerilog` outside of `CreateWebHostBuilder` In Main.
> 
> This way, I can configure it differently in my tests. Does that help?

This has worked for me.  It'd be nice if there was a cleaner way to do it, but I'll take it for now.

**Comment by voroninp** [comment]
I have no idea how to get rid of Serilog in tests, when calling `UseSeriLog` extension in `CreateHostBuilder` method. It's executed after any method of `WebApplicationFactory`

**Comment by voroninp** [comment]
Heh, that's nice. Almost exactly two years later I am hitting thing issue once more. =)
