### ISSUE TITLE
Shouldn't .UseSerilog() set up injection for more interfaces, and other on-boarding issues sure to confuse many developers

### ISSUE THREAD

**Issue by kinetiq** [serilog/serilog-aspnetcore#58]
First, thanks for the great project. I love Serilog, the Asp.Net core support is very strong, and I can tell a lot of effort goes into blog posts and documentation. These notes are feedback about the process I went through to get up and running, while perhaps somewhat encumbered by previous knowledge of the framework version of Serilog, and scanning, as humans do, in order to try and find the right starting point. 

### UseSerlog() and DI
As far as I can tell, .UseSerilog() creates a new ILoggerFactory and sets up injection for the generic version of Microsoft.Extensions.Logging.ILogger only. 

Shouldn't there also be DI options for:
 - The non-generic version of Microsoft.Extensions.Logging.ILogger
 - Serilog.ILogger (this one in particular seems egregious) 

There may be good reasons why these are missing, but it led to immediate confusion and frustration in my case, so it should probably at least be explained... For instance, if Microsoft.Extensions.Logging.ILogger is the best practice, maybe say that.  

### Documentation Issues
 - It was a bit tricky to find the correct starting point for Core. I think the second sentence on https://github.com/serilog/serilog-aspnetcore repo really threw me off... The intro starts like this: 

_Serilog logging for ASP.NET Core. This package routes ASP.NET Core log messages through Serilog, so you can get information about ASP.NET's internal operations logged to the same Serilog sinks as your application events_

...That second sentence may be accurate, but jumping into how core log messages are routed through Serilog could use perhaps one more sentence of setup. When I saw the wording above, I had no idea  logging core messages through Serilog was desirable. I assumed I had stumbled across a plugin of some kind for routing core's internal messaging, so I immediately bounced.

 - Which led me back to https://github.com/serilog/serilog ... There should probably be a message on the very top directing Core devs to the serilog-aspnetcore repo. 
 - This readme also contains a link to a 2.0 Upgrade Guide, which is clearly for upgrading to _Serilog_ 2, not Core. However, many devs will be skimming this looking for a way to move to .Net Core 2, so this should also probably have a message at the top.
 - I assume many people who use Serilog want to see console messages but also want to ship their logs to SEQ or Loggly or some other cloud logging provider. An immediate roadblock is the fact that you often want to send more details to the Console than to SEQ. Figuring out how to do this took probably two hours, maybe more. This could be easily eliminated.

I've spent well over a day just getting logging hooked up... That is a long time for logging. I know that once it's in place, I don't have to touch it. I am mostly leaving this feedback because I can tell you guys care about documentation and probably deeply desire a smooth on-boarding experience.  I hope you take it in that spirit. Thanks :)

**Comment by merbla** [comment]
Thanks @kinetiq we have an issue in the main repo tracking similar pain points

https://github.com/serilog/serilog/issues/1164

**Comment by stjepan** [comment]
I'm also confused about the first sentence in the readme at [Using the package](https://github.com/serilog/serilog-aspnetcore#using-the-package):

> With _Serilog.AspNetCore_ installed and configured, you can write log messages directly through Serilog or any `ILogger` interface injected by ASP.NET.

I'm getting an exception when trying to use ILogger in the constructor of a controller, with the error message saying "Unable to resolve service for type 'Serilog.ILogger' while attempting to activate..."

**Comment by kinetiq** [comment]
@stjepan Right. Turns out you have to use Microsoft.Extensions.Logging.ILogger. Unless something has changed since I was researching this. 

There is an effort underway underway to improve this documentation, apparently.

**Comment by nblumhardt** [comment]
At the moment, _Serilog.AspNetCore_ doesn't get involved in DI/IoC configuration. It'd be cool to investigate enabling this, if anyone is keen :-)

Cheers!

**Comment by ideoclickVanessa** [comment]
Currently, I've been referencing https://mcguirev10.com/2018/02/07/serilog-dependency-injection-easy-ip-logging.html and the companion https://github.com/MV10/Serilog.Dependency.Injection repo to achieve this today. Maybe you can work with Jon McGuire to get that code migrated into the this base project?

**Comment by WeihanLi** [comment]
I do not like current `UseSerilog`, it will ingore other log provider, I'd like to use `SerilogLoggerProvider` instead of `SerilogLoggerFactory`

**Comment by nblumhardt** [comment]
Closing this one - looks like some interesting things linked; we need to break this up now into individual, actionable issues to make any progress. Thanks again for the original post, @kinetiq .
