### ISSUE TITLE
How do I Initialize Serilog via config in program.cs

### ISSUE THREAD

**Issue by cyrusjamula** [serilog/serilog-aspnetcore#6]
My config has my serilog initialization code, & my config is Environment specific

            var configuration = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", false, true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true)
                .Build();

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();

Is there a recommended way to do this?

Currently i moved my Serilog Initialization code to Startup.cs. Is this an acceptable option

**Comment by nblumhardt** [comment]
Hi @cyrusjamula - moving the initialization code to _Startup.cs_ will make it hard to log errors raised during start-up; is the problem just `env.ContentRootPath`?

(Sample here: https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/SimpleWebSample/Program.cs#L13 otherwise.)

HTH!

**Comment by nblumhardt** [comment]
@cyrusjamula noticed your comment on the other thread; keen to know how the sample linked above works for you.

**Comment by cyrusjamula** [comment]
@nblumhardt The sample you provided will work.

**Comment by nblumhardt** [comment]
Thank you for the follow-up @cyrusjamula 👍
