### ISSUE TITLE
How to output CategoryName with controller class name in the log 

### ISSUE THREAD

**Issue by zujiang** [serilog/serilog-aspnetcore#62]
In serilog.aspnetcore, the logger object is a static class so the following code is used in MCV controller to log a message:

Log.Information("some message");

As there is no place to configure the category name per controller as mentioned in the below sample code via ILogger<TCategoryName> from Microsoft document,

public class TodoController : Controller
{
    private readonly ITodoRepository _todoRepository;
    private readonly ILogger _logger;

    public TodoController(ITodoRepository todoRepository,
        ILogger<TodoController> logger)
    {
        _todoRepository = todoRepository;
        _logger = logger;
    }
}

my question is: How to set the different category name for different controller since Log is now a static class? how can I output my controller class name as the category name automatically in the log file? Do I need to use {SourceContext:l} in the output template? Thanks.

**Comment by krajek** [comment]
I am pretty sure that after you attach `Serilog.AspNetCore` to your configuration, code sample you provided would still work correctly. You do not need to use the static class at all.

You could also inject Serilog's native `ILogger` if necessary.

In the end, you might use a static logger with `Log.ForContext` like described on the package author's blog: https://nblumhardt.com/2016/08/context-and-correlation-structured-logging-concepts-in-net-5/

**Comment by nblumhardt** [comment]
:+1: `Log.ForContext<MyController>().Information(...)` will do this.
