### ISSUE TITLE
Bug: Critical logs are shown as Fatal

### ISSUE THREAD

**Issue by pouladpld** [serilog/serilog-aspnetcore#63]
### Steps to Reproduce

Configure an ASP.NET Core MVC to output JSON-serialized logs to a file.

```c#
// class MyController
// ILogger<MyController> _logger

public async Task<IActionResult> Post()
{
    _logger.LogCritical("Foo {bar}.", 123);
    /* ... */
}
```

### Expected
```json
{"@t":"2018-08-22T17:52:31.0178179Z","@mt":"Foo {bar}.","@l":"Critical","bar":123}
```

### Actual

```json
{"@t":"2018-08-22T17:52:31.0178179Z","@mt":"Foo {bar}.","@l":"Fatal","bar":123}
```

**Comment by nblumhardt** [comment]
Thanks for getting in touch 👍 

This is by design - Serilog's Fatal level is synonymous with ASP.NET Core's Critical. The set of Serilog level names is fixed so arbitrary names have to be mapped onto the existing levels.

HTH!
Nick

**Comment by pouladpld** [comment]
Thanks for the quick reply. Not happy to see log levels are written on stone.

Is there any hack around it to hint my log parser that this record is in not really Fatal?

**Comment by tsimbalar** [comment]
If you need to change the output format, you may want to create your own `Formatter` based on https://github.com/serilog/serilog-formatting-compact , that will output Serilog events of level `Fatal` with the level name `Critical` in the generated `json` ... 

According to the [ASP.NET logging docs ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.logLevel?view=aspnetcore-2.1#fields) : 


Critical | 5 | Logs that describe an unrecoverable application or system crash, or a catastrophic failure that requires immediate attention.
-- | -- | --

sounds pretty *Fatal* to me :)
