### ISSUE TITLE
Nothing is logged in new minimum-changes project

### ISSUE THREAD

**Issue by MV10** [serilog/serilog-aspnetcore#64]
To my surprise, an ASP.NET Core app with nothing but this package and code-config to log Debug to Console generates no output whatsoever. The short version is that I was trying to reproduce some problems people reported in the SQL sink repo. I didn't reproduce their issues in a simple .NET Core console app, but they were all using ASP.NET Core, so my next step was to attempt to reproduce the problem that way.

See this comment in the SQL sink thread for my package versions and so on:

https://github.com/serilog/serilog-sinks-mssqlserver/issues/129#issuecomment-415175898

Do I have some sort of version mismatch?

Not mentioned in that other thread is that I added multiple levels of logging on the template `Index.cshtml.cs` so I should see at least those in the console:

```csharp
public class IndexModel : PageModel
{
    public void OnGet()
    {
        Log.Information("An Information message");
        Log.Warning("A Warning message ");
        Log.Error("An Error message ");
        Log.Verbose("A Verbose message ");
        Log.Debug("A Debug message ");
    }
}
```

**Comment by adamchester** [comment]
If all you’re doing is configuring the static logger with console output then calling static log methods, it’s unlikely related to this package, right?

This package allows routing log events generated from the MEL APIs through Serilog, but you don’t seem to be attempting that in this case. 

Do I have it wrong? I would guess you might have configured the logger wrong or in the wrong place?

**Comment by adamchester** [comment]
I went back to look at your samples, did you forget to *set the static logger*?

**Comment by MV10** [comment]
Bah... cut-and-paste error! (And too many months out of the Serilog/ASP.NET loop.) Thanks!
