### ISSUE TITLE
No EF Core logging

### ISSUE THREAD

**Issue by TheMattyBoy** [serilog/serilog-aspnetcore#65]
Bit of a newb to this, but how do I log EF Core 2.1.1 SQL statements?? Have set up Serilog as per examples and it captures Microsoft events, and I can log my own, but I don't get any events logged for ef core. I want to be able to log the SQL statements..

**Comment by hgmauri** [comment]
Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Information()
            .MinimumLevel.Override("Microsoft", LogEventLevel.Verbose)
            .MinimumLevel.Override("System", LogEventLevel.Verbose)
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .CreateLogger();

**Comment by TheMattyBoy** [comment]
Unfortunately no, that doesn't resolve the issue; it increases verbosity of the logged statements, but there isn't any logging from EF Core.

I've played around with it, and the only way I've found to get EF Core statements logged is when configuring the dB context use DI to get ILoggerFactory and set options as below:

```
public configContext(ILoggerFactory loggerFactory)
{
        new DbContextOptionsBuilder<myContext>()
               ..
               .UseLoggerFactory(loggerFactory)
               .EnableSensitiveDataLogging()    // Logs SQL parameters in addition to SQL Statements
               ...
}
```
Not really sure why I need to do this (the intellisense suggests UseLoggerFactory should never need to be configured explicitly), or any performance impact, but it seems to work.

**Comment by nblumhardt** [comment]
Thanks for posting your findings, @TheMattyBoy. This looks like the way to go.

It looks like EF makes the incorrect assumption that the built-in logger factory won't be swapped out. Could be a good candidate for a ticket over on their repo 👍

**Comment by TheMattyBoy** [comment]
Thanks for the explanation Nicholas; I'll close the issue here as it's not Serilog related, but due to EF. Will look to raise a ticket over on the EF repo, but a bit pushed for time at the moment.

**Comment by andymac4182** [comment]
@TheMattyBoy if you could link the issue to here it would be greats since we have had a similar issue.

**Comment by sommmen** [comment]
was this ever fixes in later  .net versions?
