### ISSUE TITLE
Access to the IServiceProvider in custom ILogEventSink.Emit method

### ISSUE THREAD

**Issue by StevenRasmussen** [serilog/serilog-aspnetcore#69]
Is there any way to access the aspnet core IServiceProvider during the ILogEventSink.Emit method?  I'd like to check the DI container for some settings so that I could dynamically determine whether or not to actually emit the logevent or not (basically dynamic filtering).  I have looked at the LoggerConfiguration.Filter.ByIncludingOnly method but since this configuration is setup in the Program.cs, I don't have access to the DI container at this point.  If this isn't currently possible would you consider a PR to do one of the following:

1)  Update the ByIncludingOnly and ByExcluding methods to include an overload that would pass in the IServiceProvider as a second argument to the Func (or perhaps these are new methods?
2)  Update the existing ILogEventSink interface to include another method called EmitWithServiceProvider that would also include the IServiceProvider as a parameter.  I'm guessing this is probably not the best solution since this interface is not exclusive to the aspnet core implementation
3)  Add a new interface called something like IAspNetCoreLogEventSink with an Emit method that also passes in the IServiceProvider.  The underlying code would need to be updated to check for this interface as well and call appropriately.

Maybe there's a better way that someone could suggest.  Bottom line is being able to have access to the IServiceProvider while trying to filter log events.  Thanks!

**Comment by nblumhardt** [comment]
Hi - creating your custom sink first using `var sink = new MyCustomSink()`, passing it to the logging pipeline with `WriteTo.Sink(sink)`, and then at some point setting `sink.ServiceProvider` to the appropriate one should do the job.

HTH!
