### ISSUE TITLE
asp.net core 2.1+ uses CreateWebHostBuilder instead of BuildWebHost

### ISSUE THREAD

**Issue by douglasg14b** [serilog/serilog-aspnetcore#71]
I'm honestly not sure about the details of this, as I'm new to asp.net core. But in 2.1 startup changed a bit and now uses:

```cs
        public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            var assemblyName = typeof(Startup).GetTypeInfo().Assembly.FullName;

            return WebHost.CreateDefaultBuilder(args)
                .UseStartup(assemblyName);
        }
```

instead of the `IWebHost` BuildWebHost.

It doesn't change much, as current instructions work when adjusted. But it might be worth updating the instructions to include the new configuration to avoid confusing new users.

**Comment by nblumhardt** [comment]
Thanks for the note, @douglasg14b - we'll take a look at updating the samples etc. :+1:
