### ISSUE TITLE
Serilog and Azure Functions

### ISSUE THREAD

**Issue by andreatosato** [serilog/serilog-aspnetcore#72]
Hi, this is wonderfull extension and so I want to use in my Azure Functions App.
I use Azure Functions v2 with Microsoft.Logging framework.
Can I use this package in my application?
What are the instructions to startup my project with  Microsoft.Extensions.Logging.ILogger and Serilog Sink?

**Comment by nblumhardt** [comment]
Hi - hope you found a solution to this. If not, Googling _Serilog.Sinks.ILogger_ should turn up some info. Cheers!
