### ISSUE TITLE
Question: can I use more than one serilog configuration in the same app?

### ISSUE THREAD

**Issue by WeihanLi** [serilog/serilog-aspnetcore#73]
I wanna have two set of configuration for serilog

One for logging request info only
One for logging common logs 

Is this possible? If posibble, how to config?

Thanks in advance.

**Comment by adamchester** [comment]
Hi @WeihanLi, thanks for stopping by.

Can you be a little more specific about why you want them separate, and what the source of the logs are?

**Comment by WeihanLi** [comment]
Because there's a previous project, that log and page request log are separate, there are two tables `Logs` and `PageViews` in the log db and these two tables have different structure, I wanna  sync page request log to `PageViews`(I've done via a asp.net core middleware) and sync common logs to `Logs`

data table structure are like follows:
``` sql
-- PageViews
CREATE TABLE [dbo].[PageViews]
(
[Id] [bigint] NOT NULL IDENTITY(1, 1) PRIMARY KEY,
[TimeStamp] [datetime2] NOT NULL,
[Url] [nvarchar] (max)
)

-- Logs
CREATE TABLE [dbo].[Logs]
(
[Id] [int] NOT NULL IDENTITY(1, 1) PRIMARY KEY,
[Message] [nvarchar] (max),
[MessageTemplate] [nvarchar] (max),
[Level] [nvarchar] (128),
[TimeStamp] [datetime2] NOT NULL,
[Exception] [nvarchar] (max),
[Properties] [nvarchar] (max)
)
```

**Comment by WeihanLi** [comment]
Is it possible to use one for global logger and one for scope logger?

**Comment by findmanoj** [comment]
@WeihanLi  did you got any solution here ? I too want to do the same thing using PostgreSQL sink.

**Comment by sungam3r** [comment]
You can configure two different DI containers with different sinks and settings.
