### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'

### ISSUE THREAD

**Issue by Foxsterc** [serilog/serilog-aspnetcore#74]
Hi,
My setup is as follows:

Serilog.AspNetCore 2.1.1
Serilog.Settings.Configuration 3.0.1
Serilog.Sinks.MSSqlServer 5.1.2

in Program.cs - Main

`Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(Configuration)
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .Enrich.FromLogContext()
                .CreateLogger();`

`    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                    .CaptureStartupErrors(true)
                    .UseStartup<Startup>()
                    .UseIISIntegration()
                    .UseSerilog();`

Works fine on my local machine. When deployed to IIS (WS 2012 R2) the site fails to start with the error

HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure 

Checking the logs shows

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'

Any ideas?

Thanks,

**Comment by Leafhood** [comment]
Did you find a reason or solution for this? I'm having the same problem now.

**Comment by nblumhardt** [comment]
This one's likely to be a publishing/deployment issue - closing as I don't think it'll be related directly to this package.

**Comment by PeterParker1234** [comment]
This is quite a common issue and I see no resolution to it yet - not even a further request for more details. Tickets are simply closed. It is not a publishing / deployment issue.

This problem has now presented itself on our Dev Server after working on multiple development machines and this has put us in a really bad space.

Should I register the Serilog.ASPNET assembly in GAC?

**Comment by nblumhardt** [comment]
@PeterParker1234 if you search for [Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly](https://www.google.com/search?client=firefox-b-d&q=Unhandled+Exception%3A+System.IO.FileNotFoundException%3A+Could+not+load+file+or+assembly) you'll find a stack of resources on debugging this.

Unfortunately, with a widely-used and visible project, just about every esoteric tooling issue shows up at least once, and since it's an open source project, Serilog doesn't have the resources to _prove it's not us_ in this case. Experience with these kinds of issues suggests that it's 99.999% likely to be elsewhere.

I'd love to be able to help, and will jump on this straight away if anyone can find detailed information suggesting that it _is_ a Serilog issue, but that's not where the burden of proof currently lies :-)

If you can track it down or if you find clues that we can help to interpret, please let us know. Thanks!

**Comment by PeterParker1234** [comment]
All valid points - thank you for the kind reply @nblumhardt. I definitely do not think this is a Serilog issue. My expectation to expect guidance as to steps on how to get more details on this step was also ungrounded.  Everyone's case will be unique as you say. In my case, I had to change the publish settings to "Self-Contained" (previously Framework-Dependant + Portable). This then added the files required. Also : I've read about instances  where Application Pools can not host more than one app - I had one AppPool with multiple apps.

**Comment by nblumhardt** [comment]
Thanks @PeterParker1234 👍

**Comment by erikthysell** [comment]
I have the same issue here but using Http sink:
Errror:

> [01/05/2024 08:32:32 > b80a7a: ERR ] Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Sinks.PeriodicBatching, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.
> [01/05/2024 08:32:32 > b80a7a: ERR ] File name: 'Serilog.Sinks.PeriodicBatching, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
> [01/05/2024 08:32:32 > b80a7a: ERR ]    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
> [01/05/2024 08:32:32 > b80a7a: ERR ]    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
> [01/05/2024 08:32:32 > b80a7a: ERR ]    at Serilog.Settings.Configuration.ConfigurationReader.LoadConfigurationAssemblies(IConfiguration section, AssemblyFinder assemblyFinder)
> [01/05/2024 08:32:32 > b80a7a: ERR ]    at Serilog.Settings.Configuration.ConfigurationReader..ctor(IConfiguration configSection, AssemblyFinder assemblyFinder, ConfigurationReaderOptions readerOptions, IConfiguration configuration)
> [01/05/2024 08:32:32 > b80a7a: ERR ]    at Serilog.ConfigurationLoggerConfigurationExtensions.GetConfigurationReader(IConfiguration configuration, ConfigurationReaderOptions readerOptions, DependencyContext dependencyContext)
> [01/05/2024 08:32:32 > b80a7a: ERR ]    at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, ConfigurationReaderOptions readerOptions)
> [01/05/2024 08:32:32 > b80a7a: ERR ]    at MyAzureSolusion.MyService.Program.Main(String[] args) in 
> D:\WorkLib\DkDep372\Default_Win2019\1\44\s\MyAzureSolusion.MyService\Program.cs:line 17

And line 17 in the Program.cs looks like this:
```
 Log.Logger = new LoggerConfiguration()
     .ReadFrom.Configuration(Configuration)
     .WriteTo.Http("https://myloghandeling/api/LogHub/MyService",null, httpClient: new CustomHttpClient())
     .Enrich.FromLogContext()
     .Destructure.ToMaximumDepth(3)
     .CreateLogger();
```
where the `CustomHttpClient` looks like this:

```
public class CustomHttpClient : IHttpClient
{
    private readonly HttpClient httpClient;

    public CustomHttpClient() => httpClient = new HttpClient();

    public void Configure(IConfiguration configuration) => httpClient.DefaultRequestHeaders.Add("MyToken", TokenContainer.MyToken);

    public Task<HttpResponseMessage> PostAsync(string requestUri, HttpContent content) => httpClient.PostAsync(requestUri, content);

    public void Dispose() => httpClient?.Dispose();

    public async Task<HttpResponseMessage> PostAsync(string requestUri, Stream contentStream)
    {
        using (var content = new StreamContent(contentStream))
        {
            content.Headers.Add("Content-Type", "application/json");
            return await httpClient.PostAsync(requestUri, content);
        }
    }
}

```
appsettings.json containes this:
 ```
"Serilog": {
   "MinimumLevel": {
     "Default": "Information",
     "Override": {
       "Microsoft": "Warning",
       "Microsoft.EntityFrameworkCore.Database.Command": "Warning",
       "System": "Warning"
     }
   },
   "WriteTo": [
     { "Name": "Console" }
   ]
 },
```

**Comment by chunty** [comment]
I know this is an old post but I hit this. I had my setup in a seperate bootstrap project. I found I needed to specifically install Serilog.Sinks.PeriodicBatching and this sync to the bootstrap project and my web api project, then it was fine.

**Comment by jhelmink** [comment]
Here's something interesting for my version of this issue.

Using github deployments to an Azure Web Service with Test and Prod slots.

After updating to Serilog packages;
- Serilog.AspNetCore: 8.0.3
- Serilog.Expressions: 5.0.0
- Serilog.Sinks.Console: 6.0.0
- Serilog.Sinks.File: 6.0.0
- Serilog.Sinks.MSSqlServer: 8.0.0

Deployment and startup for the Test slot works without issue.
Deployment to the Prod slot works, but the App fails to startup with error;

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Sinks.PeriodicBatching, Version=3.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.`

My `appsettings.json` and `program.cs` is identical between instances, and additionally does not reference `Serilog.Sinks.PeriodicBatching`

To resolve this I had to manually add the `Serilog.Sinks.PeriodicBatching` package to the project.

Is one of the packages I'm using referencing the PeriodicBatching package without it being a dependency?

**Comment by brenwebber** [comment]
I had the same issue with the same packages referenced. Worked fine in dev, but gave that exact error when published. Fix was to include:

`<PackageReference Include="Serilog.Sinks.PeriodicBatching" Version="5.0.0" />`

Thanks @jhelmink for posting your comment, it got me there much faster.

**Comment by Numpsy** [comment]
> Is one of the packages I'm using referencing the PeriodicBatching package without it being a dependency?

Serilog.Sinks.MSSqlServer version 6.x depended on the PeriodicBatching sink but it doesn't look like v8 should - it's not somehow picking up the old version is it?

**Comment by jhelmink** [comment]
> > Is one of the packages I'm using referencing the PeriodicBatching package without it being a dependency?
> 
> Serilog.Sinks.MSSqlServer version 6.x depended on the PeriodicBatching sink but it doesn't look like v8 should - it's not somehow picking up the old version is it?

I just doubled checked in the NuGet UI and in my `.csproj` file itself and definitely on v8.0.0;

```
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.PeriodicBatching" Version="5.0.0" />
```

(Note that this now includes the PeriodicBatching package since I've had to manually install it)

Perhaps it's a caching issue in the deployment pipeline? That's all I could think it could be...

**Comment by garster** [comment]
Hi from 2026. Seems like Serilog will try to load libraries based on configuration. I have been trying to figure out which config cause what lib to load dynamically. We had a syslog sink missing but seemed like we did not seen it. I ripped all serilog out and added in jsut Serilog.AspNEtCode and now getting these Enrichers file not found. So very weird.
