### ISSUE TITLE
Ignore null properties from being written to output?

### ISSUE THREAD

**Issue by sachinramachandran** [serilog/serilog-aspnetcore#78]
I'm using serilog for my application and I have a complex object in my structured log. For example:

StructuredLog:{
"Message":"Test",
"Data": {
"Name" : "xyz",
"Dept" : null
}

Is there a way to remove dept from the structure above? "Data" is an entity in my application which I serialize directly.

**Comment by nblumhardt** [comment]
Hi! I have a feeling this is a duplicate and we've answered your question via another channel. If I'm mistaken please let me know - thanks!

**Comment by sachinramachandran** [comment]
Sorry this is the first time I'm posting this question but if you can link me to the similar post on another channel, that should do!

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog/issues/1286 is the one I was thinking of. If this doesn't cover it, implementing and plugging in your own `ILogEventEnricher` will give you a way to remove the nulls.
