### ISSUE TITLE
Migrating from Microsoft.AspNetCore.All to Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by etherni** [serilog/serilog-aspnetcore#79]
Hello,

Trying to set up Serilog for a newly created project in VS 2017 using ASP.NET Core Web App (MVC) template but with no luck.

What I noticed is your sample app using Microsoft.AspNetCore.All metapackage but Microsoft [recommends](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.2#migrating-from-microsoftaspnetcoreall-to-microsoftaspnetcoreapp) using Microsoft.AspNetCore.App. As soon as I updated the sample project to use Microsoft.AspNetCore.App it stopped working (no logs in console).

Can you please update sample application to reflect the latest recommendations?

Thank you!

**Comment by nblumhardt** [comment]
Hi! Thanks for getting in touch - this all works for me:

![image](https://user-images.githubusercontent.com/342712/53845170-ed28fd00-3ff3-11e9-9a46-3a3c59886e08.png)

Any clues in the screenshot above?

Best regards,
Nick

**Comment by nblumhardt** [comment]
Closing without any further info, but let us know if you find an issue that relates to this package. Thanks!
