### ISSUE TITLE
Change Sample to show how to use it in Startup

### ISSUE THREAD

**Issue by lnaie** [serilog/serilog-aspnetcore#83]
Hi,

The sample should show how to use it in Startup.ConfigureServices() and Startup.Configure().

Thanks

**Comment by luukholleman** [comment]
@lnaie Can you show how till it's added in the sample?

**Comment by IASamoylov** [comment]
@lnaie @luukholleman I found  [the post](https://ondrejbalas.com/using-serilog-with-asp-net-core-2-0/) from April 26, 2018. 

Solution:

Program.cs
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
       .UseStartup<Startup>()
       .UseSerilog(); // Improtant! UseSerilog need to use after UseStartup
```

Startup.cs
```csharp
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Debug()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .CreateLogger();
```
but we won't be able to use ILogger<T> in Startup.cs

**Comment by IASamoylov** [comment]
And another thought, if our application crashes on command `dotnet ./app.dll` then logs will be empty too.

**Comment by nblumhardt** [comment]
I think the original post might be looking for this alternative configuration:

https://github.com/serilog/serilog-extensions-logging/#net-core-10-11-and-default-provider-integration

HTH!
