### ISSUE TITLE
How to use with sinks that depend on ConfigureServices being run first?

### ISSUE THREAD

**Issue by cmeeren** [serilog/serilog-aspnetcore#84]
I'm using this with Serilog.Sinks.ApplicationInsights, but AFAIK there seems to be a conflict:

* When calling `.UseSerilog` with the `configureLogger` parameter, `configureLogger` (which among other things calls Serilog.Sinks.ApplicationInsights' `WriteTo.ApplicationInsights`) is executed before ASP.NET Core's `ConfigureServices`.
* `ConfigureServices` sets up `TelemetryConfiguration.Active`
*  `WriteTo.ApplicationInsights` needs `TelemetryConfiguration.Active` to be set up correctly

Is there a way to solve this?

**Comment by cmeeren** [comment]
cc @aloneguid

**Comment by cmeeren** [comment]
To be clear, here are the relevant parts of my startup/config code (F#):

```f#
type Startup() =
  member __.ConfigureServices(services) =
    services.AddApplicationInsightsTelemetry(fun conf ->
        conf.InstrumentationKey <- "..."
        conf.EnableAdaptiveSampling <- false)


module Program =

  [<EntryPoint>]
  let main args =
    WebHost
      .CreateDefaultBuilder(args)
      .UseSerilog(fun ctx conf -> 
        conf.WriteTo.ApplicationInsights(
          TelemetryConfiguration.Active,
          TelemetryConverter.Traces)
      .UseStartup<Startup>()
      .Build()
      .Run()
```

What I observe, is that sampling is enabled even though I explicitly disable adaptive sampling. I also know that ingestion sampling is disabled in Azure/AI. This leads me to the conclusion that the `TelemetryConfiguration.Active` in `WriteTo.ApplicationInsightsTraces()` might not be property initialized. Though I still get traces in AI, so I don't really understand how that could happen without the instrumentation key being configured, which happens at the same place as adaptive sampling...

(Proper AI config is a nightmare IMO, I've struggled for so long with it and still haven't gotten it right)

**Comment by cmeeren** [comment]
Nevermind. Turns out we had a rogue `ApplicationInsights.config` in a library far down the dependency hierarchy that was overriding stuff.

**Comment by cmeeren** [comment]
In fact, as far as the title of this issue goes, this is still a problem now that TelemetryConfiguration.Active is deprecated (https://github.com/microsoft/ApplicationInsights-dotnet/issues/1152).

In short:

* The Application Insights telemetry config is set up and registered with DI in `ConfigureServices` (so that it picks up all telemetry initializers and processors that are also registered), and therefore only available after it has run
* The telemetry config is needed when configuring Serilog
* `UseSerilog` is configured before `ConfigureServices` is called

How can this be solved?

**Comment by JasonTheProgrammer** [comment]
If you're using `services.Configure<TelemetryConfiguration>(..)`, as described in [this issue](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1152#issuecomment-518742922) regarding deprecation of `TelemetryConfiguration.Active`, then you can use `services.PostConfigure<T>(..)`, loosely documented [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.0#options-post-configuration).

So at a basic level, you could have something like this:

    .ConfigureServices((context, services) =>
    {
        string appInsightsKey = context.Configuration["APPINSIGHTS_INSTRUMENTATIONKEY"];

        services.Configure<TelemetryConfiguration>(tc =>
        {
            tc.InstrumentationKey = appInsightsKey;
        });

        services.PostConfigure<TelemetryConfiguration>(tc =>
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.ApplicationInsights(tc, TelemetryConverter.Traces)
                .CreateLogger();
        });
    })

**Comment by cmeeren** [comment]
Thanks! I will try that. But aren't I then losing out on logging startup exceptions?

**Comment by cmeeren** [comment]
After checking sources and experimenting for many hours today, here is a workaround I have arrived at. Let me know if I'm shooting myself in the foot.

In doing this I have sacrificed early startup errors, but I am successfully logging "late" startup errors (e.g. in the `Startup.Configure` method) to Application Insights.

`Program.fs`

```f#
[<EntryPoint>]
let main args =
  WebHost
    .CreateDefaultBuilder(args)
    .CaptureStartupErrors(true)
    .UseSerilog(dispose = true)
    .UseStartup<Startup>()
    .Build()
    .Run()
  0
```

`Startup.fs`

```f#
type Startup() =

  member __.ConfigureServices(services: IServiceCollection) : unit =
    services.AddApplicationInsightsTelemetry() |> ignore
    let sp = services.BuildServiceProvider()
    let telemetryConfig = sp.GetRequiredService<TelemetryConfiguration>()

    Log.Logger <-
      LoggerConfiguration()
        .WriteTo.ApplicationInsights(telemetryConfig, TelemetryConverter.Traces)
        .CreateLogger()

    services.AddSingleton<ILogger>(Log.Logger) |> ignore
```

**Comment by mikegoatly** [comment]
I can see how that would work - it feels very clunky though; building the service provider to configure something for the next time the service provider is built :)

I've got a feeling that calling IServiceCollection.BuildServiceProvider multiple times isn't great (the framework will call it for you once ConfigureServices exits unless you return a pre-built one) I can't remember where I read it - I'll do a bit of digging.

**Comment by mikegoatly** [comment]
Could you use a lambda ILogger registration instead? I'm unsure of the F# syntax, but in C# it would be:

``` csharp
services.AddSingleton<ILogger>(
    serviceProvider =>
    {
        Log.Logger = new LoggerConfiguration().WriteTo.ApplicationInsights(
                serviceProvider.GetRequiredService<TelemetryConfiguration>(),
                TelemetryConverter.Traces)
            .CreateLogger();

        return Log.Logger;
    });
```

**Comment by sungam3r** [comment]
Maybe related to #130

**Comment by sungam3r** [comment]
Yes, that's exactly how I wanted to use it.

**Comment by JasonTheProgrammer** [comment]
Regarding my earlier suggestion of using `services.PostConfigure<TelemetryConfiguration>(..)`, I'm finding that callback does **not** get called when using the AspNetCore WebHostBuilder. I.e. `WebHost.CreateDefaultBuilder()` from Microsoft.AspNetCore v2.2.0.

But `PostConfigure` *does* get called if using generic host, i.e. `HostBuilder` from Microsoft.Extensions.Hosting v2.2.0.

In the case of WebHost, I've found that if you're using a startup class, you can request an instance of `TelemetryConfiguration` in its constructor, and use it in the `Configure` method to configure the Serilog sink. As to whether that's early enough in the pipeline to meet your needs, that's up to you, but it's at least a pretty tidy option. In total, that would mean creating WebHost like:

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights() // Necessary
                .UseStartup<Startup>();
    }

    public class Startup
    {
        private TelemetryConfiguration _telemetryConfiguration;

        public Startup(TelemetryConfiguration telemetryConfiguration)
        {
            _telemetryConfiguration = telemetryConfiguration;
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // Use _telemetryConfiguration as necessary here to configure Serilog sink
        }
    }

**Comment by cmeeren** [comment]
> Could you use a lambda ILogger registration instead?

I just tried your suggestion, but then I don't get anything logged at all.

> EDIT: And now I've just discovered that `IWebHostBuilder.UseApplicationInsights()` was deprecated in [v2.8.0](https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/2.8.0/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsWebHostBuilderExtensions.cs). I'm getting woozy trying to follow all these changes! 🤪

Not sure if by the edit you intended to retract your previous suggestion:

> In the case of WebHost, I've found that if you're using a startup class, you can request an instance of `TelemetryConfiguration` in its constructor, and use it in the `Configure` method to configure the Serilog sink.

But if you still stand by that: Wouldn't that mean that serilog would use an unconfigured `TelemetryConfiguration`, since it gets injected (to `Startup`) before it's configured?

**Comment by JasonTheProgrammer** [comment]
In the case of WebHostBuilder in .NET Core 2.2, I've had good results injecting an instance of `TelemetryConfiguration` into the `Startup` class constructor. That was in conjunction with `IServiceCollection.AddApplicationInsightsTelemetry(string instrumentationKey)` from NuGet package Microsoft.ApplicationInsights.AspNetCore. And if custom `ITelemetryInitializer` implementations are needed, also configuring them in services. So, a complete example being:

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureServices((context, services) =>
            {
                services.AddSingleton<ITelemetryInitializer>(new MyCustomTelemInit());
                services.AddApplicationInsightsTelemetry(appInsightsKey);
            })
            .UseStartup<Startup>();

Then in `Startup`, take `TelemetryConfiguration` as a constructor parameter, and I configure logging in the class's `ConfigureServices(IServiceCollection svc)` implementation, like:

    public void ConfigureServices(IServiceCollection services)
    {
        // Your own Serilog logging config
        Logging.ConfigureSerilogLogging(Configuration, _telemetryConfiguration);
        services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
    }

By this strategy, by the time the web app starts, App Insights *and* Serilog is fully configured. It does mean that any logging you'd happen to be trying to do earlier in the startup pipeline would be missed, but, I guess things get a bit trickier if you need that (would maybe need to brute-force configuration outside of the host builder).

Meanwhile, in generic host (at least in 2.2, haven't tried 3.0 yet), I got good results by registering a hosted service as a "logging initialiser" to run before my main service. Something a bit like this (not an exact copy-paste, so please forgive any gremlins in the code):

    var builder = new HostBuilder()
        .ConfigureServices((context, services) =>
        {
            services.AddSingleton<ITelemetryInitializer>(new MyTelemInit());
            services.AddHostedService<SerilogInitialiserService>(); // A custom class
        })
        .AddWebJobs( /* config redacted /* ) // Your choice of HostBuilder service may differ
        .ConfigureLogging((context, log) =>
        {
            // Your necessary logging extension may differ.
            log.AddApplicationInsightsWebJobs(aiOptions =>
            {
                aiOptions.InstrumentationKey = aiKey;
                aiOptions.EnableLiveMetrics = false;
            });

            log.AddConsole();
        })
        .UseConsoleLifetime();

    internal class SerilogInitialiserService : IHostedService
    {
        private TelemetryConfiguration _telemetryConfiguration;
        private IConfiguration _configuration;

        public SerilogInitialiserService(
            TelemetryConfiguration telemetryConfiguration,
            IConfiguration configuration)
        {
            _telemetryConfiguration = telemetryConfiguration;
            _configuration = configuration;
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            // Your choice of Serilog logging configuration...
            Logging.ConfigureSerilogLogging(_configuration, _telemetryConfiguration);
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            Log.CloseAndFlush();
            return Task.CompletedTask;
        }
    }

**Comment by jorgeolive** [comment]
Hello,

I've been facing this problem as well. What are the drawbacks of forcing the InstrumentationKey in a generic ITelemetryInitializer class? Just like you would do to define the Cloud context properties. 

Thanks,
Jorge.
