### ISSUE TITLE
Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by bender2k14** [serilog/serilog-aspnetcore#85]
Serilog.AspNetCore currently [depends on version 2.0.0 of Microsoft.Extensions.Logging](https://github.com/serilog/serilog-aspnetcore/blob/a2c1d9c437f524b1488e27d40c1b789322b9889b/src/Serilog.AspNetCore/Serilog.AspNetCore.csproj#L30).  The latest version of [Microsoft.Extensions.Logging is 2.2.0](https://www.nuget.org/packages/Microsoft.Extensions.Logging/).

In order to remove a binding redirect from my code, could a new version of Serilog.AspNetCore be released that depends on this latest version of Microsoft.Extensions.Logging?

**Comment by svrooij** [comment]
As stated in the [Instructions](https://github.com/serilog/serilog-aspnetcore/blob/dev/README.md). You should use `Install-Package Serilog.AspNetCore -DependencyVersion Highest` which should install the highest Version of the dependencies.

That should help for now at least

**Comment by bender2k14** [comment]
Hello @svrooij.  Thanks for your suggestion.

I just followed your instructions and executed the command you provided in new solution/project.  As you can see in this screenshot, the version of Microsoft.Extensions.Logging installed is still just 2.0.0.
![Screenshot 2019-04-10 08 17 01](https://user-images.githubusercontent.com/34664007/55882894-dfbedf80-5b6a-11e9-99cd-209f9adfce1d.png)

Is this the behavior you expected?  If so, how does this answer the question in my original post?  If not, what behavior did you expect?

I am not completely sure what you or Microsoft ([here](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-install-package)) mean by "highest version" when stated as you both did without any explicit qualifications.  The definition I expect in the absence of any qualifications is the "maximum" version among released versions.  In the case of Microsoft.Extensions.Logging, this "maximum" released version is currently 2.2.0, so something is not right.

I have a guess, but I could be wrong.  My guess is that both you and Microsoft are implicitly including a qualification in the form of a restrictions imposed by the installed package(s).  Currently, Serilog.AspNetCore specifies that it [depends on precisely version 2.0.0 of Microsoft.Extensions.Logging](https://github.com/serilog/serilog-aspnetcore/blob/a2c1d9c437f524b1488e27d40c1b789322b9889b/src/Serilog.AspNetCore/Serilog.AspNetCore.csproj#L30).  So in the case of installing Serilog.AspNetCore via the command `Install-Package Serilog.AspNetCore -DependencyVersion Highest` and focusing on the dependency Microsoft.Extensions.Logging, the option `-DependencyVersion Highest` means the "maximum" version contain in the intersection of the set of all released versions of Microsoft.Extensions.Logging and the set of versions of Microsoft.Extensions.Logging allowed by Serilog.AspNetCore, which is just the singleton set containing version 2.0.0.  This guess is consistent with the fact that executing the command `Install-Package Serilog.AspNetCore -DependencyVersion DependencyVersionOption` for all values of `DependencyVersionOption` (namely `Lowest`, `HighestPatch`, `HighestMinor`, and `Highest`) all install version 2.0.0 of Microsoft.Extensions.Logging.

**Comment by nblumhardt** [comment]
@bender2k14 if you add an explicit dependency on _M.E.Logging_ version 2.2 to your own CSPROJ, that's the version you'll end up building against. This package works with any of the 2.x MEL versions, the binding redirect is just how this ends up manifesting on the .NET Framework, I think.

**Comment by bender2k14** [comment]
> This package works with any of the 2.x MEL versions

Can you state this programmatically in your code?

Currently your code says otherwise.  [It says](https://github.com/serilog/serilog-aspnetcore/blob/a2c1d9c437f524b1488e27d40c1b789322b9889b/src/Serilog.AspNetCore/Serilog.AspNetCore.csproj#L30) that it only works with version 2.0.0:
> PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0"

One way to state this programmatically in your code is to change that line to
> PackageReference Include="Microsoft.Extensions.Logging" Version="2.*"

See [this documentation](https://docs.microsoft.com/en-us/nuget/reference/package-versioning) for more examples and explanation.

**Comment by adamchester** [comment]
![3FCDA214-E030-4E6E-86CF-F0177ED20F19](https://user-images.githubusercontent.com/570470/58210667-6ac7f380-7d2d-11e9-8188-44ca49e53667.jpeg)

I think we have already stated it programmatically by using “2.0.0”. In NuGet, this means `>= 2.0.0`

**Comment by bender2k14** [comment]
@adamchester I would believe you if your code specified the dependent version as `2.0`. Instead, your code specifics the dependent version as `2.0.0`.

**Comment by nblumhardt** [comment]
Hi @bender2k14 - the docs are pretty tough to interpret precisely, in this regard, but the notation `x.y` or `x.y.z` is a minimum-version spec. If you want to specify an exact version, it's `[x.y]` or `[x.y.z]`. (Per the link you provided above.)

If you expand "Dependencies" for this package on NuGet.org you'll see it called out explicitly: https://www.nuget.org/packages/serilog.aspnetcore

We tried the `2.*` wildcard option earlier and broke some builds: subtly, version wildcards are resolved _at package build time_ and not at install time, so specifying `2.*` got us a fixed `2.2.0` dependency in the package itself ([discussion](https://github.com/serilog/serilog-extensions-logging/pull/133#pullrequestreview-229349328)).

Specifying the desired version of MEL from your own CSPROJ alongside your reference to this package will always get you the version you want.

HTH

**Comment by bender2k14** [comment]
Oh, that's good. That makes things a bit easier.

I see that your NuGet file...
https://www.nuget.org/packages/Serilog.AspNetCore/2.1.1
...does explicitly say that it works with version 2.0.0 or greater.

I still want to figure out why my tests above didn't install the latest version :/

Thanks for all your patience with me :)

**Comment by nblumhardt** [comment]
Thanks @bender2k14 :+1:
