### ISSUE TITLE
using serilog with RunAsService

### ISSUE THREAD

**Issue by BlueDragon709** [serilog/serilog-aspnetcore#86]
Hello,

I am using Serilog to log my errors and everything.
It works great. But now that i configured my Asp.net Core app to run as a service it's not working anymore.

Did i do something wrong?
Here is my Program.cs:

`
    using System;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;
    using Microsoft.AspNetCore;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Hosting.WindowsServices;
    using Serilog;
    using Serilog.Events;

    namespace GameServer
    {
        public class Program
        {
            public static void Main(string[] args)
            {
                Log.Logger = new LoggerConfiguration()
                    .MinimumLevel.Debug()
                    .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                    .Enrich.FromLogContext()
                    .WriteTo.File("logs\\log.txt", rollingInterval: RollingInterval.Day)
                    .WriteTo.Console()
                    .CreateLogger();

                try
                {
                    Log.Information("Starting GameServer");

                    var isService = !(Debugger.IsAttached || args.Contains("--console"));

                    if (isService)
                    {
                        var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
                        var pathToContentRoot = Path.GetDirectoryName(pathToExe);
                        Directory.SetCurrentDirectory(pathToContentRoot);
                    }

                    var builder = CreateWebHostBuilder(args.Where(arg => arg != "--console").ToArray());
                    var host = builder.Build();

                    if (isService)
                    {
                        Log.Information("Strating as service");
                        host.RunAsService();
                    }
                    else
                    {
                        Log.Information("Starting as console");
                        host.Run();
                    }

                    //CreateWebHostBuilder(args).Build().Run();
                }
                catch (Exception e)
                {
                    Log.Fatal(e, "Host terminated unexpectedly");
                    throw;
                }
                finally
                {
                    Log.CloseAndFlush();
                }
            }

            public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
                WebHost.CreateDefaultBuilder(args)
                    .UseKestrel()
                    .UseUrls("http://0.0.0.0:5431")
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseStartup<Startup>()
                    .UseSerilog();
        }
    }
`

**Comment by nblumhardt** [comment]
Hi! Sorry about the lack of reply, here. This is more than likely due to the working directory of the service turning the file log path into something unexpected, or a permissions issue. I'll close this as stale, assuming you've found some way forward in the meantime, but I'll keep an eye out on SO in case you are able to surface more details.

**Comment by BlueDragon709** [comment]
Yeah I allready found a fix.
