### ISSUE TITLE
Support for .NET Core 3?

### ISSUE THREAD

**Issue by ffMathy** [serilog/serilog-aspnetcore#88]
Can we get support for .NET Core 3?

**Comment by nblumhardt** [comment]
Hi! What kind of incompatibility are you hitting? It might be that you need https://github.com/serilog/serilog-extensions-hosting instead of this package. HTH!

**Comment by ffMathy** [comment]
I wasn't actually hitting an incompatibility per se. I just thought there was no support since all the NET core packages have been bumped to v3, but not this Budget package.

So all good I guess.

**Comment by nblumhardt** [comment]
:+1:
