### ISSUE TITLE
Serilog imports.

### ISSUE THREAD

**Issue by malkaviano** [serilog/serilog-aspnetcore#89]
The documentation should document what are the Serilog most important namespaces.

Not everybody is using VS and VS Code does not have that feature (thank god, now I realize how stupid one can become relying too much on the IDE) .

Btw, I discovered the namespaces looking @ the source code, but you really should consider documenting it and updating the install package command.

**Comment by adamchester** [comment]
Thanks for the suggestion @malkaviano. May I ask more specifically what you were doing that needed to open namespaces related to this package?

**Comment by malkaviano** [comment]
@adamchester Like to run the sample on the README one need to know what namespaces to import. 

Where else would I look for?

**Comment by nblumhardt** [comment]
Is it just `using Serilog;` that your configuration needed, @malkaviano ? Scanning this README I can't spot any code that should need others, but I could be missing it....

**Comment by nblumhardt** [comment]
(I'm keen to add `using Serilog;` in there to clarify it, but as I think @adamchester is getting at, we want to make sure we solve the actual problem that you're hitting :-))

**Comment by malkaviano** [comment]
Yes, that will do the trick.

`using Serilog.Events;` is also nice for LogEventLevel.

**Comment by nblumhardt** [comment]
Thanks @malkaviano - I've added `using Serilog;` - in this example I don't think `LogEventLevel` plays a very prominent part so we might be best off saving the clutter, for now.
