### ISSUE TITLE
ReadFrom.Configuration() method not found

### ISSUE THREAD

**Issue by learntecno** [serilog/serilog-aspnetcore#9]
Hi I try to load the settings from the appsetting.json in asp.net core 2.0, I followd the sample but the below method is not available. please let me know how to do
LoggerConfiguration()
                .ReadFrom.Configuration()
Thanks,

**Comment by luxcan** [comment]
If I am not wrong, you need to include "Serilog.Settings.Configuration" package in order to overwrite the ReadFrom method.

https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/SimpleWebSample/SimpleWebSample.csproj

**Comment by learntecno** [comment]
Thank you, It helped

**Comment by ganeshpaiya** [comment]
thanks work for me
