### ISSUE TITLE
Disable logs to Console

### ISSUE THREAD

**Issue by PedroS11** [serilog/serilog-aspnetcore#92]
Is it possible to log to file and not logging to console? Printing to console is taking to much time on my API's and I only want file's log.

**Comment by nblumhardt** [comment]
Hi @PedroS11 - can you please post some more information about your configuration? For example, the `LoggerConfiguration()` part, and how you're calling `UseSerilog()`?

Removing the console logger should be as simple as deleting the `WriteTo.Console()` line, but your setup may be more complex.

Cheers,
Nick

**Comment by PedroS11** [comment]
Of course, I forgot about posting my code.

On Startup.cs I have this:

```
public Startup(IConfiguration configuration) {
      Log.Logger = new LoggerConfiguration().ReadFrom.Configuration(configuration).CreateLogger();
}
```

My appsettings.json is 

```json
{"Serilog": {
    "MinimumLevel": "Fatal",
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "File",
              "Args": {
                "path": "..\\Logs\\log.txt",
                "rollingInterval": "Day", 
                "retainedFileCountLimit": 5, 
                "fileSizeLimitBytes": 1073741824, 
                "rollOnFileSizeLimit": true, 
                "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {Message}{NewLine}{Exception}{NewLine}"
              }
            }
          ]
        }
      }
    ],
    "Properties": {
      "Application": "Common feature in WebApi demo"
    }
  }
}

**Comment by nblumhardt** [comment]
How is ASP.NET Core logging set up? Are you using `UseSerilog()` and have you removed the default logging configuration from Startup.cs? Cheers!

**Comment by PedroS11** [comment]
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILogger<Startup> logger, ILoggerFactory loggerFactory) {
                loggerFactory.AddSerilog();
// Some code for swagger
        }
```

You are talking about this?

**Comment by nblumhardt** [comment]
This will leave the default ASP.NET Core logging configuration intact; the README for this repo shows how to use `UseSerilog()`, instead of `AddSerilog()`, to replace it; otherwise, you'll need to find the appropriate method to clear the built in providers for the version of ASP.NET Core you're using (`ILoggingBuilder` in 2.0 has a `ClearProviders()` method for this). HTH!

**Comment by nblumhardt** [comment]
Closing as stale, but let me know if you didn't track the right option down.
