### ISSUE TITLE
UseSerilogRequestLogging is not present in the Nuget package v2.1.1

### ISSUE THREAD

**Issue by ruskindantra** [serilog/serilog-aspnetcore#98]
I have looked at your samples where you demonstrate the use of `app.UseSerilogRequestLogging();` although it uses the `Serilog.AspNetCore` project directly.  As soon as you use the Nuget package it can no longer find the extension method.

Can you please verify that the extension method is correctly built into your nuget package please?

**Comment by ruskindantra** [comment]
![image](https://user-images.githubusercontent.com/4995778/61180712-a5377800-a66e-11e9-9d48-26c175a796f4.png)

![image](https://user-images.githubusercontent.com/4995778/61180717-ae284980-a66e-11e9-8071-81146e1efca3.png)

**Comment by ruskindantra** [comment]
I just realised that I was looking at your `dev` branch and not the current release branch, closing the issue, hopefully it helps someone else who lands on this page

**Comment by nblumhardt** [comment]
Thanks for the follow-up and sorry about the confusion. It's one of the less-than-ideal side-effects of GitHub's "default branch" mechanism.

**Comment by StefanFrederiksen** [comment]
Just to check in on this, does this mean that the extension is not in the v2.1.1 nuget package at all, but will be released in the future?

Asking because on a fresh new project, and downloading the newest nuget package, the extension method cannot be found.

**Comment by nblumhardt** [comment]
@StefanFrederiksen 👍 it's in the published 3.0.0-dev-* package versions, and will be RTM'd as 3.0.0.

**Comment by StefanFrederiksen** [comment]
Alright, the readme states it like it's available for use now, which is a bit confusing. Maybe this could use some clarification so other people don't stumble into the same misunderstanding.

**Comment by nblumhardt** [comment]
@StefanFrederiksen I've made some subtle README tweaks that should help with this
